### ISSUE TITLE
iPhone 5s failing to restore to 10.3.3

### ISSUE THREAD

**Issue by AverageUser231** [LukeZGD/Legacy-iOS-Kit#284]
Every time I get to the restore process, it just fails. If it matters, I use gaster to pwn my device because ipwnder never works

[log.txt](https://github.com/LukeZGD/Legacy-iOS-Kit/files/11182998/log.txt)

**Comment by LukeZGD** [comment]
Try using another USB cable/port. According to #273, you may have better luck trying USB ports on the motherboard
