### ISSUE TITLE
Restoring to dumped iOS 7 blobs results in corrupted /var and recovery mode loop

### ISSUE THREAD

**Issue by nameless1O1** [LukeZGD/Legacy-iOS-Kit#285]
I have an iPhone 5c with iOS 7.1.1 blobs that were dumped using Legacy-iOS-Kit, but when I restore to them the device gets stuck in a recovery mode loop, and upon further investigation using an SSHRD, /var is completely empty.

**Comment by LukeZGD** [comment]
No idea, sorry. But recovery mode loop sounds like an NVRAM issue. You can go to Other Utilities -> Clear NVRAM to clear all values in NVRAM.

**Comment by nameless1O1** [comment]
Clearing NVRAM fixed it, thank you.
