### ISSUE TITLE
Sending IBEC stuck at 78% 

### ISSUE THREAD

**Issue by davidexpress** [LukeZGD/Legacy-iOS-Kit#286]
Hi, i have an iPad Mini 2 WiFi (IPad 4,4) and i am trying to restore to iOS 10.3.3 and it get stuck at IBEC stuck at 78.9%

I am using Windows 11 

What should i do?

Thank you in advance

**Comment by LukeZGD** [comment]
https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting#windows
