### ISSUE TITLE
appsync unified removes all the apps on ios 5

### ISSUE THREAD

**Issue by Naxy21** [LukeZGD/Legacy-iOS-Kit#292]
i restored my iPhone 4 to iOS 5, and i installed appsync unified, and all my apps from the home screen are gone, i had to restore it again to be functional again, it says it's compatible with iOS 5 and my iPad 1 has appsync working fine, does anyone know what the issue might be? is it appsync or another thing?

**Comment by LukeZGD** [comment]
Looks like a pris0nbarake/unthredeh4il bug. I'll try to look into it, but no guarantees.. For now, the solution is disable the jailbreak option and jailbreak with Absinthe

**Comment by LukeZGD** [comment]
upon doing testing, looks like restarting the phone fixes the missing icons

**Comment by Naxy21** [comment]
it does! thank you so much for the help!
