### ISSUE TITLE
iPhone 5,1 8.4.1 apps disappear after Cydia essential upgrade

### ISSUE THREAD

**Issue by Cosmicdesert11** [LukeZGD/Legacy-iOS-Kit#293]
The iPhone is activation lock bypassed with Sliver 6.2 so i can't sideload etasonJB. I use the built in jailbreak option and restore, then bypass, and i open cydia with it "preparing filesystems". then it asks for an essential upgrade and i download and install when the screen turns black and i lock the phone and when i unlock all the apps disappear except for newstand but restarting gets rid of newstand.

**Comment by LukeZGD** [comment]
Disappearing app icons is a well-known issue with EtasonJB, not much I can do with it unfortunately (I can try making daibutsuCFW compatible with all A5/A6 devices sometime, but don't count on it)

Maybe try this and see though: https://www.reddit.com/r/jailbreak/comments/71yzgz/tutorial_how_to_fix_missing_icons_and_app/
