### ISSUE TITLE
Restoring issue

### ISSUE THREAD

**Issue by pogrebalnaagencia** [LukeZGD/Legacy-iOS-Kit#294]
Hi I've been trying to restore iPhone 3GS to iOS 3.1.3 and iOS 5.1.1. Everything fine, until going to restore. When I start the restore it immidietly says that everything is done, but actually nothing happens. Im using macOS High Sierra, and tried a two versions of Legacy iOS Kit.

**Comment by LukeZGD** [comment]
Do you have a full log/terminal output

**Comment by LukeZGD** [comment]
yes i do have discord: `lukezgd`

i'm also active in legacyjailbreak discord: discord.legacyjailbreak.com

**Comment by LukeZGD** [comment]
Issue resolved, idevicerestore and tools seem to work better on newer Mac versions
