### ISSUE TITLE
when launching ./restore.sh on gentoo it says its unsupported

### ISSUE THREAD

**Issue by Devel-ash** [LukeZGD/Legacy-iOS-Kit#295]
when i try to launch the script it says unsupported even with the ios use flag

**Comment by LukeZGD** [comment]
Oh, I didn't even notice that Gentoo was missing from the script since the rewrite, sorry about that. Will be re-adding it now

**Comment by Devel-ash** [comment]
oh ok then i thought i removed an important flag
