### ISSUE TITLE
Linux Mint not detected/supported

### ISSUE THREAD

**Issue by MarioKartEpicness** [LukeZGD/Legacy-iOS-Kit#296]
Installed a fresh copy of the latest version Linux Mint Cinnamon edition from https://www.linuxmint.com/ in the readme, Installed all updates to Linux Mint & went through the setup steps, but the distro is still not detected as supported. Is their something i'm doing wrong? I could try another distro but hoped I didn't have to go through the hassle again. Log in txt.
[Unsaved Document 1.txt](https://github.com/LukeZGD/Legacy-iOS-Kit/files/11814171/Unsaved.Document.1.txt)

**Comment by LukeZGD** [comment]
I'll be fixing the Ubuntu version detecting

**Comment by LukeZGD** [comment]
Fixed in v23.06.22

**Comment by MarioKartEpicness** [comment]
confirmed it recognizes Linux Mint, cheers
