### ISSUE TITLE
Pwndfu Linux iOS 10.3.3 Downgrade

### ISSUE THREAD

**Issue by Eow2022yia** [LukeZGD/Legacy-iOS-Kit#297]
Hello there,

I am fully aware that Pwndfu is very unreliable on Linux, however I don't have a MAC so what is your best suggestion? Do you know of any other tools that may work to downgrade my iPhone 5S to 10.3.3?

Thank you.

**Comment by LukeZGD** [comment]
If you have another iOS device, go here: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Pwning-Using-Another-iOS-Device

Then proceed to use Legacy iOS Kit
