### ISSUE TITLE
Support for hacktivation and icloud bypassing on older devices

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/Legacy-iOS-Kit#299]
Hello @LukeZGD, 

I would like to thank you for making this awesome tool for legacy devices. This kit really makes them still usable in 2023 and gives lots of opportunities to explore different iOS versions. But a common problem with older iOS devices is that many of them are getting bricked because the owner forgets to disable Find My when tossing the device out making it useless in normal circumstances since you cannot activate it. But there are some methods to bypass activation which make iCloud locked devices to be usable which is a really life saving thing. So is it possible to make an addition to legacy-iOS-kit and add support for hacktivation and iCloud bypass for older 32 bit and A7 devices?

Sincerely,

**Comment by LukeZGD** [comment]
I do not plan on adding that, sorry. Though, SSH Ramdisk is available for supported 32-bit devices for those who want to try it manually. For older devices, greenpois0n's hacktivation files can be found here: https://github.com/Chronic-Dev/anthrax
