### ISSUE TITLE
trying to use zorin os 16 and it's not working

### ISSUE THREAD

**Issue by ethanodonnell** [LukeZGD/Legacy-iOS-Kit#300]
hi i was using zorin os 16 pro (based on ubuntu) and its not working and says its an unsupported os even tho the readme says an ubuntu based os can be used

**Comment by ethanodonnell** [comment]
UPDATE:
i got a live usb of ubuntu 23.06 and have tried using restore.sh, unfortunately it has been very difficult and will read the iphone until i run the script, then the iphone will disconnect and reconnect, giving the following script. i also got continuous crashes when the program/iphone was plugged in

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Enter your user password when prompted
[Log] Running on platform: linux (Ubuntu 23.04)
[Log] Checking Internet connection...
* Version: v23.07.01 (f1247bb)
[Log] Checking for updates...
[Log] Getting device info...
[Error] No device found! Please connect the iOS device to proceed.
* Make sure to trust this computer by selecting "Trust" at the pop-up.
* For more details, read the "Troubleshooting" wiki page in GitHub.
* Troubleshooting link: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting
ubuntu@ubuntu:~$

**Comment by LukeZGD** [comment]
zorin os 16 is based on ubuntu 20.04, so it's not supported. as for the usb problems, yea usbmuxd is probably causing problems there. you can try putting the device in dfu mode then running the script again.

or you can also try this: run `sudo systemctl stop usbmuxd; sudo usbmuxd -pf` in another terminal window, then run the script with `./restore.sh --disable-usbmuxd`
