### ISSUE TITLE
I recently downgraded the baseband device with shsh blobs, and recently encountered the following error.

### ISSUE THREAD

**Issue by ChenKanNing** [LukeZGD/Legacy-iOS-Kit#304]
CurrentDirectory: C:\Users\1\Desktop\futurerestore
usbmuxd: usbmuxd_get_device_list
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status i
formation
[TSSC] opening /tmp/futurerestore/basebandManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested bu
ld.

ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.
)
baseband firmware isn't signed
Failed with errorcode=-3

**Comment by LukeZGD** [comment]
What are you trying to do here? What device and do you have full terminal output?

**Comment by LukeZGD** [comment]
Cool, then.. I guess I can close this?
