### ISSUE TITLE
Jailbreak option error

### ISSUE THREAD

**Issue by alexo0o** [LukeZGD/Legacy-iOS-Kit#306]
Whenever I select no to jailbreaking it skips a prompt to enable it going faster but requiring 8gb of ram and it seems to get stuck on

"Did set sep+baseband path and firmware" (sat for about 30 minutes)

When I do say yes to jailbreaking it gives me that prompt and it works properly

This may be something unrelated to the jailbreaking prompt as i also restarted and instead of installing the ipsw and continuing with it auto selected i manually selected the ipsw

Also don't know what happens if you say yes to the second prompt

Edit// not sure if its of any significance but i was using

All devices, jailbroken on iOS 9 or lower (alternative)

iPhone 4S
9.3.6 >> 8.1.4
Ubuntu 22.04.2
Installed on computer, not a live usb

**Comment by LukeZGD** [comment]
Do you have full terminal log/output
