### ISSUE TITLE
Can't activate my iPhone after using powdersn0w 7.x blobs restore

### ISSUE THREAD

**Issue by yzh9865** [LukeZGD/Legacy-iOS-Kit#307]
tried almost every ios ,can't activate iPhone 5(server unavailable).It was all good before yesterday's version update except I can't charge my iPhone pass 78 percent on every ios 8 version, this version v23.07.08 now can't even let me activate the iPhone, please do check this issue and hopefully get a fix, thank you

**Comment by LukeZGD** [comment]
Try again on v23.07.09. If the restore fails on updating baseband, try doing this:

1. Delete all existing Custom IPSWs
2. Run `./restore.sh`
3. Restore to iOS 10.3.4, or 8.4.1 with jailbreak option enabled
4. Make sure that your device is jailbroken
7. Run `./restore.sh --disable-bbupdate`
    - Output should show: `Disable bbupdate flag detected, baseband update is disabled`
9. Select Restore/Downgrade with powdersn0w to your selected target version
10. The script should dump the baseband of your device
    - Overwrite `baseband.tar` if asked
12. Device should restore and activate successfully

**Comment by yzh9865** [comment]
Hi, thanks for the instruction, I’ll try later, just saw new update again, is there any chance you will make dora’s 32bit  ios10 untether jailbreak with ios7 iboot bug into this script in the future? I tried dora’s p0insettia <https://github.com/dora2-iOS/p0insettia> script, seems unfinished, I can’t make it work, if ios10 untether is already there for years, why not make it feasible.

**Comment by LukeZGD** [comment]
> Hi, thanks for the instruction, I’ll try later, just saw new update again, is there any chance you will make dora’s 32bit ios10 untether jailbreak with ios7 iboot bug into this script in the future? I tried dora’s p0insettia <https://github.com/dora2-iOS/p0insettia> script, seems unfinished, I can’t make it work, if ios10 untether is already there for years, why not make it feasible.
> […](#)
> On Jul 19, 2023, at 6:58 PM, LukeeGD ***@***.***> wrote: 10.3.4

I do have a fork named p0insettia plus: https://github.com/LukeZGD/p0insettia-plus

I will try working on adding support for all iPhone 5 and 5C devices sometime

**Comment by yzh9865** [comment]
That’s amazing, is there any guide on how to use untether script in p0insettia plus?------------------Best regards!On Jul 19, 2023, at 8:53 PM, LukeeGD ***@***.***> wrote:﻿

Hi, thanks for the instruction, I’ll try later, just saw new update again, is there any chance you will make dora’s 32bit ios10 untether jailbreak with ios7 iboot bug into this script in the future? I tried dora’s p0insettia https://github.com/dora2-iOS/p0insettia script, seems unfinished, I can’t make it work, if ios10 untether is already there for years, why not make it feasible.
…
On Jul 19, 2023, at 6:58 PM, LukeeGD @.***> wrote: 10.3.4

I do have a fork named p0insettia plus: https://github.com/LukeZGD/p0insettia-plus
I will try working on adding support for all iPhone 5 and 5C devices sometime
