### ISSUE TITLE
How to Downgrade iPhone 4 GSM (3,1)

### ISSUE THREAD

**Issue by systemd11** [LukeZGD/Legacy-iOS-Kit#308]
Hi, 

I wanted to Downgrade my iPhone 4 to iOS 6. I selected Downgrade with powdersn0w. But it tells me to select Base or Target IPSW. Tried both but idk what to do.
Thanks!!

**Comment by LukeZGD** [comment]
Target IPSW: iOS 6

Base IPSW: iOS 7.1.2

Download both IPSWs in IPSW.me
