### ISSUE TITLE
Script gets stuck while downgrading - iPhone 3,1 

### ISSUE THREAD

**Issue by cyg0** [LukeZGD/Legacy-iOS-Kit#309]
Hello,
I tried downgrading my iPhone 3,1 to iOS 5.1.1(9B208) using your tool on live Ubuntu image. After running `./restore.sh` everything goes smoothly until script gets stuck on `Waiting for device...` and phone reboots to iOS 7 Recovery Mode.
I tried disabling jailbreak option but I got same output.

I hope you can help me
I wish you well!

Log:
[log.txt](https://github.com/LukeZGD/Legacy-iOS-Kit/files/12175856/log.txt)

**Comment by LukeZGD** [comment]
Try this:

- On a second terminal window, run `sudo systemctl stop usbmuxd; sudo usbmuxd -pf`
- Go back to the first terminal window, launch the script with `./restore.sh --disable-usbmuxd`

**Comment by LukeZGD** [comment]
You may also try again with v23.07.14 which (hopefully) fixes this issue entirely
