### ISSUE TITLE
Tethered downgrade iOS 7 iPhone 5S

### ISSUE THREAD

**Issue by tolikes** [LukeZGD/Legacy-iOS-Kit#310]
Hello sir, you can add an automated option to downgrade tethered as it was a pain in the ass with IDA64 arm https://ios7.iarchive.app/downgrade/

I have faith that it is possible to automate it and the modified files like kernelcache can be uploaded on the web and downloaded with wget for the end user

**Comment by tolikes** [comment]
For example prebuilt ipsw and just boot with the script that feature in your restore.sh would be a great thing.

**Comment by LukeZGD** [comment]
Sorry but I do not plan on ever supporting anything tethered in Legacy iOS Kit (tethered restores/downgrades and jailbreaks)

Legacy iOS Kit will support untethered restores/downgrades and jailbreaks only, anything that is semi-untethered/semi-tethered/tethered is not worth adding
