### ISSUE TITLE
iphone 4 not supported?

### ISSUE THREAD

**Issue by Bitterbuffaloh** [LukeZGD/Legacy-iOS-Kit#313]
I get this when I run the restore:

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Enter your user password when prompted
[Log] Running on platform: linux (Ubuntu 22.04.2 LTS)
[Log] Checking Internet connection...
* Version: v23.08.09 (fe86044)
[Log] Checking for updates...
[Log] Finding device in Normal mode...
[Log] Getting device info...
ERROR: Could not connect to lockdownd: Invalid HostID (-21)
[Input] Enter device type (eg. iPad2,1): iphone 4
* Device: iphone 4 (n90ap) in Normal mode
* iOS Version: 7.1.2
* ECID: 3665989854669

[Error] This device is not supported by Legacy iOS Kit.

**Comment by LukeZGD** [comment]
The correct device type is `iPhone3,1`

Put that in the input device type
