### ISSUE TITLE
Would you consider adding a lockdownd patch if possible?

### ISSUE THREAD

**Issue by halal-beef** [LukeZGD/Legacy-iOS-Kit#315]
When I downgraded my iPhone 4 to iOS 4.3, it was really hard to activate without a sim, and DFU being almost impossible to acces with a nearly dead homebutton I couldn't hacktivate in any way, I had to use sn0wbreeze to make a hacktivated 4.3 ipsw, extract the ipsw, extract the DMG, find lockdownd, then push it to the iPhone using and SCP Client, it takes a bit of time to do this and it could be avoided via an option to make the ipsw hacktivated

**Comment by LukeZGD** [comment]
I can get the lockdownd patches from sn0wbreeze, but I don't think I will be adding them to Legacy iOS Kit to comply with LegacyJailbreak rules (3GS and older only)

I might be adding support and patches for 2G and 3G sometime though

**Comment by halal-beef** [comment]
Ah, thanks for the info
