### ISSUE TITLE
How did you setup usbmuxd for Legacy iOS Devices?

### ISSUE THREAD

**Issue by systemd11** [LukeZGD/Legacy-iOS-Kit#317]
Idk how you did it but lmd tells me "No Device found". Just wanted to Backup my iPhone 4s on iOS 6 but it does not work? How do you make lmd recognize legacy iOS Devices for your script?

**Comment by LukeZGD** [comment]
when script starts: https://github.com/LukeZGD/Legacy-iOS-Kit/blob/d0eabcf25beef8583f16d8cf5768ceb7c3b77a33/restore.sh#L218

`sudo systemctl stop usbmuxd; sudo usbmuxd -pf`

when script stops: https://github.com/LukeZGD/Legacy-iOS-Kit/blob/d0eabcf25beef8583f16d8cf5768ceb7c3b77a33/restore.sh#L48

`sudo systemctl restart usbmuxd` twice
