### ISSUE TITLE
Can't downgrade iPad Mini 2: Terminal output below

### ISSUE THREAD

**Issue by ikdotinnmoodayaa** [LukeZGD/Legacy-iOS-Kit#321]
Hi, I've spent a lot of time last few days trying to get my iPad Mini 2 to downgrade but I keep getting the same error in terminal using the restore.sh script I got from here. I'm not sure what part of my installation it is right or wrong so a few details.

I've jailbroken with Chimera, which I believe is the only option for me. I even tried to reset NVRAM as suggested in troubleshooting but not sure it worked. I've even fixed up my old 2012 macbook pro (since macbook pro 2016 only has usb-c ports) to see if the usb-c adapters (tried two) were the issue. Tried different cables and they all get the same issue which is listed below. Thank you for reading, I hope you'll be able to help because reddit sent me here and jailbreak's discord server chat and genius bar didn't offer answers.

Last login: Tue Aug 29 23:32:06 on ttys000
ebayusers-MacBook-Pro:~ ebayuser$ /Users/ebayuser/Downloads/Legacy-iOS-Kit_macos_v23.08.15/restore.sh 

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

[Log] Running on platform: macos (10.13.6)
[Log] Checking Internet connection...
* Version: v23.08.18 (dd22438)
[Log] Checking for updates...
* A newer version of Legacy iOS Kit is available.
* Current version: v23.08.18 (dd22438)
* Latest version:  v23.08.19 (bcb605e)
* Please download/pull the latest version before proceeding.
[Input] Do you want to update now? (Y/n): y
[Log] Downloading: https://github.com/LukeZGD/Legacy-iOS-Kit/releases/download/latest/Legacy-iOS-Kit_macos_v23.08.19.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 42.3M  100 42.3M    0     0  5443k      0  0:00:07  0:00:07 --:--:-- 5078k
[Log] Updating...
[Log] Done! Please run the script again
ebayusers-MacBook-Pro:~ ebayuser$ /Users/ebayuser/Downloads/Legacy-iOS-Kit_macos_v23.08.15/restore.sh 

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

[Log] Running on platform: macos (10.13.6)
[Log] Checking Internet connection...
* Version: v23.08.19 (bcb605e)
[Log] Checking for updates...
[Log] Finding device in Normal mode...
[Log] Getting device info...

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v23.08.19 (bcb605e)
* Platform: macos (10.13.6) 

* Device: iPad4,5 (j86ap) in Normal mode
* iOS Version: 12.5.7
* ECID: 8476295725104

 > Main Menu
[Input] Select an option:
1) Restore/Downgrade  3) Other Utilities
2) Save SHSH Blobs    4) Exit
#? 1

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v23.08.19 (bcb605e)
* Platform: macos (10.13.6) 

* Device: iPad4,5 (j86ap) in Normal mode
* iOS Version: 12.5.7
* ECID: 8476295725104

 > Main Menu > Restore/Downgrade
[Input] Select an option:
1) iOS 10.3.3   3) Go Back
2) Other (Use SHSH Blobs)
#? 1
[Log] Verifying ../iPad_64bit_10.3.3_14G60_Restore.ipsw...
[Log] IPSW SHA1sum matches

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v23.08.19 (bcb605e)
* Platform: macos (10.13.6) 

* Device: iPad4,5 (j86ap) in Normal mode
* iOS Version: 12.5.7
* ECID: 8476295725104

* Selected IPSW: ../iPad_64bit_10.3.3_14G60_Restore.ipsw

 > Main Menu > Restore/Downgrade > iOS 10.3.3
[Input] Select an option:
1) Select Target IPSW 3) Start Restore
2) Download Target IPSW 4) Go Back
#? 2
[Log] Verifying ../iPad_64bit_10.3.3_14G60_Restore.ipsw...
[Log] IPSW SHA1sum matches
[Log] Verifying ../iPad_64bit_10.3.3_14G60_Restore.ipsw...
[Log] IPSW SHA1sum matches

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v23.08.19 (bcb605e)
* Platform: macos (10.13.6) 

* Device: iPad4,5 (j86ap) in Normal mode
* iOS Version: 12.5.7
* ECID: 8476295725104

* Selected IPSW: ../iPad_64bit_10.3.3_14G60_Restore.ipsw

 > Main Menu > Restore/Downgrade > iOS 10.3.3
[Input] Select an option:
1) Select Target IPSW 3) Start Restore
2) Download Target IPSW 4) Go Back
#? 3
[Log] Patching iBSS and iBEC...
Archive:  ../iPad_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBSS.ipad4.RELEASE.im4p  
Archive:  ../iPad_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBEC.ipad4.RELEASE.im4p  
Archive:  ../iPad_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBSS.ipad4b.RELEASE.im4p  
Archive:  ../iPad_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBEC.ipad4b.RELEASE.im4p  
[Log] Pwned iBSS and iBEC saved at: saved/iPad4,5
* The device needs to be in recovery/DFU mode before proceeding.
[Input] Send device to recovery mode? (Y/n): y
[Log] Entering recovery mode...
[Log] Finding device in Recovery mode...
[Log] Found device in Recovery mode.
* Get ready to enter DFU mode.
[Input] Select Y to continue, N to exit recovery mode (Y/n) y
* Hold TOP and HOME buttons for 10 seconds.
10 9 8 7 6 5 4 3 2 1 
* Release TOP button and hold HOME button for 8 seconds.
8 7 6 5 4 3 2 1 
[Log] Finding device in DFU mode...
[Error] Failed to find device in DFU mode (Timed out). Please run the script again.

ebayusers-MacBook-Pro:~ ebayuser$

**Comment by LukeZGD** [comment]
Only lightning to usb A cables will work. You can then use a usb A to usb C adapter to connect it to your Mac. Do not use lightning to usb C cables, they will not work
