### ISSUE TITLE
how to fix error?

### ISSUE THREAD

**Issue by hatvce** [LukeZGD/Legacy-iOS-Kit#323]
when i run the tool is shows an error the resources folder cannot be found. Replace resources folder and try again

**Comment by LukeZGD** [comment]
https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/How-to-Use

https://github.com/LukeZGD/Legacy-iOS-Kit/releases/tag/latest

**Comment by hatvce** [comment]
i can't install homebrew help me pls
