### ISSUE TITLE
mount_hfs invalid argument error on iPod Touch 5

### ISSUE THREAD

**Issue by bmwalters** [LukeZGD/Legacy-iOS-Kit#325]
Hello! I’m trying to access mnt2 on A5 iPod Touch 5. Here’s what I tried:

1. Enter pwned dfu with arduino
2. Use sliver to get into recovery (“Load M1 Ramdisk”); iBSS/iBEC send from this project was seemingly failing to get into recovery so I commented that part out.
3. Send ramdisk from this project.
4. Connect via ssh and run mount.sh

This mount mnt1 but gave mentioned error for mnt2. Any tips on troubleshooting? Thank you!

**Comment by LukeZGD** [comment]
I think it should be able to mount with this:
```
fsck_hfs /dev/disk0s1s1
mount_hfs /dev/disk0s1s1 /mnt1
fsck_hfs /dev/disk0s1s2
mount_hfs /dev/disk0s1s2 /mnt2
```

**Comment by bmwalters** [comment]
Thanks for the help (btw I pulled latest changes which fixed entering recovery via your script!)

Still getting an error on mount/fsck though :(

```sh
$ ~/p/iPhone5,1> ssh -oHostKeyAlgorithms=+ssh-rsa -p 2222 root@localhost
root@localhost's password:
Use mount.sh script to mount the partitions
Use reboot_bak to reboot
Use 'device_infos' to dump EMF keys (when imaging user volume)
-sh-4.0# ls /
System	bin  dev  etc  mktar.sh  mnt1  mnt2  private  sbin  usr  var
-sh-4.0# ls /mnt1
-sh-4.0# ls /mnt2
-sh-4.0# fsck_hfs /dev/disk0s1s1
** /dev/rdisk0s1s1
   Executing fsck_hfs (version diskdev_cmds-558.1~378).
** Checking Journaled HFS Plus volume.
fsck_hfs: Volume is journaled.  No checking performed.
fsck_hfs: Use the -f option to force checking.
-sh-4.0# mount_hfs /dev/disk0s1s1 /mnt1
-sh-4.0# fsck_hfs /dev/disk0s1s2
** /dev/rdisk0s1s2
   Executing fsck_hfs (version diskdev_cmds-558.1~378).
** Checking Journaled HFS Plus volume.
fsck_hfs: Volume is journaled.  No checking performed.
fsck_hfs: Use the -f option to force checking.
-sh-4.0# mount_hfs /dev/disk0s1s2 /mnt2
mount_hfs: Input/output error
-sh-4.0# umount /dev/disk0s1s1
-sh: umount: command not found
-sh-4.0# fsck_hfs -f /dev/disk0s1s2
** /dev/rdisk0s1s2
	Using cacheBlockSize=32K cacheTotalBlock=2014 cacheSize=64448K.
   Executing fsck_hfs (version diskdev_cmds-558.1~378).
** Checking Journaled HFS Plus volume.
   Invalid B-tree node size
(3, 0)
** The volume   could not be verified completely.
```

**Comment by LukeZGD** [comment]
hmm try doing `fsck_hfs -f /dev/disk0s1s1` and `fsck_hfs -f /dev/disk0s1s2`, then mount them. btw if your device is on ios 9 or newer, you will not be able to mount the data (var) partition, idk how

**Comment by bmwalters** [comment]
thanks so much! iirc i'm on 9.3.5. happy to send over any other info that would help.

**Comment by LukeZGD** [comment]
Fixed in v23.10.12 (e6f0916), the script will now prompt for build version. To mount /var for iOS 9/10, I recommend using "13A452" for the build version

**Comment by bmwalters** [comment]
It worked, thank you. Do you have PayPal or GitHub sponsor?

**Comment by LukeZGD** [comment]
I don't have either but thanks
