### ISSUE TITLE
Hello, iPad2 6.1.3 self-made firmware encountered this problem, how to solve it, thank you

### ISSUE THREAD

**Issue by BigKingJames** [LukeZGD/Legacy-iOS-Kit#326]
Hashing IPSW...
Matching IPSW in FirmwareBundles/... (241a02bb...)
checking: FirmwareBundles//Down_iPad2,1_6.1.3_10B329.bundle/Info.plist
loading: 048-2516-005.dmg (9955684)
loading: 048-2634-005.dmg (803633664)
loading: 048-2679-005.dmg (9951588)
loading: BuildManifest.plist (18888)
loading: Firmware/ (0)
loading: Firmware/all_flash/ (0)
loading: Firmware/all_flash/all_flash.k93ap.production/ (0)
loading: Firmware/all_flash/all_flash.k93ap.production/applelogo.s5l8940x.img3 (7524)
loading: Firmware/all_flash/all_flash.k93ap.production/batterycharging0.s5l8940x.img3 (5092)
loading: Firmware/all_flash/all_flash.k93ap.production/batterycharging1.s5l8940x.img3 (15972)
loading: Firmware/all_flash/all_flash.k93ap.production/batteryfull.s5l8940x.img3 (249636)
loading: Firmware/all_flash/all_flash.k93ap.production/batterylow0.s5l8940x.img3 (47524)
loading: Firmware/all_flash/all_flash.k93ap.production/batterylow1.s5l8940x.img3 (17700)
loading: Firmware/all_flash/all_flash.k93ap.production/DeviceTree.k93ap.img3 (76196)
loading: Firmware/all_flash/all_flash.k93ap.production/glyphcharging.s5l8940x.img3 (6180)
loading: Firmware/all_flash/all_flash.k93ap.production/glyphplugin.s5l8940x.img3 (5092)
loading: Firmware/all_flash/all_flash.k93ap.production/iBoot.k93ap.RELEASE.img3 (293348)
loading: Firmware/all_flash/all_flash.k93ap.production/LLB.k93ap.RELEASE.img3 (149988)
loading: Firmware/all_flash/all_flash.k93ap.production/manifest (320)
loading: Firmware/all_flash/all_flash.k93ap.production/recoverymode~ipad.s5l8940x.img3 (83876)
loading: Firmware/dfu/ (0)
loading: Firmware/dfu/iBEC.k93ap.RELEASE.dfu (289252)
loading: Firmware/dfu/iBSS.k93ap.RELEASE.dfu (76260)
loading: Firmware/usr/ (0)
loading: Firmware/usr/local/ (0)
loading: Firmware/usr/local/standalone/ (0)
loading: kernelcache.release.k93 (7744228)
loading: Restore.plist (2092)
[+] needPref ? 1...
iBSS: Firmware/dfu/iBSS.k93ap.RELEASE.dfu (FirmwareBundles//Down_iPad2,1_6.1.3_10B329.bundle/iBSS.k93ap.RELEASE.patch)... encrypted input... /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: f75ca651b0dee8b54077bb5977b625b44dfdd3b2b15c23965fc5d39f8ec0b7efbe95f04f664b7d4d7f9f873b86d0ffb0
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: f75ca651b0dee8b54077bb5977b625b44dfdd3b2b15c23965fc5d39f8ec0b7efbe95f04f664b7d4d7f9f873b86d0ffb0
encrypted output... /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: f75ca651b0dee8b54077bb5977b625b44dfdd3b2b15c23965fc5d39f8ec0b7efbe95f04f664b7d4d7f9f873b86d0ffb0
writing... success
iBSS: /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: f75ca651b0dee8b54077bb5977b625b44dfdd3b2b15c23965fc5d39f8ec0b7efbe95f04f664b7d4d7f9f873b86d0ffb0
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: f75ca651b0dee8b54077bb5977b625b44dfdd3b2b15c23965fc5d39f8ec0b7efbe95f04f664b7d4d7f9f873b86d0ffb0
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: f75ca651b0dee8b54077bb5977b625b44dfdd3b2b15c23965fc5d39f8ec0b7efbe95f04f664b7d4d7f9f873b86d0ffb0
writing... success
iBEC: Firmware/dfu/iBEC.k93ap.RELEASE.dfu (FirmwareBundles//Down_iPad2,1_6.1.3_10B329.bundle/iBEC.k93ap.RELEASE.patch)... encrypted input... /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 366167bc66fd913b56c9e1d16a20098da4e2999a1186095debe1b493d8fb4c34e56e41a8faf387ba99454da181323f67
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 366167bc66fd913b56c9e1d16a20098da4e2999a1186095debe1b493d8fb4c34e56e41a8faf387ba99454da181323f67
encrypted output... /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 366167bc66fd913b56c9e1d16a20098da4e2999a1186095debe1b493d8fb4c34e56e41a8faf387ba99454da181323f67
writing... success
iBEC: /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 366167bc66fd913b56c9e1d16a20098da4e2999a1186095debe1b493d8fb4c34e56e41a8faf387ba99454da181323f67
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 366167bc66fd913b56c9e1d16a20098da4e2999a1186095debe1b493d8fb4c34e56e41a8faf387ba99454da181323f67
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 366167bc66fd913b56c9e1d16a20098da4e2999a1186095debe1b493d8fb4c34e56e41a8faf387ba99454da181323f67
writing... success
RestoreDeviceTree: /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 3de4373b0ab2a4fa71f7ae0b17131521ae4a770f970ae9724ae67117d555b2f95e5a2e5472e136ae46043cf94c93edd4
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 3de4373b0ab2a4fa71f7ae0b17131521ae4a770f970ae9724ae67117d555b2f95e5a2e5472e136ae46043cf94c93edd4
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 3de4373b0ab2a4fa71f7ae0b17131521ae4a770f970ae9724ae67117d555b2f95e5a2e5472e136ae46043cf94c93edd4
writing... success
RestoreLogo: /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 332b5ad9084c1db5764609e7326c00b5739dcda8e794fa2edf2835c9ff6a0d8b9ed1bc0a555af087f3e42e92cc0fba6b
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 332b5ad9084c1db5764609e7326c00b5739dcda8e794fa2edf2835c9ff6a0d8b9ed1bc0a555af087f3e42e92cc0fba6b
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 332b5ad9084c1db5764609e7326c00b5739dcda8e794fa2edf2835c9ff6a0d8b9ed1bc0a555af087f3e42e92cc0fba6b
writing... success
RestoreKernelCache: /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 7f73c1400417bff880eb880905a4e0d54214d9e0e7fa9f01f0772255bd568e86688aa9adff6a6644edcf360f3933867d
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 7f73c1400417bff880eb880905a4e0d54214d9e0e7fa9f01f0772255bd568e86688aa9adff6a6644edcf360f3933867d
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 7f73c1400417bff880eb880905a4e0d54214d9e0e7fa9f01f0772255bd568e86688aa9adff6a6644edcf360f3933867d
writing... success
Restore Ramdisk: /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 5f1d5d16df9fe704ac4c7815a4008f9f7efa26b542590a03e6a24d49042c1441a96bdd0c8ad0cf5a0a6dd133ab192702
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 5f1d5d16df9fe704ac4c7815a4008f9f7efa26b542590a03e6a24d49042c1441a96bdd0c8ad0cf5a0a6dd133ab192702
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 5f1d5d16df9fe704ac4c7815a4008f9f7efa26b542590a03e6a24d49042c1441a96bdd0c8ad0cf5a0a6dd133ab192702
writing... success
/d/a/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/main.c:main:451: using filesystem backed temporary storage
Writing out data..
run 0: start=0 sectors=512, length=25219, fileOffset=0x191
run 100: start=26214400 sectors=512, length=262144, fileOffset=0xb0dbfe
run 200: start=52428800 sectors=512, length=262144, fileOffset=0x15d17b6
run 300: start=78643200 sectors=512, length=111309, fileOffset=0x2dceaa4
run 400: start=104857600 sectors=512, length=262144, fileOffset=0x3efac13
run 500: start=131072000 sectors=512, length=262144, fileOffset=0x556e127
run 600: start=157286400 sectors=512, length=48965, fileOffset=0x6dd1c65
run 700: start=183500800 sectors=512, length=262144, fileOffset=0x7fc7217
run 800: start=209715200 sectors=512, length=262144, fileOffset=0x97840a8
run 900: start=235929600 sectors=512, length=262144, fileOffset=0xb0536ba
run 1000: start=262144000 sectors=512, length=262144, fileOffset=0xc783527
run 1100: start=288358400 sectors=512, length=185160, fileOffset=0xdbb7a5d
run 1200: start=314572800 sectors=512, length=191473, fileOffset=0xed8fe5b
run 1300: start=340787200 sectors=512, length=262144, fileOffset=0x104ee95f
run 1400: start=367001600 sectors=512, length=169801, fileOffset=0x11764b89
run 1500: start=393216000 sectors=512, length=226357, fileOffset=0x12c8ca58
run 1600: start=419430400 sectors=512, length=262144, fileOffset=0x14454b9b
run 1700: start=445644800 sectors=512, length=28848, fileOffset=0x14d21ade
run 1800: start=471859200 sectors=512, length=262144, fileOffset=0x16352290
run 1900: start=498073600 sectors=512, length=58356, fileOffset=0x17991e2b
run 2000: start=524288000 sectors=512, length=262144, fileOffset=0x19010eda
run 2100: start=550502400 sectors=512, length=219930, fileOffset=0x1a62e18a
run 2200: start=576716800 sectors=512, length=225068, fileOffset=0x1bb84f5f
run 2300: start=602931200 sectors=512, length=262144, fileOffset=0x1d365849
run 2400: start=629145600 sectors=512, length=246568, fileOffset=0x1e829726
run 2500: start=655360000 sectors=512, length=180874, fileOffset=0x1f997304
run 2600: start=681574400 sectors=512, length=180155, fileOffset=0x20f2dfc1
run 2700: start=707788800 sectors=512, length=172614, fileOffset=0x2208acc1
run 2800: start=734003200 sectors=512, length=262144, fileOffset=0x22bc9aec
run 2900: start=760217600 sectors=512, length=262144, fileOffset=0x2423146c
run 3000: start=786432000 sectors=512, length=217727, fileOffset=0x259ffea1
run 3100: start=812646400 sectors=512, length=237784, fileOffset=0x267d18c2
run 3200: start=838860800 sectors=512, length=262144, fileOffset=0x27f346ef
run 3300: start=865075200 sectors=512, length=250253, fileOffset=0x28f6cbb6
run 3400: start=891289600 sectors=512, length=137772, fileOffset=0x29ef9a87
run 3500: start=917504000 sectors=512, length=131985, fileOffset=0x2ad0ecae
run 3600: start=943718400 sectors=512, length=229026, fileOffset=0x2bb2de7b
run 3700: start=969932800 sectors=512, length=170569, fileOffset=0x2c92b727
run 3800: start=996147200 sectors=512, length=149370, fileOffset=0x2d5ce577
run 3900: start=1022361600 sectors=512, length=173414, fileOffset=0x2e1f8c07
run 4000: start=1048576000 sectors=512, length=105851, fileOffset=0x2ebfe16f
run 4100: start=1074790400 sectors=512, length=61793, fileOffset=0x2f43d9f5
run 4200: start=1101004800 sectors=512, length=68262, fileOffset=0x2faa538e
Growing root to minimum: 1063
Cannot shrink volume
[*] Executing needPref...
error: /d/a/daibutsuCFW/daibutsuCFW/src/xpwn/hfs/rawfile.c:233: allocate
error: No error
unzip:  cannot find or open custom.ipsw, custom.ipsw.zip or custom.ipsw.ZIP.
usage: ./xpwntool <infile> <outfile> [-x24k|-xn8824k] [-t <template> [-c <certificate>]] [-k <key>] [-iv <key>] [-decrypt]
unzip:  cannot find or open custom.ipsw, custom.ipsw.zip or custom.ipsw.ZIP.
mv: missing destination file operand after 'pwnediBEC'
Try 'mv --help' for more information.

**Comment by LukeZGD** [comment]
Based on the log snippet, this seems to be on Windows, and Windows version is not supported
