### ISSUE TITLE
Broken iPad 4 jailbreak at iOS 9.3.x

### ISSUE THREAD

**Issue by kreb0sh** [LukeZGD/Legacy-iOS-Kit#332]
Hello!

I've jailbreak an iPad 4 (GSM, iPad3,5) doing a custom ipsw (9.3, build 13E237) with jailbreak enabled and tether booting it. all done with Legacy iOS Kit. 

It works flawlessly, the iOS works good, and Cydia appears up and can be launched. The problem comes when i install anything from Cydia: after installing/updating anything, the iPad goes straight to a black screen, then goes to the lock screen, when i unlock it, all the apps are gone, all icons, everything is gone, just a lot of blank space at home screen. Not even a app there, i can't open anything from control center too. 

I've tried to reboot into safe/no substrate mode, does not seems to work at all.

What can i do? I can't sideload any IPAs, that's why i am trying to jailbreak with a custom ipsw (even if it's tethered).

Thanks in advance!

**Comment by LukeZGD** [comment]
v23.10.05 should fix this, where I disabled stashing for 9.x UntetherHomeDepot. Update Legacy iOS Kit and delete the existing custom IPSW

**Comment by kreb0sh** [comment]
Hey again! It worked now, no more buggy homescreen!

Now there's another bug (it was previously present too, i forgot to mention it, i am very sorry...): 

Trying to update/install anything with Cydia will always fail with error: Subprocess /usr/libexec/cydia/cydo returned an error code (2).

Looking through this error it seems to be a permission problem, i could fix it by chmod -s with SSH, and far i know, OpenSSH should be added by default to custom iPSW if ipsw_openssh=1 in the script, but it does not seem to work.

As there's no OpenSSH in the Cydia package list (and trying to SSH the iPad, i always got connection refused) i can't chmod +s cydo process to fix the error 2.

So there's two bugs (?)

1. OpenSSH not installing/working by default (ipsw_openssh=1 has no effect)

2. Subprocess /usr/libexec/cydia/cydo returned an error code (2).

That's all!

Arigathanks! <3

**Comment by LukeZGD** [comment]
1 is a known issue with etasonjb and untetherhomedepot where it doesnt install debs in the autoinstall folder, idk a fix for it unfortunately. ssh only works after installing openssh from cydia.

2 is fixed in v23.10.06, i just added `/bin/launchctl` in the tars for untetherhomedepot
