### ISSUE TITLE
iPhone 5c 8.3 Jailbreak Restore Segfault, Jailbreak fails

### ISSUE THREAD

**Issue by CatsLover2006** [LukeZGD/Legacy-iOS-Kit#333]
I'm on macOS 13.5.1, running on a 2012 15" Unibody MacBook Pro with 16GB RAM (before you say this is why, it worked on a 8.1.3 iPhone 5 literally a week ago). Memory option does nothing, due to it being a segfault. 
[WhyDoesThisHappenToMe.txt](https://github.com/LukeZGD/Legacy-iOS-Kit/files/12798521/WhyDoesThisHappenToMe.txt)
Here's a log. Same 5c also fails to jailbreak properly with the script, with it getting stuck on an empty loading bar (then it's forced to recovery mode, although I just kick it out). With TaiG dead, I'm left unable to jailbreak my 5c. Any idea why this is happening?
Also, blobs are valid, I restored with them ~3 hours before I encountered this issue (got the thing in an untested lot, and it had a passcode despite not being iC locked; most of the devices in that lot that are FMI-clean are on 10.3.3 already, so I'm just going to sell those later)

**Comment by LukeZGD** [comment]
idk why that happens on your ipsw unfortunately.. maybe try re-downloading the ipsw? 

also do you have a log of the jailbreak process in the "jailbreak device" option? to try this out, restore to 8.3 with the jailbreak option disabled, then select the "jailbreak device" option after restoring

**Comment by CatsLover2006** [comment]
[JailbreakOOF.txt](https://github.com/LukeZGD/Legacy-iOS-Kit/files/12799118/JailbreakOOF.txt)
Here's a log of the jailbreak attempt. I think this might have to do with the one line `scp: failed to upload file ../resources/jailbreak/daibutsu/move.sh to /`

**Comment by LukeZGD** [comment]
yeah i see the issue now, ill be pushing a fix in a bit

**Comment by LukeZGD** [comment]
fixed on v23.10.08 (80dd9f5)

**Comment by CatsLover2006** [comment]
thx
