### ISSUE TITLE
Failed to find device in Recovery mode (Timed out).

### ISSUE THREAD

**Issue by RiberWang** [LukeZGD/Legacy-iOS-Kit#341]
last step error
`[Input] Is your device already in pwned iBSS/kDFU mode? (y/N): y
[Log] Pwned iBSS/kDFU mode specified by user.
[Log] Sending iBSS...
[Log] Sending iBEC...
[=================================                 ] 65.1%[Log] Finding device in Recovery mode...
[Error] Failed to find device in Recovery mode (Timed out). Please run the script again.
`

I try some method, but it's not work!

**Comment by LukeZGD** [comment]
I need more context, what are you trying to do and do you have a full log?

**Comment by RiberWang** [comment]
This is all logs
` *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v23.10.28 (4475a84)
* Platform: macos (12.6.5) 

* Device: iPhone4,1 (n94ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 4046666341775

 > Main Menu
[Input] Select an option:
1) Restore/Downgrade  3) Save SHSH Blobs    5) Exit
2) Jailbreak Device   4) Other Utilities
#? 1








 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v23.10.28 (4475a84)
* Platform: macos (12.6.5) 

* Device: iPhone4,1 (n94ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 4046666341775

 > Main Menu > Restore/Downgrade
[Input] Select an option:
1) iOS 8.4.1			 5) Other (Use SHSH Blobs)
2) iOS 6.1.3			 6) DFU IPSW
3) Latest iOS (9.3.6)		 7) Go Back
4) Other (powdersn0w 7.x blobs)
#? 2
[Log] Verifying ../iPhone4,1_6.1.3_10B329_Restore.ipsw...
[Log] IPSW SHA1sum matches




 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v23.10.28 (4475a84)
* Platform: macos (12.6.5) 

* Device: iPhone4,1 (n94ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 4046666341775

* Selected IPSW: ../iPhone4,1_6.1.3_10B329_Restore.ipsw

 > Main Menu > Restore/Downgrade > iOS 6.1.3
[Input] Select an option:
1) Select Target IPSW	 3) Start Restore
2) Download Target IPSW	 4) Go Back
#? 3
[Input] Jailbreak Option
* When this option is enabled, your device will be jailbroken on restore.
* I recommend to enable this option to have the jailbreak and Cydia pre-installed.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): y
[Log] Jailbreak option enabled.

[Input] Memory Option for creating custom IPSW
* When this option is enabled, system RAM will be used for the IPSW creation process.
* I recommend to enable this option to speed up creating the custom IPSW.
* However, if you have less than 8 GB of RAM, disable this option.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): y
[Log] Memory option enabled.

[Log] Found existing Custom IPSW. Skipping IPSW creation.
[Log] Found existing saved 6.1.3 blobs: ../saved/shsh/4046666341775_iPhone4,1_n94ap_6.1.3-10B329_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2
* Select Y if your device is in pwned iBSS/kDFU mode.
* Select N if this is not the case.
[Input] Is your device already in pwned iBSS/kDFU mode? (y/N): y
[Log] Pwned iBSS/kDFU mode specified by user.
[Log] Manifest: ../saved/iPhone4,1/13G37.plist
[Log] Baseband: ../saved/baseband/Trek-6.7.00.Release.bbfw
[Log] Extracting IPSW: ../iPhone4,1_6.1.3_10B329_CustomJ.ipsw
Archive:  ../iPhone4,1_6.1.3_10B329_CustomJ.ipsw
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/048-2516-005.dmg  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/048-2613-005.dmg  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/048-2679-005.dmg  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/BuildManifest.plist  
   creating: ../iPhone4,1_6.1.3_10B329_CustomJ/Downgrade/
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Downgrade/RestoreDeviceTree  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Downgrade/RestoreKernelCache  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Downgrade/RestoreLogo  
   creating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/Trek-3.4.03.Release.bbfw  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/Trek-3.4.03.Release.plist  
   creating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/
   creating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/DeviceTree.n94ap.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/LLB.n94ap.RELEASE.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/applelogo@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batterycharging0@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batterycharging1@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batteryfull@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batterylow0@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batterylow1@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/glyphcharging@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/glyphplugin@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/iBoot.n94ap.RELEASE.img3  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/manifest  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/all_flash/all_flash.n94ap.production/recoverymode@2x~iphone.s5l8940x.img3  
   creating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/dfu/
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/dfu/iBEC.n94ap.RELEASE.dfu  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/dfu/iBSS.n94ap.RELEASE.dfu  
   creating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/usr/
   creating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/usr/local/
   creating: ../iPhone4,1_6.1.3_10B329_CustomJ/Firmware/usr/local/standalone/
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/Restore.plist  
  inflating: ../iPhone4,1_6.1.3_10B329_CustomJ/kernelcache.release.n94  
[Log] Running idevicererestore with command: ../bin/macos/idevicererestore -r "../iPhone4,1_6.1.3_10B329_CustomJ.ipsw"
NOTE: Updated version data.
Found device in DFU mode
Identified device as n94ap, iPhone4,1
Extracting BuildManifest from IPSW
Product Version: 6.1.3
Product Build: 10B329 Major: 10
Found ECID 4046666341775
Getting ApNonce in dfu mode... 
checking for local shsh
Using local SHSH
Extracting 048-2516-005.dmg...
Extracting 048-2679-005.dmg...
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from '../iPhone4,1_6.1.3_10B329_CustomJ/048-2613-005.dmg'
Extracting iBSS.n94ap.RELEASE.dfu...
Sending iBSS (76056 bytes)...
[==================================================] 100.0%
Nonce: 
checking for local shsh
Using local SHSH
Extracting iBEC.n94ap.RELEASE.dfu...
Sending iBEC (276760 bytes)...
[=================================                 ]  65.1%ERROR: Unable to send iBEC component: Unable to upload data to device
ERROR: Unable to send iBEC to device
ERROR: Unable to place device into recovery mode from DFU mode

[Log] Restoring done! Read the message below if any error has occurred:
* If you are getting the error "could not retrieve device serial number":
 -> This means that your device is not compatible with 6.1.3
* If the restore failed on updating baseband:
 -> Try disabling baseband update: ./restore.sh --disable-bbupdate

* Please read the "Troubleshooting" wiki page in GitHub before opening any issue!
* Your problem may have already been addressed within the wiki page.
* If opening an issue in GitHub, please provide a FULL log/output. Otherwise, your issue may be dismissed.

* Save the terminal output now if needed.
* Legacy iOS Kit v23.10.28 (4475a84)
`

**Comment by LukeZGD** [comment]
ok I see, did you make sure that the 4S is in **kDFU mode**?

**Comment by RiberWang** [comment]
> ok I see, did you make sure that the 4S is in **kDFU mode** before running Legacy iOS Kit?

> ok I see, did you make sure that the 4S is in **kDFU mode** before running Legacy iOS Kit?

Yes, it is my mistake.
My net is poor.I see it in Troubleshooting, you can close this issue.
`Run checkm8-a5, do not send pwned iBSS, select N for "Pwned iBSS/kDFU mode", select Y for "pwned DFU", for ipwndfu to send pwned iBSS. `
