### ISSUE TITLE
Set up github sponsoring so me and others can sponsor your work

### ISSUE THREAD

**Issue by wilma242008** [LukeZGD/Legacy-iOS-Kit#342]
I feel like [Legacy-iOS-Kit](https://github.com/LukeZGD/Legacy-iOS-Kit/) is a fundamental program in the iOS jailbreaking community, and thus we should be able to [sponsor](https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-personal-account) your work on github to be able to say thanks to you. Just a thought. I really appreciate all the work you have done.

**Comment by LukeZGD** [comment]
Thanks, I'll consider it

**Comment by LukeZGD** [comment]
Will be closing this as it is more suited in Discussions, havent opened one yet but I'll be looking into it in the future
