### ISSUE TITLE
iPhone 3,3 CDMA Downgrade Not Working - Attempted Clearing NVRAM

### ISSUE THREAD

**Issue by WizardNight7718** [LukeZGD/Legacy-iOS-Kit#343]
I've tried to downgrade my iPhone 4 3,3 CDMA to iOS 6.1.3, but each time it restores it gets stuck on the iOS 7 boot logo, and I've read the guide tried clearing the NVRAM, no effect on downgrade.

**Comment by LukeZGD** [comment]
Need more details, what platform, what target iOS, and do you have the terminal output?

**Comment by WizardNight7718** [comment]
Platform: MacOS 10.15.7 Catalina
Target iOS: 6.1.3 10B329
Base iOS: 7.1.2 11D257

Terminal Output
[Terminal Saved Output.zip](https://github.com/LukeZGD/Legacy-iOS-Kit/files/13211800/Terminal.Saved.Output.zip)

**Comment by LukeZGD** [comment]
Okay that log is really long and now I'm not sure on what you're trying to do.. Are you trying to downgrade back to 6.1.3, or are you trying to restore back to 7.1.2?

**Comment by LukeZGD** [comment]
So for downgrading back to 6.1.3:
- First run: Go to Other Utilities -> Clear NVRAM
- Second run: Go to Restore/Downgrade -> powdersn0w, select 6.1.3 target and 7.1.2 base, start

For going back to 7.1.2:
- First run: Go to Other Utilities -> Clear NVRAM
- Second run: Go to Restore/Downgrade -> Latest 7.1.2, download/select IPSW, start

Hope this helps and works out for you. If it doesn't, well.. idk. The steps for restoring to latest should at least work and these have been tested (not by me though, i dont have a cdma 4)
