### ISSUE TITLE
More support Part 2 

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#352]
Here is what I want to see come to Legacy ios Kit

Fix iPhone3,3 iOS 4.2.x Boot Issues

Fix iPad 1 iOS 3.2.x and iOS 4.2.1 Boot Issues

Fix iPhone3,1 iOS 4.2.1 Boot Issues

Fix iPod Touch 3G iOS 3.1.x Boot Issues

Add Downgrade Support for All iOS Versions for iPhone 2G/3G/3GS and iPod Touch 1G/2G as well as Custom IPSW Support

**Comment by Jefferyat** [comment]
Also Add Support for macOS 10.6 Snow Leopard to macOS 10.12 Sierra

**Comment by LukeZGD** [comment]
fixing boot issues on the powdersn0w devices are not happening anytime soon, sorry

for the older devices downgrade support, i plan on adding this but lowest will be 3.0 only. 2g/3g/touch 1 support is uncertain bc i dont have those. custom ipsw support is re-enabled for older devices in v23.11.17 (92186f6) though so theres that

extending macos version support might happen, lowest will be 10.11 el capitan only.
