### ISSUE TITLE
Is there a solution?

### ISSUE THREAD

**Issue by Vadim7565** [LukeZGD/Legacy-iOS-Kit#365]
I did everything as you said, but the same problem, will you fix it in the future or is it impossible?

https://github.com/LukeZGD/Legacy-iOS-Kit/issues/362

**Comment by LukeZGD** [comment]
I don't really have any suggestion, solution, or anything to fix, it works fine for me and others, and idk what's causing the issue on your end

The only other thing that I can suggest is to try different USB cables/ports and maybe different PC/Mac
