### ISSUE TITLE
non work downgrade iPad 2,2

### ISSUE THREAD

**Issue by Unagaml** [LukeZGD/Legacy-iOS-Kit#369]
<img width="1404" alt="Снимок экрана 2023-12-16 в 02 51 53" src="https://github.com/LukeZGD/Legacy-iOS-Kit/assets/92244180/385535cc-43e5-4f05-af2a-2b83550e2c16">
I was able to downgrade the tablet 1 month ago on macos sonoma. One of the updates broke this opportunity. can you fix it

**Comment by LukeZGD** [comment]
Need more details on this, what device, target version, and do you have a full terminal output

**Comment by LukeZGD** [comment]
No info given, closing

**Comment by Unagaml** [comment]
Mac OS Sonoma 14.2 MacBook Pro 14 2021 and iPad 2,2 iOS 9.3.5. iPad has been jaibroked.

**Comment by Spritzerland** [comment]
i am having this issue aswell, here is the log output https://pastebin.com/raw/USRMWh17
my ipad has been jailbroken with phoenix
