### ISSUE TITLE
iPhone4,1 downgrade (iOS 6.1.3/powdersn0w) is not working

### ISSUE THREAD

**Issue by iphone4suser** [LukeZGD/Legacy-iOS-Kit#370]
I have iPhone4,1 A1387 (CPID:8940 CPRV:21 CPFM:03 SCEP:01 BDID:08 IBFL:00 SRTG:[iBoot-838.3] PWND:[checkm8]) with iOS 7.1.2 and I tried to downgrade it to iOS 5.1.1 using "4) Other (powdersn0w 7.x blobs)" feature. I have used Arduino + USB Host Shield to put the device in to PWNED DFU mode. When I try to downgrade, an error is displayed that it is not possible to upload iBSS.

` *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v23.12.02 (63dcadc)
* Platform: macos (10.15.7) 

* Device: iPhone4,1 (n94ap) in DFU mode
[WARNING] Disable bbupdate flag detected, baseband update is disabled. Proceed with caution
* For iPhones, current baseband will be dumped and stitched to custom IPSW
* Stitching is supported in these restores/downgrades: 8.4.1/6.1.3, Other with SHSH, powdersn0w
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 3034529422634

* Selected Target IPSW: ../iPhone4,1_5.1.1_9B206_Restore.ipsw
* Target Version: 5.1.1-9B206

* Selected Base (iOS 7.1.x) IPSW: ../iPhone4,1_7.1.2_11D257_Restore.ipsw
* Base Version: 7.1.2-11D257

* Selected Base (iOS 7.1.x) SHSH: ../3034529422634-iPhone4,1-7.1.2.shsh
* Selected SHSH file is validated

 > Main Menu > Restore/Downgrade > Other (powdersn0w 7.x blobs)
[Input] Select an option:
1) Select Target IPSW
2) Select Base IPSW
3) Select Base SHSH
4) Start Restore
5) Go Back
#? 4
[Input] Jailbreak Option
* When this option is enabled, your device will be jailbroken on restore.
* I recommend to enable this option to have the jailbreak and Cydia pre-installed.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): 
[Log] Jailbreak option enabled.

[Input] Memory Option for creating custom IPSW
* When this option is enabled, system RAM will be used for the IPSW creation process.
* I recommend to enable this option to speed up creating the custom IPSW.
* However, if you have less than 8 GB of RAM, disable this option.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): 
[Log] Memory option enabled.

[Input] Verbose Boot Option
* When this option is enabled, the device will have verbose boot on restore.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): n
[Log] Verbose boot option disabled by user.

[Log] Found existing Custom IPSW. Skipping IPSW creation.
* Select Y if your device is in pwned iBSS/kDFU mode.
* Select N if this is not the case.
[Input] Is your device already in pwned iBSS/kDFU mode? (y/N): n
* DFU mode for A5 device - Make sure that your device is in PWNED DFU mode.
* You need to have an Arduino and USB Host Shield to proceed for PWNED DFU mode.
* If you do not know what you are doing, select N and restart your device in normal mode.
[Input] Is your device in PWNED DFU mode using synackuk checkm8-a5? (y/N): y
[Log] python2 from pyenv detected
[Log] Downloading iBSS...
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios8.4.1/031-31129-20150812-751A3CB8-3C8F-11E5-A8A5-A91A3A53DB92/iPhone4,1_8.4.1_12H321_Restore.ipsw
init done
getting: Firmware/dfu/iBSS.n94.RELEASE.dfu
100% [===================================================================================================>]
download succeeded
[Log] Checking firmware keys in ../resources/firmware/iPhone4,1/12H321
[Log] Decrypting iBSS...
/tmp/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ca0b54a96b22a813f562eb257cb02afb9518b73701007b43c5e8712146a3eb75482800d2ac9cecc643aac17f9132ff2f
[Log] Patching iBSS...
main: Starting...
main: iBoot-2261 inputted.
patch_rsa_check: Entering...
find_bl_verify_shsh_generic: Entering...
find_bl_verify_shsh_generic: Found LDR instruction at 0x60ac
find_bl_verify_shsh_generic: Found BL verify_shsh at 0x6452
find_bl_verify_shsh_generic: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x6452...
patch_rsa_check: Leaving...
main: Writing out patched file to pwnediBSS...
main: Quitting...
/tmp/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ca0b54a96b22a813f562eb257cb02afb9518b73701007b43c5e8712146a3eb75482800d2ac9cecc643aac17f9132ff2f
/tmp/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ca0b54a96b22a813f562eb257cb02afb9518b73701007b43c5e8712146a3eb75482800d2ac9cecc643aac17f9132ff2f
[Log] Pwned iBSS saved at: saved/iPhone4,1/pwnediBSS
[Log] Pwned iBSS img3 saved at: saved/iPhone4,1/pwnediBSS.dfu
[Log] Sending iBSS using ipwndfu...
* ipwndfu should have "done!" as output.
[Log] Device iPhone4,1 has no baseband/disabled baseband update
[Log] Extracting IPSW: ../iPhone4,1_5.1.1_9B206_CustomBJP.ipsw
Archive:  ../iPhone4,1_5.1.1_9B206_CustomBJP.ipsw
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/038-4343-021.dmg  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/038-4352-023.dmg  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/038-4356-009.dmg  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/BuildManifest.plist  
   creating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Downgrade/
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Downgrade/RestoreDeviceTree  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Downgrade/RestoreKernelCache  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Downgrade/RestoreLogo  
   creating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/Trek-2.0.12.Release.bbfw  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/Trek-2.0.12.Release.plist  
   creating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/
   creating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/DeviceTree.n94ap.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/LLB.n94ap.RELEASE.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/applelogo7@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/applelogo@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/batterycharging0@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/batterycharging1@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/batteryfull@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/batterylow0@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/batterylow1@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/glyphcharging@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/glyphplugin@2x.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/iBoot.n94ap.RELEASE.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/iBoot5.n94ap.RELEASE.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/manifest  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/recoverymode7@2x~iphone.s5l8940x.img3  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/all_flash/all_flash.n94ap.production/recoverymode@2x~iphone.s5l8940x.img3  
   creating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/dfu/
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/dfu/iBEC.n94ap.RELEASE.dfu  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/dfu/iBSS.n94ap.RELEASE.dfu  
   creating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/usr/
   creating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/usr/local/
   creating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/usr/local/standalone/
   creating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Firmware/usr/standalone/
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/Restore.plist  
  inflating: ../iPhone4,1_5.1.1_9B206_CustomBJP/kernelcache.release.n94  
[Log] Running idevicerestore with command: ../bin/macos/idevicerestore -ew "../iPhone4,1_5.1.1_9B206_CustomBJP.ipsw"
Found device in DFU mode
Identified device as n94ap, iPhone4,1
Extracting BuildManifest from IPSW
Product Version: 5.1.1
Product Build: 9B206 Major: 9
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Found ECID 3034529422634
Getting ApNonce in dfu mode... 
checking for local shsh
Using cached SHSH
Using cached filesystem from '../iPhone4,1_5.1.1_9B206_CustomBJP/038-4356-009.dmg'
Extracting iBSS.n94ap.RELEASE.dfu...
Not personalizing component iBSS...
Sending iBSS (72016 bytes)...
ERROR: Unable to send iBSS component: Unable to upload data to device
ERROR: Unable to send iBSS to device
ERROR: Unable to place device into recovery mode from DFU mode

[Log] Restoring done! Read the message below if any error has occurred:
* If the restore failed on updating baseband:
 -> Try disabling baseband update: ./restore.sh --disable-bbupdate

* Please read the "Troubleshooting" wiki page in GitHub before opening any issue!
* Your problem may have already been addressed within the wiki page.
* If opening an issue in GitHub, please provide a FULL log/output. Otherwise, your issue may be dismissed.

* Save the terminal output now if needed.
* Legacy iOS Kit v23.12.02 (63dcadc)`

It appears, that there might be an issue with ipwndfu, but when I manually upload the iBSS there is also no output, so I cannot tell whenever this a desired behavior or not. The same issue is also present, when I tried to downgrade the device to iOS 6.1.3. I have tried every possible solution from "Troubleshooting" wiki, but they are not working in my case.

**Comment by LukeZGD** [comment]
There's something wrong with python2 on your system, idk on how to fix that kind of external issue. ipwndfu should output something
