### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#373]
I Updated Legacy iOS Kit to the new update and i saw that support for these 

iPhone 4 (3,1) iOS 4.2.1 support was removed

iPhone 3,3 iOS 4.2.x support was removed

iPod Touch 3G iOS 3.1.x Support was removed

iPad 1 iOS 3.2.x Support was removed as well from powdersn0w 

any idea why??

**Comment by Jefferyat** [comment]
and can they make a comeback

**Comment by LukeZGD** [comment]
its functionality isn't really removed, it's just that they never really worked in the first place, so i just removed their mentions from the readme

**Comment by userse31** [comment]
Good move.
