### ISSUE TITLE
iOS 4.3.x Jailbreak on iPad 2 

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#376]
Will the iOS 4.3.x iPad 2 Jailbreak implemented into Legacy iOS Kit be untethered eventually???

**Comment by Jefferyat** [comment]
also for the iOS 4.3.x iPad 2 Tethered Jailbreak, which iOS Version SHSH is required??

**Comment by LukeZGD** [comment]
> Will the iOS 4.3.x iPad 2 Jailbreak implemented into Legacy iOS Kit be untethered eventually???

Eventually yes, if it somehow manages to work (it currently just doesn't work)

> also for the iOS 4.3.x iPad 2 Tethered Jailbreak, which iOS Version SHSH is required??

Tethered: no blobs. Semi-tethered: whatever is the iOS 4.3.x blob available for your device
