### ISSUE TITLE
More Fixes

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#381]
The Tool would be better if these would be fixed 

Boot Issues after powdersn0w restores -- and restore issues with tethered downgrades 

iPhone3,3 4.2.x (the asr issue on Tethered, Boot Issues after restore on powdersn0w)
iPad 1 3.2.x (can't boot to restore mode on Tethered, Boot Issues after restore on powdersn0w )
iPod touch 3 3.1.x (iBSS issue when restoring on Tethered, Boot Issues after restore on powdersn0w)
iPhone3,1 iOS 4.2.1 (Boot Issue on powdersn0w, Tethered works fine)

**Comment by LukeZGD** [comment]
Sorry, as I already mentioned before, I can't fix the powdersn0w boot issues, and for the problems with tethered restores, just use pre-existing custom IPSWs for those versions with issues (iOS 5 and newer should work fine with the "Other (Tethered)" option)
