### ISSUE TITLE
Downgrading an iPhone 3G to 2.2.1 requires a double-restore (possibly) due to NOR

### ISSUE THREAD

**Issue by garoffoli** [LukeZGD/Legacy-iOS-Kit#383]
Downgrading an iPhone 3g to 2.2.1 requires a double-restore, due to the first restore failing due to not being to able to flash NOR

I've added a file with the full output of the second restore (I sadly didn't save the first restore output). I have censored sensitive data.
[secondrestore.txt](https://github.com/LukeZGD/Legacy-iOS-Kit/files/13907514/secondrestore.txt)

**Comment by LukeZGD** [comment]
Thanks for letting me know, added a note/message for this in v24.01.22
