### ISSUE TITLE
Legacy-iOS-Kit won't recognize a fresh install of iOS 2.x due to lockdownd error

### ISSUE THREAD

**Issue by garoffoli** [LukeZGD/Legacy-iOS-Kit#384]
After doing fresh downgrade to iOS 2.2.1 (as described in #383), Legacy-iOS-Kit doesn't recognize the 3G and thus can't attempt activation.

Log:

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.01.21 (150801c)
[Log] Running on platform: macos (10.13.6)
[Log] Detected libimobiledevice and libirecovery from Homebrew/MacPorts
[Log] Checking Internet connection...
[Log] Checking for updates...
[Log] Finding device in Normal mode...
[Log] Getting device info...
ERROR: Could not connect to lockdownd: SSL error (-5)
* Device:  (ap) in Normal mode
* iOS Version:
* ECID:

[Error] This device is not supported by Legacy iOS Kit.

* Legacy iOS Kit v24.01.21 (150801c)

**Comment by LukeZGD** [comment]
Disabled usage of libimobiledevice and libirecovery from Homebrew/Macports in v24.01.22, they can no longer be used since I have to use tihmstar's forks for iOS 1 and 2 compatibility
