### ISSUE TITLE
idevicerestore2 not exisiting in macOS bin folder

### ISSUE THREAD

**Issue by rastiqdev** [LukeZGD/Legacy-iOS-Kit#388]
Hi,
I've been trying to do a restore on my iPhone 6S to iOS 15.8 but I got an error after the IPSW got extracted.
It was looking for an `idevicerestore2` file in the macOS bin folder, but it doesn't seem to exist, it only does in the **Linux** bin folder.
Would you please be able to fix that?
Thank you in advance.

(I sadly can't use the commit before you switched to idevicerestore2, as Legacy-iOS-Kit forces me to pull the latest commit.)

**Comment by LukeZGD** [comment]
Added `idevicerestore2` for macOS on v24.01.24. I haven't tested it though, hopefully it works fine
