### ISSUE TITLE
Phone 4 boots to white screen after downgrading to 4.0

### ISSUE THREAD

**Issue by ios456** [LukeZGD/Legacy-iOS-Kit#389]
I have a iPhone 3,1 and want to downgrade to iOS 4.0 with Powdersn0w via LegacyIOSKit it succesfully. completes then boots to a white screen I have Cleared NVRAM Multiple times and restored to 7 and tried again 4 times to no avail

**Comment by LukeZGD** [comment]
for now try restoring it to 4.1 to see if it successfully boots there

**Comment by ios456** [comment]
It Worked Now Thanks A Lot
