### ISSUE TITLE
White Screen on iPhone 4 downgrading to iOS 4

### ISSUE THREAD

**Issue by Raphi69420** [LukeZGD/Legacy-iOS-Kit#390]
I have a problem. I want to downgrade to iOS 4 but every Time I restore it using Legacy iOS Kit after the restore on the iPhone there is a white screen and on my Mac it recognise it in recovery mode. I can't restore it back to iOS 7.1.2. My iPhone 4 is an 16GB model, Model iPhone 3,1. Can someone please help me? (I am german btw) 
<img width="1440" alt="Bildschirmfoto 2024-01-14 um 11 57 24" src="https://github.com/LukeZGD/Legacy-iOS-Kit/assets/156579464/9e3e8ff3-9ef3-40f4-b87d-ddc0eecf8e8a">
<img width="1440" alt="Bildschirmfoto 2024-01-14 um 11 53 58" src="https://github.com/LukeZGD/Legacy-iOS-Kit/assets/156579464/83c07c7d-be41-4ce4-bccf-952462c308bb">
<img width="1440" alt="Bildschirmfoto 2024-01-14 um 11 54 08" src="https://github.com/LukeZGD/Legacy-iOS-Kit/assets/156579464/0a054619-7bf0-4327-b765-27bde1cb8706">
<img width="1440" alt="Bildschirmfoto 2024-01-14 um 11 54 12" src="https://github.com/LukeZGD/Legacy-iOS-Kit/assets/156579464/1c50d766-c94c-460d-a4e8-df707767c8bd">
<img width="1440" alt="Bildschirmfoto 2024-01-14 um 11 54 14" src="https://github.com/LukeZGD/Legacy-iOS-Kit/assets/156579464/6e5719b2-de85-46c6-acad-8336a7832fd8">

**Comment by LukeZGD** [comment]
Very similar to #389, see my comments there.

Also for restoring to 7.1.2, go to Other Utilities -> Clear NVRAM. That will resolve the recovery mode issue

**Comment by Raphi69420** [comment]
Ok thanks I try it and let you know if it works

**Comment by Raphi69420** [comment]
It worked. Thanks a lot. It's back on iOS 7
