### ISSUE TITLE
How to Use - Usage doesn't have any info about Usage of some 64bit devices

### ISSUE THREAD

**Issue by Veshurik** [LukeZGD/Legacy-iOS-Kit#394]
https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/How-to-Use

Hello!
I have a problem understanding how to downgrade my iPod touch 6 from iOS 12.5.5 to some older iOS. 
There is no variant in section "How to Use" about 64bit devices at all, but I found that it's compatible [here](https://github.com/LukeZGD/Legacy-iOS-Kit/blob/main/README.md#Legacy-iOS-Kit).

Can you help, please? Thanks.

**Comment by LukeZGD** [comment]
It is compatible, hoewever you would need to have valid SHSH blobs to downgrade to the iOS version, as well as the fact that it muat be compatible with the latest 12.5.7 SEP/baseband: Go to Restore/Downgrade -> Other (Use SHSH Blobs) Select your IPSW and SHSH file. Before starting the restore, make sure that the generator is set, there is a link provided for instructions. Once that is done, start the restore. The device will be put ro recovery mode and futurerestore will start
