### ISSUE TITLE
Tethered boot IOS 7 iphone 4s failed.

### ISSUE THREAD

**Issue by ZeroCodespy** [LukeZGD/Legacy-iOS-Kit#398]
So i restored my iphone 4s from ios 9.3.6 to ios 7.1.2 and its stuck on the recovery mode
when i am trying the option just boot it asks me if i am in checkmate-A5 DFU of course i am not cause am in recovery

i havent found any way to "just boot" on the phone and i would like a bit of help-

**Comment by LukeZGD** [comment]
You need an Arduino and USB Host Shield, and use synackuk checkm8-a5. This is required in order to tether boot your device. https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting#dfu-advanced-menu-a5x-pwndfu-mode-with-arduino-and-usb-host-shield
