### ISSUE TITLE
Which device+version combos require blobs?

### ISSUE THREAD

**Issue by gamer191** [LukeZGD/Legacy-iOS-Kit#399]
I noticed that https://github.com/LukeZGD/Legacy-iOS-Kit/commit/0ba8a76392db9dbed511aace3697674113a66d0e mentions requiring blobs. I'm curious what other device+version combos do? Also, this should probably be documented at https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Jailbreaking-with-Legacy-iOS-Kit, since I doubt many people will have blobs (unless Legacy iOS Kit is able to generate them?)

**Comment by LukeZGD** [comment]
"with blobs" in this context means that your device must be already on the version you want to jailbreak (for example, an iPad 2 that is currently on iOS 4.3.5 and has not been tether downgraded or anything like that)

This applies to pretty much all versions (except on the older devices that do not need blobs, listed in the README)
