### ISSUE TITLE
Outdated curl

### ISSUE THREAD

**Issue by ErveI** [LukeZGD/Legacy-iOS-Kit#400]
I did update with homebrew but Legacy IOS Kit says that you have outdated curl. What am I have to do?
![Ekran Resmi 2024-01-28 18 14 25](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/51764827/0330e093-9ca7-44e2-befd-eb64b7841a10)

**Comment by LukeZGD** [comment]
Make sure to have `/usr/local/bin` (or `/opt/homebrew/bin` for apple silicon) in `PATH`. 
To verify this, run command `which curl`, it should output `/usr/local/bin/curl` (not `/usr/bin/curl`). ig ill add additional checks for this later

**Comment by ErveI** [comment]
It doesn't says like that.

![Ekran Resmi 2024-01-28 19 10 32](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/51764827/7577f84c-3e8c-4597-8c0c-c0ac61505535)

**Comment by ErveI** [comment]
![Ekran Resmi 2024-01-28 19 17 35](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/51764827/620c23d8-2a54-4eb1-a672-ddb2a805db79)

how do I change to /usr/local/bin/curl
