### ISSUE TITLE
Type-c to lighting cable

### ISSUE THREAD

**Issue by topdzd** [LukeZGD/Legacy-iOS-Kit#402]
I'm new here. And I want to downgrade my iPhone 5 from iOS 10.3.4 to iOS 8.4.1.
Following the steps in usage step by step, but I always fail to enter the DFU mode somehow.
I'm kind of stuck in the iTunes step. 
I'm using the MacBook Pro m1 and the cable is type-c to lighting for iPhone 13.
I wondered what caused the failure, cable or the system platform.

**Comment by LukeZGD** [comment]
lightning to usb c cable is the problem.
use a lightning to usb A cable. use an adapter if needed.
