### ISSUE TITLE
Restore to iOS 7 Beta 1 failing

### ISSUE THREAD

**Issue by elis-tech** [LukeZGD/Legacy-iOS-Kit#404]
Hi,

I've been trying to use powdersn0w to install iOS 7 beta 1 onto my iPhone 4s.

However, the restore never completes. It says DONE in the Legacy-iOS-Kit window, but my iPhone still has a progress bar. It's almost full, but not completely. Is there a fix for this?

I'm using macOS Catalina (10.5.7) and the latest version of Legacy-iOS-Kit (it updated itself this morning.)

Thank you :)

**Comment by LukeZGD** [comment]
I have no fix for this, sorry, I have no idea why this happens. For now, just use 7 beta 2 since that one works fine
