### ISSUE TITLE
Problem with restoring iPad3 to 9.3.6 after downgrading to 8.4.1

### ISSUE THREAD

**Issue by MaximilianHerrmann** [LukeZGD/Legacy-iOS-Kit#406]
Dear Sir or Madam,

I am experiancing the following problem:

`*** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.02.10 (bba456b)
* Platform: linux (Fedora Linux 38 (Workstation Edition)) 

* Device: iPad3,3 (j2aap) in Normal mode
* iOS Version: 8.4.1 (12H321)
* ECID: xxxxxxxxxxxxx

* Selected IPSW: ../iPad3,3_9.3.6_13G37_Restore.ipsw

* This restore will use 9.3.6 baseband if the jailbreak option is disabled

 > Main Menu > Restore/Downgrade > Latest iOS (9.3.6)
[Input] Select an option:
1) Select Target IPSW	 3) Start Restore
2) Download Target IPSW	 4) Go Back
#? 3
[Log] Checking firmware keys in ../resources/firmware/iPad3,3/13G37
[Log] Getting firmware keys for iPad3,3-13G37
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  223k    0  223k    0     0   430k      0 --:--:-- --:--:-- --:--:--  430k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0     18      0  0:00:01  0:00:01 --:--:--    18
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 8888 after 0 ms: Couldn't connect to server
[Error] Failed to download firmware keys.

* Legacy iOS Kit v24.02.10 (bba456b)
* Platform: linux (Fedora Linux 38 (Workstation Edition)) 
HM@fedora ~ [1]> 

`

Hopefully someone can explain the reason to me.

Best regards,
Max

**Comment by LukeZGD** [comment]
Oh.. didn't consider that in one of the changes I made recently. I'll be fixing it real quick
