### ISSUE TITLE
stuck dkwngrading

### ISSUE THREAD

**Issue by bradycodemaster** [LukeZGD/Legacy-iOS-Kit#407]
[Log] Placing device to pwnDFU mode using gaster
usb_timeout: 5
usb_abort_timeout_min: 0
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227

**Comment by bradycodemaster** [comment]
okay now im at thi part  *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.02.18 (f26caeb)
* Platform: linux (Fedora Linux 39.20240205.0 (Bazzite)) 

* Device: iPhone6,1 (n51ap) in DFU mode
* iOS Version: Unknown
* ECID: 6833433412432
* Pwned: checkm8

* Selected IPSW: ../iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw

 > Main Menu > Restore/Downgrade > iOS 10.3.3
[Input] Select an option:
1) Select Target IPSW
2) Download Target IPSW
3) Start Restore
4) Go Back
#? 3
[Log] Patching iBSS and iBEC...
Archive:  ../iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBSS.iphone6.RELEASE.im4p  
Archive:  ../iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBEC.iphone6.RELEASE.im4p  
[Log] Pwned iBSS and iBEC saved at: saved/iPhone6,1
[Log] Found existing saved 10.3.3 blobs: ../saved/shsh/6833433412432_iPhone6,1_n51ap_10.3.3-14G60_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2
[WARNING] python2 is not installed. Attempting to install python2 before continuing
* You may install python2 from pyenv by running: pyenv install 2.7.18
[Log] Installing python2 using pyenv
* This may take a while, but should not take longer than a few minutes.
Downloading Python-2.7.18.tar.xz...
-> https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tar.xz
Installing Python-2.7.18...
patching file configure
patching file configure.ac
patching file setup.py
patching file Mac/Tools/pythonw.c
patching file setup.py
patching file Doc/library/ctypes.rst
patching file Lib/test/test_str.py
patching file Lib/test/test_unicode.py
patching file Modules/_ctypes/_ctypes.c
patching file Modules/_ctypes/callproc.c
patching file Modules/_ctypes/ctypes.h
patching file Modules/_ctypes/callproc.c
patching file setup.py
patching file Mac/Modules/qt/setup.py
patching file setup.py

BUILD FAILED (Fedora 39 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20240210131414.163082
Results logged to /tmp/python-build.20240210131414.163082.log

Last 10 log lines:
checking for --with-universal-archs... no
checking MACHDEP... linux2
checking EXTRAPLATDIR... 
checking for --without-gcc... no
checking for --with-icc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/python-build.20240210131414.163082/Python-2.7.18':
configure: error: C compiler cannot create executables
See `config.log' for more details
[WARNING] Cannot detect python2 from pyenv, its installation may have failed.
* Try installing pyenv and/or python2 manually:
    pyenv:   > curl https://pyenv.run | bash
    python2: > /home/brady/.pyenv/bin/pyenv install 2.7.18

**Comment by LukeZGD** [comment]
run `sudo dnf group install "C Development Tools and Libraries"` then try again
