### ISSUE TITLE
iPhone 5 won't restore with SHSH blob 6.1.4

### ISSUE THREAD

**Issue by NagyAttilaORG** [LukeZGD/Legacy-iOS-Kit#410]
Dead Luke!

I have a problem with the latest Kit, there is an iPhone 5 with onboard 6.1.4 SHSH blobs and I can not restore it.
This is the LOG: 

Updating gas gauge software (46)
Updating baseband (19)
About to send BasebandData...
sending request without baseband nonce
WARNING: Unable to find BbSkeyId node
Sending Baseband TSS request...
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
ERROR: Unable to fetch Baseband TSS
ERROR: Unable to send baseband data
ERROR: Unable to successfully restore device
ERROR: Unable to restore device
Sending TSS request attempt 1... 

If I try the --disable-bbupdate it is working but won't activate. This problem is new, until the new update it worked like charm.

Is there any solution? 
Thank you!

**Comment by LukeZGD** [comment]
Is this with iPhone5,1? If so I'll do some changes in a bit

**Comment by NagyAttilaORG** [comment]
No, it's an iPhone5,2 (n42ap).

**Comment by LukeZGD** [comment]
That is weird then, I have done many successful tests with the iPhone5,2. Do you have the full terminal output for more details? (Mac or Linux?)

**Comment by NagyAttilaORG** [comment]
Oh LukeZGD!

I've made a huge mistake, just used the old CustomJ ipsw, now I have deleted it and generated a new one and it is working perfectly. Sorry about that. Was a huge user error.
Thank you for your quick response!
