### ISSUE TITLE
Battery Logo

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#411]
is there any way the battery logo when your phone is out of battery can be the iOS 6 one for iOS 7 Downgraded powdersn0w devices

**Comment by LukeZGD** [comment]
Not possible, since these have to be signed as part of the iOS 7 firmware components

The only reason why the iOS 6 Apple logo is possible is because of the iBoot jump also jumping to the old logo. I just made the iOS 7 logo to be a blank one by not adding it to the manifest
