### ISSUE TITLE
features requests

### ISSUE THREAD

**Issue by bradycodemaster** [LukeZGD/Legacy-iOS-Kit#412]
1 powder snow for all ios 7 blobs 7.0.0-7.1.2
2 ipod touch 4 and iphone 4,2  unthered downgrade without blobs all versions
3 powdersnow iphone 4,1 4.2.1 ipad 1 3.2-4.2.1 and ipod touch 3 3.1-4.0
4 a5 pwn no audriuno
5 a7 pwn fix on linux

**Comment by LukeZGD** [comment]
1, 2, 3: see my comments in https://github.com/LukeZGD/Legacy-iOS-Kit/issues/337, https://github.com/LukeZGD/Legacy-iOS-Kit/issues/352 and https://github.com/LukeZGD/Legacy-iOS-Kit/issues/371

4 and 5 are also not possible
