### ISSUE TITLE
Line 4176: syntax error near unexpected token `else'

### ISSUE THREAD

**Issue by FitTerminator** [LukeZGD/Legacy-iOS-Kit#413]
Latest commit of the tool results in the following error(s):

line 4176: syntax error near unexpected token `else'

and

line 4176: `    else'

**Comment by LukeZGD** [comment]
Oh oops, I forgot to check/shellcheck again, fixing it real quick

**Comment by FitTerminator** [comment]
Great work as always, thanks for the quick fix!
