### ISSUE TITLE
iPod touch DFU IPSW Restore Issue: Stuck on White Screen and Reverts to iTunes Recovery

### ISSUE THREAD

**Issue by fabianober** [LukeZGD/Legacy-iOS-Kit#414]
Hi, 
I am trying to restore an iPod touch 4. For all my other iPods, this tool works perfectly except for one iPod.

Since the Home Button is broken and I cannot enter DFU mode manually, **I created the DFU IPSW, which should force the iPod to go into DFU mode**. 

When I use the **restore to DFU IPSW function**, everything seems to work until the iPod shows the **Apple logo with the progress bar** beneath. Then it **stops, shows a white screen for a second and directly goes back to the iTunes recovery screen**. 

This behavior also occurs when trying to reinstall any other IPSW. It always goes back to the iTunes screen and entering DFU Mode via the buttons does not work. Maybe someone has an idea?

**These are the last few lines from the terminal. The script then just stops...:**

Sending RestoreKernelCache (7271449 bytes)...
About to restore device... 
Waiting for device...
Device 07313458a8e9df09cd06bd820f09c59156935cbc is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 12
Device 07313458a8e9df09cd06bd820f09c59156935cbc has successfully entered restore mode
Hardware Information:
BoardID: 8
ChipID: 35120
UniqueChipID: 4000981441998
ProductionMode: true
Panic log is available:
panic(cpu 0 caller 0x9a0dbac5): "Failed _ReplaceBadBlock CE 1 PBN 437"
Debugger message: panic
OS version: 10B500
Kernel version: Darwin Kernel Version 13.0.0: Wed Feb 13 21:36:52 PST 2013; root:xnu-2107.7.55.2.2~1/RELEASE_ARM_S5L8930X
iBoot version: iBoot-1537.9.55
secure boot?: YES
Paniclog version: 1
Kernel slide:     0x0000000019800000
Kernel text base: 0x99801000
Epoch Time:        sec       usec
  Boot    : 0x00596ab2 0x00000000
  Sleep   : 0x00000000 0x00000000
  Wake    : 0x00000000 0x00000000
  Calendar: 0x00596ab9 0x0004cbf7

Task 0x80193c20: 5009 pages, 83 threads: pid 0: kernel_task
        thread 0x8029f6d0
                kernel backtrace: 8b3f3bc0
                  lr: 0x99889fa1  fp: 0x8b3f3bf0
                  lr: 0x9988a83d  fp: 0x8b3f3c1c
                  lr: 0x99817ca7  fp: 0x8b3f3c34
                  lr: 0x9a0dbac5  fp: 0x8b3f3c98
                  lr: 0x9a0d6c9d  fp: 0x8b3f3d00
                  lr: 0x9a0df6eb  fp: 0x8b3f3d28
                  lr: 0x9a0e8c71  fp: 0x8b3f3d48
                  lr: 0x9a0e7cbf  fp: 0x8b3f3da0
                  lr: 0x9a0e7ab3  fp: 0x8b3f3dbc
                  lr: 0x9a0e294d  fp: 0x8b3f3e3c
                  lr: 0x9a0d5c39  fp: 0x8b3f3e9c
                  lr: 0x9a0efe09  fp: 0x8b3f3ed8
                  lr: 0x99a49ba7  fp: 0x8b3f3f10
                  lr: 0x99a49823  fp: 0x8b3f3f60
                  lr: 0x99a4a2f9  fp: 0x8b3f3f88
                  lr: 0x99a4a0cb  fp: 0x8b3f3fa8
                  lr: 0x9988805c  fp: 0x00000000

Task 0x80193968: 365 pages, 3 threads: pid 1: launchd
Task 0x801936b0: 543 pages, 1 threads: pid 2: launchctl
Task 0x801933f8: 748 pages, 1 threads: pid 3: restored_externa
Task 0x80193140: 3083 pages, 4 threads: pid 4: restored_externa

**Comment by LukeZGD** [comment]
Try restoring to 6.1.6 first. If it can't restore to 6.1.6, there might be something wrong with the iPod
