### ISSUE TITLE
Stuck at "waiting for NAND (28)" when trying to reset iphone 4 (GSM) to iOS 7.1.2 without jailbreak

### ISSUE THREAD

**Issue by reenatok** [LukeZGD/Legacy-iOS-Kit#415]
Hi all, ive been trying to reset an iPhone 4 that's stuck on DFU mode with a black screen, it just starts resetting and the apple logo with the progress bar appears but it doesn't do anything. Ive tried it with different versions of iTunes, 3utools, and i came across Legacy-iOS-Kit and it gets stuck with the apple logo and progress bar, and terminal shows "waiting for NAND (28)"

What could this issue be for? Thank you in advance

Terminal log:

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.02.33 (c1f2864)
* Platform: macos (14.4) 

* Device: iPhone3,1 (n90ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 2208762523022

 > Main Menu > Restore/Downgrade
[Input] Select an option:
1) powdersn0w (any iOS)
2) Latest iOS (7.1.2)
3) Other (Use SHSH Blobs)
4) DFU IPSW
5) Go Back
#? 2
[Log] Getting SHA1 hash for ../iPhone3,1_7.1.2_11D257_Restore.ipsw...
[Log] Using saved SHA1 hash for this IPSW: 81da17b3e893a61508fe203849b7e1f60e2127b1
[Log] IPSW SHA1sum matches

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.02.33 (c1f2864)
* Platform: macos (14.4) 

* Device: iPhone3,1 (n90ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 2208762523022

* Selected IPSW: ../iPhone3,1_7.1.2_11D257_Restore.ipsw

* This restore will use 7.1.2 baseband if the jailbreak option is disabled

 > Main Menu > Restore/Downgrade > Latest iOS (7.1.2)
[Input] Select an option:
1) Select Target IPSW
2) Download Target IPSW
3) Start Restore
4) Go Back
#? 3
[Input] Jailbreak Option
* When this option is enabled, your device will be jailbroken on restore.
* I recommend to enable this option to have the jailbreak and Cydia pre-installed.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): n
[Log] Jailbreak option disabled by user.

[Log] Extracting IPSW: ../iPhone3,1_7.1.2_11D257_Restore.ipsw
Archive:  ../iPhone3,1_7.1.2_11D257_Restore.ipsw
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/058-4107-013.dmg  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/058-4266-010.dmg  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/058-4520-010.dmg  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/BuildManifest.plist  
   creating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/
   creating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/
   creating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/applelogo@2x~iphone.s5l8930x.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/batterycharging0@2x~iphone.s5l8930x.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/batterycharging1@2x~iphone.s5l8930x.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/batteryfull@2x~iphone.s5l8930x.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/batterylow0@2x~iphone.s5l8930x.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/batterylow1@2x~iphone.s5l8930x.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/DeviceTree.n90ap.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/glyphplugin@2x~iphone-30pin.s5l8930x.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/iBoot.n90ap.RELEASE.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/LLB.n90ap.RELEASE.img3  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/manifest  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/all_flash/all_flash.n90ap.production/recoverymode@2x~iphone-30pin.s5l8930x.img3  
   creating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/dfu/
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/dfu/iBEC.n90ap.RELEASE.dfu  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/dfu/iBSS.n90ap.RELEASE.dfu  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/ICE3_04.12.09.Release.bin  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/ICE3_04.12.09_BOOT_02.13.Release.bbfw  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/ICE3_04.12.09_BOOT_02.13.Release.plist  
   creating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/usr/
   creating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/usr/local/
   creating: ../iPhone3,1_7.1.2_11D257_Restore/Firmware/usr/local/standalone/
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/kernelcache.release.n90  
  inflating: ../iPhone3,1_7.1.2_11D257_Restore/Restore.plist  
[Log] Running idevicerestore with command: ../bin/macos/idevicerestore -e "../iPhone3,1_7.1.2_11D257_Restore.ipsw"
Found device in DFU mode
Found ECID 2208762523022
Identified device as n90ap, iPhone3,1
Extracting BuildManifest from IPSW
Product Version: 7.1.2
Product Build: 11D257 Major: 11
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Getting ApNonce in dfu mode... c2 90 96 45 df e0 75 73 a0 bb 8c 49 a2 0b 86 b6 e5 ae a3 c5 
Trying to fetch new SHSH blob
Getting SepNonce in dfu mode... 
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
Using cached filesystem from '../iPhone3,1_7.1.2_11D257_Restore/058-4520-010.dmg'
Extracting iBSS.n90ap.RELEASE.dfu...
Personalizing IMG3 component iBSS...
reconstructed size: 68057
Sending iBSS (68057 bytes)...
[==================================================] 100.0%
Nonce: c2 90 96 45 df e0 75 73 a0 bb 8c 49 a2 0b 86 b6 e5 ae a3 c5 
Extracting iBEC.n90ap.RELEASE.dfu...
Personalizing IMG3 component iBEC...
reconstructed size: 285145
Sending iBEC (287897 bytes)...
[==================================================] 100.0%
Getting ApNonce in recovery mode... c2 90 96 45 df e0 75 73 a0 bb 8c 49 a2 0b 86 b6 e5 ae a3 c5 
Sending APTicket (2741 bytes)
Recovery Mode Environment:
iBoot build-version=iBoot-1940.10.58
iBoot build-style=RELEASE
ramdisk-size=0x4000000
Extracting 058-4107-013.dmg...
Not personalizing component RestoreRamDisk...
Sending RestoreRamDisk (8892684 bytes)...
Extracting DeviceTree.n90ap.img3...
Not personalizing component RestoreDeviceTree...
Sending RestoreDeviceTree (74764 bytes)...
Extracting kernelcache.release.n90...
Not personalizing component RestoreKernelCache...
Sending RestoreKernelCache (8115660 bytes)...
About to restore device... 
Waiting for device...
Device 9296a3faa094e79c88d32822ee8abafa734d2181 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 13
Device 9296a3faa094e79c88d32822ee8abafa734d2181 has successfully entered restore mode
Hardware Information:
BoardID: 0
ChipID: 35120
UniqueChipID: 2208762523022
ProductionMode: true
Waiting for NAND (28)

**Comment by LukeZGD** [comment]
Try to do a clear nvram: Other Utilities -> Clear NVRAM, and/or try doing a DFU restore with iTunes or Finder once.

You can also try to just wait it out: "Waiting for NAND" can also take a very long time, I observed this when I was testing restores on my 3GS and 4

**Comment by reenatok** [comment]
When i try to clear NVRAM, it gives me this error: "ERROR: This device is in soft (LLB/iBSS) DFU mode.
please put device in normal DFU mode.", and then it fails because my iPhone 4 won't go into recovery mode, its stuck in DFU mode without anything in the screen and it won't do anything apart from that, what should i do?, thank you in advance.

**Comment by LukeZGD** [comment]
Ah, I see now.

Even while the screen is black, do the DFU mode procedure (hold both power and home buttons for 10 seconds, release power and keep holding home for 10 seconds)

Then try restoring again

**Comment by reenatok** [comment]
hello, ive already cleared the NVRAM and put it into the correct mode of DFU mode but i left it overnight in the restore process into iOS 7.1.2, and it got stuck at "Waiting for NAND (28", does this mean that there's a hardware issue with the iphone?, thank you in advance.
