### ISSUE TITLE
Can I just restore my iPhone5 from downgraded iOS 6 to iOS 7 using iOS7 shsh

### ISSUE THREAD

**Issue by topdzd** [LukeZGD/Legacy-iOS-Kit#418]
I downgrade to iOS 6.1.4 with jailbreak, Then I restore it to iOS 7 using iOS 7 SHSH with the Other ( Use SHSH Blobs) option.
After the process, it's done. and iPhone restarts automatically but somehow it's stuck in recovery mode.
I use press buttons or send the exit recovery command in the legacy tool. Both ways won't work.
So, it's a bug or Jailbreak that causes this consequence.

**Comment by LukeZGD** [comment]
Use Clear NVRAM option: Other Utilities -> Clear NVRAM

Or restore to 10.3.4 and follow this: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting#clearing-nvram

**Comment by topdzd** [comment]
Thanks, bro.  It works.
