### ISSUE TITLE
Downgrade i5S iOS 9.3.1 using SHSH2

### ISSUE THREAD

**Issue by Ziiipple2022** [LukeZGD/Legacy-iOS-Kit#419]
i have dump my shsh iOS 9.3.1 onboard using your script, but i can't downgrade my 5S...

**Comment by Ziiipple2022** [comment]
and for restore to lastest same.. no work 

For downgrade SEP error 
and for latest : 

.7_16H81_Restore/038-87199-051.dmg  
[Log] Running idevicerestore with command: ../bin/macos/idevicerestore2 -ey "../iPhone_4.0_64bit_12.5.7_16H81_Restore.ipsw"
./restore.sh: line 3700:  1810 Killed: 9               $idevicerestore2 $ExtraArgs "$ipsw_path.ipsw"
* For device activation, go to: Other Utilities -> Attempt Activation

* Save the terminal output now if needed.
* Legacy iOS Kit v24.02.38 (16a9037)
* Platform: macos (14.0)

**Comment by LukeZGD** [comment]
It is currently impossible to use <iOS 10 blobs for the 5S

Also for restoring to latest on 64-bit devices, just use iTunes/Finder
