### ISSUE TITLE
iPhone 4S on iOS 5 isn't detected

### ISSUE THREAD

**Issue by ledeuxiemenoe6262** [LukeZGD/Legacy-iOS-Kit#420]
when i plug my iphone 4s on iOS 5.0.1 (9A406) it just dosent connect

it only connects in recovery mode and dfu mode

i also tried re-installing the depedencies but that didnt work

i use ubuntu 22.04.3

**Comment by LukeZGD** [comment]
try this https://www.reddit.com/r/LegacyJailbreak/comments/17d9cit/comment/krjus22

**Comment by ledeuxiemenoe6262** [comment]
Thanks,but i meant normal mode

**Comment by LukeZGD** [comment]
Yes, restarting the PC is supposed to fix normal mode detection.. If it doesn't, I can't really help much at that point
