### ISSUE TITLE
iOS 4.3.x iPad 2 Gil1bert JB Support 

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#422]
is it usable yet??

**Comment by UInt2048** [comment]
Just try it and see lol. Dump your blobs if you're concerned

**Comment by LukeZGD** [comment]
The (semi-)tethered jailbreak is very usable now, works on all 4.3.x versions and iPad 2 devices

There is no progress on any untethered, I'm not even sure if this will be done anymore
