### ISSUE TITLE
Too many tries?

### ISSUE THREAD

**Issue by terminalN00b** [LukeZGD/Legacy-iOS-Kit#423]
Hello,

first of all, thank you so much for the legacy kit, Luke. I was able to downgrade some of my iPhone 5's to iOS 6. Now I wanted to do it once more for a friend, but suddenly, even though doing the exact same process, it doesn't work properly. I will provide the error code displayed in terminal later. But my question for now is: can I ruin/ break the device's-

*EDIT WHILE WRITING THIS: Nevermind. It worked! The issue was the SHSH iOS 7 blob. For some reason, when I saved it, this time it had the firmware Version number (I think) in the .shsh files name, which wasn't the case in the last few downgrades. After hours of trying, I decided to remove it from the filename and boom.
I'm still wondering though: Can the baseband 'break' by doing to many downgrading attempts, entering/exiting DFU mode, executing commands etc.? Because that was what I was mainly worried about here.

Best regards.

**Comment by LukeZGD** [comment]
Devices can be restored as many times as needed and it wouldnt break things. Unless there is already a hradware issue present on the device
