### ISSUE TITLE
Erase iPhone 64 bit with SSH Ramdisk

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#424]
how to do it, when entering command nvram oblit-inprogress=5

**Comment by Jefferyat** [comment]
error i get when trying is new session to port 62078 failed: 61

**Comment by Jefferyat** [comment]
when entering mount_filesystems i get this

.
localhost:~ root# mount_filesystems
seputil: can't read '/mnt1/usr/standalone/firmware/sep-firmware.img4'
seputil: rejecting zero-byte firmware
seputil: failed to load /mnt1/usr/standalone/firmware/sep-firmware.img4 in  mode

**Comment by Jefferyat** [comment]
im using iOS 10.3.1 iPhone 7 Plus

**Comment by LukeZGD** [comment]
here https://www.reddit.com/r/LegacyJailbreak/wiki/guides/sameioswipe

follow the ios 9 section, its used for ios 9 and newer

do not use the mount_filesystems command, only use that for ios 11.3 and newer

**Comment by Jefferyat** [comment]
Tried the guide on https://www.reddit.com/r/LegacyJailbreak/wiki/guides/sameioswipe method to erase device using nvram oblit-inprogress=5; exit and reboot device and the device still boots into recovery mode with Legacy iOS Kit, using SSHRD Ramdisk
