### ISSUE TITLE
How to Bypass iCloud with SSH Ramdisk in Legacy iOS Kit

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#427]
How do you bypass icloud and remove setup.app via SSH Ramdisk

Thank you for your awesome tool

**Comment by LukeZGD** [comment]
This depends on your iOS version (the mounting filesstems command will vary)

AFAIK you just need to move or remove /mnt1/Applications/Setup.app after mounting filesystem for a basic bypass without signal

beyond that I don't really know much else regarding that topic
