### ISSUE TITLE
Don't show Cydia iOS 3.1.3 

### ISSUE THREAD

**Issue by Ziiipple2022** [LukeZGD/Legacy-iOS-Kit#428]
After restore iOS 3.1.3 i don't see Cydia, and try to force with Jailbreak option, i don't see Cydia 

3GS 3.1.3 -- Alloc8 Restore

**Comment by LukeZGD** [comment]
Just select "Jailbreak Device" after restoring

**Comment by Ziiipple2022** [comment]
after restore, i select Jailbreak Option, don't show cydia..
