### ISSUE TITLE
Downgrade iPad mini 2 to 10.3.3 not working 

### ISSUE THREAD

**Issue by emeraldongithub** [LukeZGD/Legacy-iOS-Kit#430]
OS: Ubuntu [Live usb]

When it gets to the pwnDFU setup, It just goes back to normal recovery mode after a few seconds and nothing is displayed on the terminal 
![image](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/99167692/ec16d306-77ca-4be3-9f84-18143a9dc11b)
![image](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/99167692/6a0e2c25-29bb-4967-876a-35f5e5b5abc0)

**Comment by LukeZGD** [comment]
Please read the message above the gaster running with the 2 links

**Comment by emeraldongithub** [comment]
> Please read the message above the gaster running with the 2 links

Are you able to change it to ipwndfu, or is that only available on Mac?

**Comment by LukeZGD** [comment]
All checkm8 tools on Linux do not work on A6 and A7 devices. Use ipwnder on macOS or iOS
