### ISSUE TITLE
can core 2 duo actually put a device in pwnDFU mode?

### ISSUE THREAD

**Issue by cozumii8364** [LukeZGD/Legacy-iOS-Kit#434]
I’m trying to downgrade iPad 4,5 to 10.3.3 but I can’t enter pwnDFU mode (tried 6 times). I’m wondering if there is still a chance the Core 2 Duo can set a device to pwnDFU mode or if I will have to use iPwnder Lite to do it. Legacy iOS kit says that the rates are low but not impossible. I’m also on 10.13.6 if that helps

**Comment by LukeZGD** [comment]
I don't have one myself, but from what I know it can succeed after very many tries. It's not worth the trouble though, so just use iPwnder Lite on another iOS device to pwn your mini 2
