### ISSUE TITLE
Connection to SSH issue - iPhone 5s iOS 8.1.2

### ISSUE THREAD

**Issue by 12andrew42** [LukeZGD/Legacy-iOS-Kit#438]
Awesome project! Having issues with the following:

**when I try to mount using iOS 12 SSH tool:**

mounting both /mnt1 and /mnt2 work but I get the following code from FileZilla when trying to connect

> Status:      	Connecting to 127.0.0.1:6414...
> Status:      	Using username "root". 
> Status:      	Connected to 127.0.0.1
> Error:         	FATAL ERROR: Received unexpected end-of-file from SFTP server
> Error:         	Could not connect to server

**when I try to mount using iOS 8 SSH tool:** 

connection to the SFTP works on FileZilla

mounting /mnt1 works however get this issue when trying to mount /mnt2

```
localhost:~ root# mount -t hfs /dev/disk0s1s2 /mnt2
mount_hfs: Could not create property for re-key environment check: No such file or directory
GetMasterBlock: Error 83 from read; amount=-1, wanted=4096
GetMasterBlock: Error 83 from read; amount=-1, wanted=4096
```

It seems as I am stuck in a limbo between the two methods and am looking for a solution. I have tried ipwnd32 and lite but that doesn't affect anything.

Thanks in advance.

**Comment by LukeZGD** [comment]
Identified the issue, pushing the fix now

**Comment by LukeZGD** [comment]
Now the scp/sftp issue with the iOS 12 ramdisk is fixed

**Comment by 12andrew42** [comment]
> Now the scp/sftp issue with the iOS 12 ramdisk is fixed

worked! thanks so much.

**Comment by 12andrew42** [comment]
also @LukeZGD not sure if you want to add this to the features or if it's already implied. Was able to get into the phone (disabled) by swapping the pblist.tar file in the shhrd folder with my own custom one. Here's the code I used. 

`<key>SBDeviceLockBlockStateGeneration</key>
	<integer>8847</integer>
	<key>SBDeviceLockBlocked</key>
	<false/>
	<key>SBDeviceLockFailedAttempts</key>
	<integer>-9999</integer>`

Thanks again for the quick fix and amazing tool, only one I could get to work!
