### ISSUE TITLE
Get/Reset Pin on IPad 1st gen IOS 5.1.1

### ISSUE THREAD

**Issue by Heiwa03** [LukeZGD/Legacy-iOS-Kit#439]
Hello! Is there some way to get/reset/bypass the pin on an ipad 1,1 with ios 5.1.1 using this kit? I can get into ramdisk ssh but i don't know what to do afterwards. Some guidance would be much appreciated!

**Comment by LukeZGD** [comment]
I don't really know much regarding that topic, sorry
