### ISSUE TITLE
Issue trying to restore an iPhone 3G (Could not make sure this firmware is suitable for the current device.)

### ISSUE THREAD

**Issue by circularsprojects** [LukeZGD/Legacy-iOS-Kit#442]
I'm trying to restore my iPhone 3G using iOS 4.2.1 (jailbreak & hackivate option enabled), but it fails very early into the restore with "ERROR: Could not make sure this firmware is suitable for the current device. Refusing to continue."
Looking at the output, idevicerestore is identifying the device as an iPhone1,1 (2G), which is just completely wrong.
I know it's an iPhone 3G as it was on a version of iOS 4 before i restored it back to 3.1.3 (which did work), and the restore.sh tool detects it as iPhone1,2
I've tried recompiling idevicerestore (the custom fork used), but clearly it was not meant to be compiled on apple silicon, and keeps on failing.
The actual up-to-date idevicerestore doesn't work either.

Any help or insight would be appreciated, I can also attach more logs if required.

[3g.txt](https://github.com/LukeZGD/Legacy-iOS-Kit/files/14657778/3g.txt)

**Comment by LukeZGD** [comment]
Try to disable the jailbreak option since it's broken for S5L8900 devices. 

Just jailbreak the device later using the "Jailbreak Device" option, and hacktivate by going to "Other Utilities -> Hacktivate Device" after jailbreaking.

This should work for versions 3.1.3-4.2.1 for your device. Let me know if this works or not

**Comment by circularsprojects** [comment]
idevicerestore detects the model correctly, but now it can't place the device into recovery mode from DFU mode.

**Comment by circularsprojects** [comment]
[3g.txt](https://github.com/LukeZGD/Legacy-iOS-Kit/files/14658985/3g.txt)
I tried from normal mode as well, but I keep getting the same error

**Comment by LukeZGD** [comment]
Try again on the latest update (v24.03.28)

**Comment by circularsprojects** [comment]
It worked! I was able to successfully restore my 3G to 4.2.1, however I can't hacktivate, activate or jailbreak the device, but I think that deserves its own issue.
