### ISSUE TITLE
iPhone 3G Error "This iPhone was previously in DFU mode, but restarted and is no longer in DFU mode. To restore this iPhone from DFU mode, disconnect it and place it in DFU mode again."

### ISSUE THREAD

**Issue by GeorgeDouglasMcFly** [LukeZGD/Legacy-iOS-Kit#449]
Hi there,

I recently found my old iPhone 3G with stuck in bootloop and wanted to reset it. During the normal process via Finder on macOS I receive this error:

"This iPhone was previously in DFU mode, but restarted and is no longer in DFU mode. To restore this iPhone from DFU mode, disconnect it and place it in DFU mode again."

Then I found your great kit and tried to reset it. Unfortunately I receive this message in the terminal:

`[Log] Running on platform: macos (14.4.1)
[Log] Checking Internet connection...
[Log] Checking for updates...
[Log] Finding device in Normal mode...
ERROR: No device found!
ERROR: No device found!
[Log] Finding device in Recovery/DFU mode...
[Log] Getting device info...
[Log] Found an S5L8900 device in DFU mode. Please re-enter WTF mode for good measure.
* Force restart your device and place it in normal or recovery mode, then run the script again.`

Do you have any idea how to fix this?

**Comment by LukeZGD** [comment]
Yeah just do the DFU mode procedure for that:

- Hold home and power button for about 10 seconds
- Release power and keep holding home for about 10 seconds

**Comment by GeorgeDouglasMcFly** [comment]
Hi @LukeZGD,

believe me or not, but it is in DFU mode.

I found more users having the same issue ([example 1](https://www.reddit.com/r/LegacyJailbreak/comments/16n42wa/cant_restore_any_device_now_question/), [example 2](https://discussions.apple.com/thread/254509547?sortBy=best) & [example 3](https://discussions.apple.com/thread/255152539?sortBy=best)).

Is there any other solution?

**Comment by LukeZGD** [comment]
Try recovery mode, then:

- Hold home and power button for about 10 seconds
- Release all buttons
- Hold power button for about 2 seconds
- Release power and start holding home until recovery screen shows up

In any case, iTunes issues are irrelevant here, the device just has to be in normal, recovery, or WTF mode. DFU mode is not allowed because the phone can only be pwned from WTF mode

**Comment by GeorgeDouglasMcFly** [comment]
Thanks for you quick response.

Unfortunately I cannot put my iPhone into recovery mode. How do I get the WTF mode?

**Comment by LukeZGD** [comment]
> Unfortunately I cannot put my iPhone into recovery mode. How do I get the WTF mode?

Plug the device in wall adapter, and do the DFU mode button procedure. Do not plug in the device yet. Run restore.sh, and when it says "Finding device in DFU/recovery mode" plug in the device

**Comment by GeorgeDouglasMcFly** [comment]
Thank you, we are getting closer. This time I receive this in the console:

<img width="746" alt="Screenshot 2024-03-28 at 12 53 57" src="https://github.com/LukeZGD/Legacy-iOS-Kit/assets/62904800/24e61170-0dd8-4490-910c-c5efbcd33ea6">

**Comment by LukeZGD** [comment]
Create a folder named saved on where the restore.sh is located

**Comment by GeorgeDouglasMcFly** [comment]
Really appreciate your support and software! So I tried to restore 4.2.1 on the 3G.

At the end I got this in the log:

`
...
Sending iBEC (167284 bytes)...
ERROR: Unable to connect to device in recovery mode
ERROR: Unable to place device into restore mode
[Log] Restoring done! Read the message below if any error has occurred:
* Please read the "Troubleshooting" wiki page in GitHub before opening any issue!
* Your problem may have already been addressed within the wiki page.
* If opening an issue in GitHub, please provide a FULL log/output. Otherwise, your issue may be dismissed.
* For device activation, go to: Other Utilities -> Attempt Activation
[WARNING] Do not uninstall Cydia Substrate and Substrate Safe Mode in Cydia!

* Save the terminal output now if needed.
* Legacy iOS Kit v24.03.36 (ad57fab)
* Platform: macos (14.4.1) `

**Comment by GeorgeDouglasMcFly** [comment]
Update: Now everything works. You are a hero!
