### ISSUE TITLE
iPhone 4 won't charge 

### ISSUE THREAD

**Issue by Raphi69420** [LukeZGD/Legacy-iOS-Kit#451]
Yeah, so I have a problem which might be a Problem with the Downgrade or with my new Frame. I downgraded it to iOS 5 and it worked after this normal. Yesterday I got a new Frame with Charging Flex and everything. This also worked for a time normal. Then I wanted to reset the deivce so I can start this as a new phone becuase it basiclly is. I clicked "Erase all Data&Settings". Then it ended up as a endless spinning wheel. I went home and plugged it in to a computer. Neither did it charge or connect to a PC. My Mac says nothing and my Windows PC says USB device not recognised. I wonder if it is a problem with the Reset with the downgrade. If someone can't help me then I would try a new Dock Connector. But thanks for anybodys help.

**Comment by LukeZGD** [comment]
> clicked "Erase all Data&Settings"

Never do this on a jailbroken device.

Alright, here are some tips for now: Make sure that the device is in DFU mode. To do this, just do the DFU mode procedure:

- Plug in the device in the PC/Mac or power adapter
- Hold home and power button for about 10 seconds
- Release power and keep holding home for about 10 seconds

Now the device should be able to be seen in the PC/Mac and restore it using iTunes/Finder/Legacy iOS Kit. If not, then yeah there might be something wrong with your dock connector.

If you restore it back to iOS 7.1.2, make sure to go to Other Utilities -> Clear NVRAM after the restore.

**Comment by Raphi69420** [comment]
Ok I will try it. Thanks
