### ISSUE TITLE
iPhone 5S iOS 8 sshrd isn't working because the iarchive site is down

### ISSUE THREAD

**Issue by Un1q32** [LukeZGD/Legacy-iOS-Kit#457]
A major issue with this is that it doesn't error out when curl fails to download the tar like it should, it just keeps going, leading to a failed ramdisk boot with an apple logo and forever empty progress bar, where it isn't obvious what went wrong and the only way to figure it out is to read through a wall of text.  curl downloads should really be error checked so the scripts fails immediately when more links inevitably die.

**Comment by LukeZGD** [comment]
yeah this is fixed in the test branch, will be pushing it to main soon
