### ISSUE TITLE
How do I restore dumped baseband?

### ISSUE THREAD

**Issue by ItsOver23** [LukeZGD/Legacy-iOS-Kit#459]
Hi, I have an iPad 4th gen celluar o 6.0.1, I dumped both the baseband and shsh blobs and did a restore with the dumped blobs. However after the restore I noticed that it has updated my modem firmware from 2.03.09 to 11.80.00, is there a way which I can downgrade the modem firmware by flashing my dumped baseband? Thanks
![IMG_1711](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/152078685/122642f6-ca02-4faa-8465-7bd619815928)

**Comment by LukeZGD** [comment]
you shouldve enabled "disable-bbupdate" in other utilities if you want to use the baseband dump. your baseband dump is now useless. baseband dump is only used for preserving baseband, not downgrading. there is no downgrading baseband, except on signed ota ones with 6.1.3 and 8.4.1

baseband version doesnt really matter on a5 and a6 devices anyway
