### ISSUE TITLE
iPhone 5 stuck on black screen

### ISSUE THREAD

**Issue by WinyJeff** [LukeZGD/Legacy-iOS-Kit#464]
Nothing i do will wake it up, not holding the buttons, or anything in legacy ios kit or using finder to restore. i have no log because there is no need. nothing works. i tried a tethered downgrade to ios 7.1.2 and tried just boot, and thats when it decided it didnt want to do anything.

**Comment by LukeZGD** [comment]
have you tried disconnecting the battery and reconnecting it? also check your buttons, and it can also be a hardware issue that is not caused by legacy ios kit at all.
