### ISSUE TITLE
How to improve Linux pwndfu

### ISSUE THREAD

**Issue by bradycodemaster** [LukeZGD/Legacy-iOS-Kit#466]
1. When at the patch stage unplug iPhone then plug it back in after 15 seconds
2. Have auto retry instead of quitting should be on all actions
3. Add ipwnder lite for iOS 8 host a6 users downgrade to this and can’t use ipwnder lite
4. Add ipwnder lite for a5 host and target
5. Remove amd support. And drops scuess rate way more than using linux

**Comment by LukeZGD** [comment]
Not dealing with this

https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting
https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Pwning-Using-Another-iOS-Device
