### ISSUE TITLE
powdersn0w support check

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#467]
Will Powdersn0w Add

iOS 3.2-3.2.2 Targets for iPad 1 (Boot Issues Fixed)

iOS 4.2.1 for iPhone 4 GSM (Boot Issues Fixed)

iOS 4.2.6-iOS 4.2.10 for iPhone 4 CDMA (Boot Issues Fixed)

iOS 3.1.1-iOS 3.1.3 for iPod Touch 3G (Boot Issues Fixed)

**Comment by LukeZGD** [comment]
I'm putting Legacy iOS Kit in pretty much a "feature freeze" state. There will be no more additional features or support added outside of what is listed in the current features and supported device/version lists. It will only be bug/issue fixing with the current feature set from now on.

All of the powdersn0w versions mentioned in OP will not be fixed. 

Downgrade issues with 2.x and below will not be fixed.

I will also not be dealing with jailbreaking any version below 3.1.

Issues with 64-bit stuff will not be prioritized as the main focus of LiK is 32-bit.
