### ISSUE TITLE
iPhone5,3 (n48ap) tethered boot for iOS 7.1.2 (11D257) fails.

### ISSUE THREAD

**Issue by userse31** [LukeZGD/Legacy-iOS-Kit#472]
` *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.04.15 (3186c32)
* Platform: linux (Debian GNU/Linux 12 (bookworm)) 

* Device: iPhone5,3 (n48ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 1386906580299

 > Main Menu > Other Utilities
[Input] Select an option:
1) Send Pwned iBSS                   5) Activation Records               9) Enable disable-bbupdate flag    13) Go Back
2) Get iOS Version                   6) Just Boot                       10) Enable activation-records flag
3) Clear NVRAM                       7) SSH Ramdisk                     11) Enable skip-ibss flag
4) Dump Baseband                     8) Create Custom IPSW              12) (Re-)Install Dependencies
#? 6
* You are about to do a tethered boot.
[Input] Enter build version (eg. 10B329): 11D257
[Log] Checking firmware keys in ../resources/firmware/iPhone5,3/11D257
[Log] iBSS
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: http://appldnld.apple.com/ios10.3.3/091-23384-20170719-CA966D80-6977-11E7-9F96-3E9100BA0AE3/iPhone_4.0_32bit_10.3.3_14G60_Restore.ipsw
init done
Error: file Firmware/dfu/iBSS.n48ap.RELEASE.dfu does not exist, or is a directory
cp: cannot stat 'iBSS.n48ap.RELEASE.dfu': No such file or directory
mv: cannot stat 'iBSS.n48ap.RELEASE.dfu': No such file or directory
error: cannot open template
[Log] iBEC
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: http://appldnld.apple.com/ios10.3.3/091-23384-20170719-CA966D80-6977-11E7-9F96-3E9100BA0AE3/iPhone_4.0_32bit_10.3.3_14G60_Restore.ipsw
init done
Error: file Firmware/dfu/iBEC.n48ap.RELEASE.dfu does not exist, or is a directory
cp: cannot stat 'iBEC.n48ap.RELEASE.dfu': No such file or directory
mv: cannot stat 'iBEC.n48ap.RELEASE.dfu': No such file or directory
error: cannot open template
[Log] DeviceTree
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: http://appldnld.apple.com/ios10.3.3/091-23384-20170719-CA966D80-6977-11E7-9F96-3E9100BA0AE3/iPhone_4.0_32bit_10.3.3_14G60_Restore.ipsw
init done
Error: file Firmware/all_flash/all_flash.n48ap.production/DeviceTree.n48ap.img3 does not exist, or is a directory
cp: cannot stat 'DeviceTree.n48ap.img3': No such file or directory
mv: cannot stat 'DeviceTree.n48ap.img3': No such file or directory
error: cannot open template
[Log] Kernelcache
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: http://appldnld.apple.com/ios10.3.3/091-23384-20170719-CA966D80-6977-11E7-9F96-3E9100BA0AE3/iPhone_4.0_32bit_10.3.3_14G60_Restore.ipsw
init done
Error: file kernelcache.release.n48 does not exist, or is a directory
cp: cannot stat 'kernelcache.release.n48': No such file or directory
mv: cannot stat 'kernelcache.release.n48': No such file or directory
error: cannot open template
error: Cannot open image-file.
[Log] Patch iBSS
error: cannot open infile
main: Starting...
main: Error opening iBSS.raw!
error: cannot open template
[Log] Patch iBEC
error: cannot open infile
main: Starting...
main: Error opening iBEC.raw!
error: cannot open template
* Select Y if your device is in pwned iBSS/kDFU mode.
* Select N to place device to pwned DFU mode using ipwndfu/ipwnder.
* Failing to answer correctly will cause "Sending iBEC" to fail.
[Input] Is your device already in pwned iBSS/kDFU mode? (y/N): y
[Log] Pwned iBSS/kDFU mode specified by user.
[Log] Sending iBEC...
[Log] Finding device in Recovery mode...
[Error] Failed to find device in Recovery mode (Timed out). Please run the script again.
                                                                                                                                                    
* Legacy iOS Kit v24.04.15 (3186c32)
* Platform: linux (Debian GNU/Linux 12 (bookworm)) 
qwerty@debian:~/Documents/compiling/Legacy-iOS-Kit$ 
`

It seems like the script is trying to use iOS 10.3.3 for some reason. _Weird._

**Comment by userse31** [comment]
For iOS 8.4.1 (12H321) it works fine.

` *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.04.15 (3186c32)
* Platform: linux (Debian GNU/Linux 12 (bookworm)) 

* Device: iPhone5,3 (n48ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 1386906580299

 > Main Menu > Other Utilities
[Input] Select an option:
1) Send Pwned iBSS                   5) Activation Records               9) Enable disable-bbupdate flag    13) Go Back
2) Get iOS Version                   6) Just Boot                       10) Enable activation-records flag
3) Clear NVRAM                       7) SSH Ramdisk                     11) Enable skip-ibss flag
4) Dump Baseband                     8) Create Custom IPSW              12) (Re-)Install Dependencies
#? 6
* You are about to do a tethered boot.
[Input] Enter build version (eg. 10B329): 12H321
[Log] Checking firmware keys in ../resources/firmware/iPhone5,3/12H321
[Log] iBSS
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 2422a2b76ceb657cbd0e87b706fc48eaf2cea0b0eaaf0c489391b898eb8b4ab4c8eb105e1d6765dc0a95d4611f52b936
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 2422a2b76ceb657cbd0e87b706fc48eaf2cea0b0eaaf0c489391b898eb8b4ab4c8eb105e1d6765dc0a95d4611f52b936
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 2422a2b76ceb657cbd0e87b706fc48eaf2cea0b0eaaf0c489391b898eb8b4ab4c8eb105e1d6765dc0a95d4611f52b936
[Log] iBEC
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 2ebff27e87cd1afa1ecc09e784d3a40d3f00762c070e5e79af3d21224bb828406aa7b0fbaf0053cc92a668d78d454ff0
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 2ebff27e87cd1afa1ecc09e784d3a40d3f00762c070e5e79af3d21224bb828406aa7b0fbaf0053cc92a668d78d454ff0
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 2ebff27e87cd1afa1ecc09e784d3a40d3f00762c070e5e79af3d21224bb828406aa7b0fbaf0053cc92a668d78d454ff0
[Log] DeviceTree
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 50df88dad06d03bfff592b0168b6afee9a8d2f254f3581ce560ca4046002c9db974de59b0da0ab532dd7ef665072d525
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 50df88dad06d03bfff592b0168b6afee9a8d2f254f3581ce560ca4046002c9db974de59b0da0ab532dd7ef665072d525
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 50df88dad06d03bfff592b0168b6afee9a8d2f254f3581ce560ca4046002c9db974de59b0da0ab532dd7ef665072d525
[Log] Kernelcache
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: b051a17748aef1a6a30cc70d40dbbdfc0b60e481a3de2b48fcd57e3ada86c443ae3e4c63d90e367ea97d58f389b29403
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: b051a17748aef1a6a30cc70d40dbbdfc0b60e481a3de2b48fcd57e3ada86c443ae3e4c63d90e367ea97d58f389b29403
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: b051a17748aef1a6a30cc70d40dbbdfc0b60e481a3de2b48fcd57e3ada86c443ae3e4c63d90e367ea97d58f389b29403
error: Cannot open image-file.
[Log] Patch iBSS
main: Starting...
main: iBoot-2261 inputted.
patch_rsa_check: Entering...
find_bl_verify_shsh_generic: Entering...
find_bl_verify_shsh_generic: Found LDR instruction at 0x6510
find_bl_verify_shsh_generic: Found BL verify_shsh at 0x68b6
find_bl_verify_shsh_generic: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x68b6...
patch_rsa_check: Leaving...
main: Writing out patched file to iBSS.patched...
main: Quitting...
[Log] Patch iBEC
main: Starting...
main: iBoot-2261 inputted.
patch_boot_args: Entering...
patch_boot_args: Default boot-args string is at 0x3cfa2
patch_boot_args: boot-args xref is at 0x1c884
patch_boot_args: Applying custom boot-args "-v"
patch_boot_args: Found LDR R1, =boot_args at 0x1c656
patch_boot_args: Found CMP R6, #0 at 0x1c658
patch_boot_args: Found IT EQ/IT NE at 0x1c65c
patch_boot_args: Found MOV R4, R1 at 0x1c65e
patch_boot_args: Found LDR R4, =null_str at 0x1c65a
patch_boot_args: Pointing LDR R4, =null_str to boot-args xref...
patch_boot_args: Leaving...
patch_rsa_check: Entering...
find_bl_verify_shsh_generic: Entering...
find_bl_verify_shsh_generic: Found LDR instruction at 0x1a5d0
find_bl_verify_shsh_generic: Found BL verify_shsh at 0x1ac0a
find_bl_verify_shsh_generic: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x1ac0a...
patch_rsa_check: Leaving...
main: Writing out patched file to iBEC.patched...
main: Quitting...
* Select Y if your device is in pwned iBSS/kDFU mode.
* Select N to place device to pwned DFU mode using ipwndfu/ipwnder.
* Failing to answer correctly will cause "Sending iBEC" to fail.
[Input] Is your device already in pwned iBSS/kDFU mode? (y/N): y
[Log] Pwned iBSS/kDFU mode specified by user.
[Log] Sending iBEC...
[==================================================] 100.0%
[Log] Finding device in Recovery mode...
[Log] Found device in Recovery mode.
[Log] Sending DeviceTree...
[==================================================] 100.0%
[Log] Running devicetree
[Log] Sending KernelCache...
[==================================================] 100.0%
[Log] Device should now boot.

* Save the terminal output now if needed.
* Legacy iOS Kit v24.04.15 (3186c32)
* Platform: linux (Debian GNU/Linux 12 (bookworm)) 

qwerty@debian:~/Documents/compiling/Legacy-iOS-Kit$ 
`

**Comment by userse31** [comment]
Idk if it's because my git pull is somewhat old by now, but when changing "./resources/firmware/iPhone5,3/11D257/url" to contain "http://appldnld.apple.com/iOS7.1/031-4814.20140627.YoE3b/iPhone5,3_7.1.2_11D257_Restore.ipsw" and removing sha1sum, the script uses the correct IPSW and the phone tether boots.

**Comment by LukeZGD** [comment]
This and #471 seem to be caused by remnants from a very old Legacy iOS Kit version, downloading fresh would fix these, but I'll add some checks for these just in case

**Comment by userse31** [comment]
That would make sense!
