### ISSUE TITLE
iPad mini 2 4,4 downgrade to iOS 10.3.3 fails on Ubuntu 22.04.4

### ISSUE THREAD

**Issue by 0wenli** [LukeZGD/Legacy-iOS-Kit#473]
*** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.04.15 (3186c32)
* Platform: linux (Ubuntu 22.04.4 LTS) 

* Device: iPad4,4 (j85ap) in Recovery mode
* iOS Version: ::	BUILD_TAG: iBoot-4513.270.14
* ECID: 7370853337328

* Only select unmodified IPSW for the selection. Do not select custom IPSWs

* Selected IPSW: ../iPad_64bit_10.3.3_14G60_Restore.ipsw

 > Main Menu > Restore/Downgrade > iOS 10.3.3
[Input] Select an option:
1) Select Target IPSW	 3) Start Restore
2) Download Target IPSW	 4) Go Back
#? 3
[Log] Patching iBSS and iBEC...
Archive:  ../iPad_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBSS.ipad4.RELEASE.im4p  
Archive:  ../iPad_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBEC.ipad4.RELEASE.im4p  
Archive:  ../iPad_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBSS.ipad4b.RELEASE.im4p  
Archive:  ../iPad_64bit_10.3.3_14G60_Restore.ipsw
  inflating: iBEC.ipad4b.RELEASE.im4p  
[Log] Pwned iBSS and iBEC saved at: saved/iPad4,4
[Log] Found existing saved 10.3.3 blobs: ../saved/shsh/7370853337328_iPad4,4_j85ap_10.3.3-14G60_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2
* Get ready to enter DFU mode.
* If you already know how to enter DFU mode, you may do so right now before continuing.
[Input] Select Y to continue, N to exit recovery mode (Y/n) y
* Get ready...
02 01 
* Hold TOP and HOME buttons.
10 09 08 07 06 05 04 03 02 01 
* Release TOP button and keep holding HOME button.
08 07 06 05 04 03 02 01 
[Log] Finding device in DFU mode...
[Log] Found device in DFU mode.
[Log] Please read the message below:
* Unfortunately, success rates for checkm8 are very low on Linux.
* Pwning using a Mac or another iOS device using iPwnder Lite are better options.
* For more details, read the "Troubleshooting" wiki page in GitHub
* Troubleshooting links:
    - https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting
    - https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Pwning-Using-Another-iOS-Device
* If pwning gets stuck, you can press Ctrl+C to cancel.
[Log] Placing device to pwnDFU mode using gaster
usb_timeout: 5
usb_abort_timeout_min: 0
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227

After this, it goes no further.
![image](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/167589538/769c1861-bcaa-4e98-b248-4849b38b0e55)

**Comment by 0wenli** [comment]
Well it's still stuck on it and it's been an hour. Any solutions?

**Comment by LukeZGD** [comment]
This is the solution: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Pwning-Using-Another-iOS-Device

**Comment by 0wenli** [comment]
I don't have another iOS device to jailbreak. Also I don't have a lightning to lightning cable

**Comment by 0wenli** [comment]
How to reopen this issue?

**Comment by LukeZGD** [comment]
Why would you? I already provided the solution. It is up to you to buy an iPhone 5 and adapter for downgrading

**Comment by 0wenli** [comment]
Okay waste of time 0/5 stars not actually supported on Linux misleading

**Comment by LukeZGD** [comment]
funny that you say that, but many people have successfully downgraded on linux

**Comment by 0wenli** [comment]
I don’t care about what others achieved I didn’t achieve it so 0/5 stars misleading
