### ISSUE TITLE
add ipad 1 restore to 3.2-4.2.1

### ISSUE THREAD

**Issue by bradycodemaster** [LukeZGD/Legacy-iOS-Kit#474]
![Screenshot_20240427_183852](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/139728745/b9b430c2-cdf2-47c1-befe-3c93449b9b69)
![Screenshot_20240427_183939](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/139728745/6d0c3444-8edf-49fc-a3ff-d504cd13272c)
![Screenshot_20240427_183939](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/139728745/c4f8f2f0-2e0f-4525-8491-a252657031d5)
![Screenshot_20240427_184017](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/139728745/6a595e82-c25d-401d-8b2b-43825df8773b)
heres discord https://discord.gg/WQWDBBYJTb

**Comment by LukeZGD** [comment]
see #467

**Comment by bradycodemaster** [comment]
![image](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/139728745/09c6a8e9-d6de-4f42-bbaf-59e80772a622)

**Comment by LukeZGD** [comment]
Yes. You literally opened an issue for this.
