### ISSUE TITLE
iPhone 4 GSM stuck on Waiting for NAND ( 28 ) for over 15 minutes

### ISSUE THREAD

**Issue by SmallMarbles** [LukeZGD/Legacy-iOS-Kit#475]
OK, So I have this iPhone 4 ( 3,1 ), it recovery loops and I tried restoring it to 7.1.2 using iTunes, nothing worked.

So I try again with other programs and nothing happened

I tried again with Legacy-iOS-Kit and it seems to do something, but then it just gets stuck on Waiting for NAND ( 28 ) and the phone goes back to recovery.

Do I have to wait more, or is it stuck? Thanks.

**Comment by LukeZGD** [comment]
It could be some hardware issue? My guess is the battery being dead, you can check this if the device immediately turns off when unplugged

**Comment by LukeZGD** [comment]
And also, Waiting for NAND takes a few minutes, that is normal. What isnt is good ng back to recovery
