### ISSUE TITLE
Program not finding device in Recovery Mode after pwned DFU

### ISSUE THREAD

**Issue by SmallMarbles** [LukeZGD/Legacy-iOS-Kit#476]
( note: this is the same phone as https://github.com/LukeZGD/Legacy-iOS-Kit/issues/475 )

Basically, if I put it in DFU mode and try to do anything involving pwned DFU ( ex. SSH Ramdisk ) it starts working fine, after everything is sent succesfully the device goes in some black screen recovery mode.

What happens after though, is that Legacy IOS Kit will keep looking for a device in Recovery mode, and claiming that there isn't one after a bit ( despite it being in Recovery mode if I try to open IOS Kit after )

Also note that, after this happens, I have to run the script a few times for the phone to be connected.

I also tried connecting and reconnecting a bit, switching cable, etc.

**Comment by LukeZGD** [comment]
Be more specific, what device, iOS version, what OS, and do you have any log?

**Comment by LukeZGD** [comment]
Have you also tried rebooting, or trying different USB cables/ports? It can also be a hardware issue as I commented in the previous issue
