### ISSUE TITLE
more proof on 3.2 downgrade ipad 1

### ISSUE THREAD

**Issue by bradycodemaster** [LukeZGD/Legacy-iOS-Kit#477]
https://www.reddit.com/r/LegacyJailbreak/comments/1cfrq4m/successfully_downgraded_2_ipads_to_32_untethered/

should work on ipod touch 3 also

![successfully-downgraded-2-ipads-to-3-2-untethered-v0-pnx4jsbmycxc1](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/139728745/44b609b7-9366-497d-bf9b-862bf9389ef0)

**Comment by LukeZGD** [comment]
I'll probably do it eventually , so stop bothering me with this crap already
