### ISSUE TITLE
iPhoneWiki has removed firmware keys??

### ISSUE THREAD

**Issue by LuckyHeroes** [LukeZGD/Legacy-iOS-Kit#478]
I can't futurerestore as iPhoneWiki has removed firmware keys ? Could you help lukezgd 

I've attempted dumping them myself with no luck.

**Comment by LukeZGD** [comment]
What device and version are you trying to restore? Depending on the version, you might need to run wikiproxy: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting#running-wikiproxy
