### ISSUE TITLE
Syntax error from restore.sh on Ubuntu 24.04

### ISSUE THREAD

**Issue by DT-DOE** [LukeZGD/Legacy-iOS-Kit#481]
Hello,

I have 2 errors when I'm executing the restore.sh script:

restore.sh: 61: bash_version: not found
restore.sh: 1121: Syntax error: "(" unexpected (expecting ";;")

Environment: Ubuntu 24.04 x64
Version: Legacy-iOS-Kit_linux_x86_64_v24.05.07

![error](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/98012168/760fe836-9688-45cc-956c-99ccf1410c2b)

**Comment by LukeZGD** [comment]
Cannot reproduce this issue, the script seems to be fine. Check your setup and/or your copy of Legacy iOS Kit. You may also try to git clone the repo and run the script from there

**Comment by YourAdIsHere** [comment]
using `sh restore.sh` will give you that error. try using `bash restore.sh` or `./restore.sh`
