### ISSUE TITLE
downgrade help

### ISSUE THREAD

**Issue by Ran-Xing** [LukeZGD/Legacy-iOS-Kit#482]
I have an iPad Pro 9.7 WiFi
I want to downgrade to 14.x
I can accept no fingerprint, jailbreak, device boot,
Are there any relevant tutorials? I have been following it for half a year

**Comment by LukeZGD** [comment]
See the following tools: [dualra1n](https://github.com/dualra1n/dualra1n), [downr1n](https://github.com/edwin170/downr1n), [Semaphorin](https://github.com/y08wilm/Semaphorin)

Also this gist: https://gist.github.com/LukeZGD/9d781f1b03a69fa46869384a9407a41a
