### ISSUE TITLE
Incorrect identification for 5th gen iPad, cannot find firmware keys

### ISSUE THREAD

**Issue by JomSpoons** [LukeZGD/Legacy-iOS-Kit#484]
I am attempting to restore my iPad (model A1822 & identifier 6,11) to iOS 16.6.1 using blobs, however the process halts with the error `Failed to download firmware keys.` I am using wikiproxy as suggested but it hasn't made a difference. It seems as though Legacy-iOS-Kit is interpreting my device's identifier as 6,1 instead of 6,11 which makes the tool check the wrong Apple Wiki page for firmware keys. I've provided the logs for both restore.sh and wikiproxy.py below. I'd greatly appreciate any assistance. Thank you.

restore.sh: https://pastebin.com/Fv3YshBN
wikiproxy: https://pastebin.com/hQhaVr2V

**Comment by LukeZGD** [comment]
Thanks for letting me know, will be fixing this
