### ISSUE TITLE
How to Save Cydia SHSH Blobs, how does it work 

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#485]
*** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.05.11 (d1b1fe6)
* Platform: macos (10.15.7) 

* Device: iPhone5,1 (n41ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 1609658049423

 > Main Menu
[Input] Select an option:
1) Restore/Downgrade  3) Save SHSH Blobs    5) Exit
2) Jailbreak Device   4) Other Utilities
#? 3

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.05.11 (d1b1fe6)
* Platform: macos (10.15.7) 

* Device: iPhone5,1 (n41ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 1609658049423

 > Main Menu > Save SHSH Blobs
[Input] Select an option:
1) iOS 8.4.1	     3) Cydia Blobs	  5) Go Back
2) Onboard Blobs     4) Convert Raw Dump
#? 3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24120    0 24120    0     0  45768      0 --:--:-- --:--:-- --:--:-- 45681

14G61 failed
14G60 failed
14F89 failed
14E304 failed
14E277 failed
14D27 failed
14C92 failed
14B150 failed
14B100 failed
14B72 failed
14A456 failed
14A403 failed
13G36 failed
13G35 failed
13G34 failed
13F69 failed
13E238 failed
13E237 failed
13E233 failed
13D15 failed
13C75 failed
13B143 failed
13A452 failed
13A404 failed
13A344 failed
12H321 failed
12H143 failed
12F70 failed
12D508 failed
12B466 failed
12B440 failed
12B435 failed
12B411 failed
12A405 failed
12A402 failed
12A365 failed
11D257 failed
11D201 failed
11D167 failed
11B651 failed
11B554a failed
11B511 failed
11A501 failed
11A465 failed
10B350 failed
10B329 failed

* Save the terminal output now if needed.
* Legacy iOS Kit v24.05.11 (d1b1fe6)
* Platform: macos (10.15.7)

**Comment by LukeZGD** [comment]
that just means that your device does not have cydia blobs

more details: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Save-SHSH-blobs-from-Cydia-servers
