### ISSUE TITLE
Error occurred while downupgrading my iPad1 mini from 8.4.1 to 6.3.1

### ISSUE THREAD

**Issue by FlutterW** [LukeZGD/Legacy-iOS-Kit#490]
Sending iBSS (76056 bytes)...
ERROR: Unable to send iBSS component: Unable to upload data to device
ERROR: Unable to send iBSS to device
ERROR: Unable to place device into recovery mode from DFU mode

However, my Mac had installed libusb

**Comment by LukeZGD** [comment]
Needs more context. Are you doing a tethered downgrade to 6.1.3? If yes, do you have an Arduino and USB Host Shield for checkm8-a5?

**Comment by FlutterW** [comment]
> Needs more context. Are you doing a tethered downgrade to 6.1.3? If yes, do you have an Arduino and USB Host Shield for checkm8-a5?

Yes, I'm doing a tethered downgrade to 6.1.3. 
Then it means I have to get an Arduino and USB Host Shield for this downgrading? Only an Mac will not be able to downgrade?

**Comment by LukeZGD** [comment]
Yes, you need an Arduino and USB Host Shield for tether downgrading A5 devices in this case that checkm8-a5 needs to be used. Here's a good place to start for this: https://www.youtube.com/watch?v=efAxIXieCLM
