### ISSUE TITLE
After entering DFU mode, my iPhone5 cannot exit DFU mode, and erros occurred while restoring

### ISSUE THREAD

**Issue by FlutterW** [LukeZGD/Legacy-iOS-Kit#491]
*** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.05.12 (9a3f574)
* Platform: macos (14.5) 

* Device: iPhone5,2 (n42ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 2384983055755

* Only select unmodified IPSW for the selection. Do not select custom IPSWs

* Selected IPSW: ../iPhone_4.0_32bit_10.3.4_14G61_Restore.ipsw

* This restore will use 10.3.4 baseband

 > Main Menu > Restore/Downgrade > Latest iOS (10.3.4)
[Input] Select an option:
1) Select Target IPSW	 3) Start Restore
2) Download Target IPSW	 4) Go Back
#? 3
[Log] Found existing saved 10.3.4 blobs: ../saved/shsh/2384983055755_iPhone5,2_n42ap_10.3.4-14G61_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2
[Log] Extracting IPSW: ../iPhone_4.0_32bit_10.3.4_14G61_Restore.ipsw
Archive:  ../iPhone_4.0_32bit_10.3.4_14G61_Restore.ipsw
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/058-74968-065.dmg  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/._058-74968-065.dmg  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/058-75249-065.dmg  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/058-75393-065.dmg  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/BuildManifest.plist  
   creating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/
   creating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/applelogo@2x~iphone.s5l8950x.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/batterycharging0@2x~iphone.s5l8950x.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/batterycharging1@2x~iphone.s5l8950x.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/batteryfull@2x~iphone.s5l8950x.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/batterylow0@2x~iphone.s5l8950x.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/batterylow1@2x~iphone.s5l8950x.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/DeviceTree.n41ap.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/DeviceTree.n42ap.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/DeviceTree.n48ap.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/DeviceTree.n49ap.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8950x.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/iBoot.iphone5.RELEASE.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/iBoot.iphone5b.RELEASE.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/LLB.iphone5.RELEASE.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/LLB.iphone5b.RELEASE.img3  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8950x.img3  
   creating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/dfu/
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/dfu/iBEC.iphone5.RELEASE.dfu  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/dfu/iBEC.iphone5b.RELEASE.dfu  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/dfu/iBSS.iphone5.RELEASE.dfu  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/dfu/iBSS.iphone5b.RELEASE.dfu  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/Mav5-11.80.00.Release.bbfw  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/Mav5-11.80.00.Release.plist  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/Mav7Mav8-7.60.00.Release.bbfw  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/Mav7Mav8-7.60.00.Release.plist  
   creating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/usr/
   creating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/usr/local/
   creating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Firmware/usr/local/standalone/
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/kernelcache.release.iphone5  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/kernelcache.release.iphone5b  
  inflating: ../iPhone_4.0_32bit_10.3.4_14G61_Restore/Restore.plist  
[Log] Running idevicerestore with command: ../bin/macos/idevicerestore -e "../iPhone_4.0_32bit_10.3.4_14G61_Restore.ipsw"
Found device in DFU mode
Found ECID 2384983055755
Identified device as n42ap, iPhone5,2
Extracting BuildManifest from IPSW
Product Version: 10.3.4
Product Build: 14G61 Major: 14
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Getting ApNonce in dfu mode... 4f e4 85 fd 0c 9a 99 6f 98 38 db 2f 0e 4d 27 d0 48 67 46 6f 
Trying to fetch new SHSH blob
Getting SepNonce in dfu mode... 
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
Using cached filesystem from '../iPhone_4.0_32bit_10.3.4_14G61_Restore/058-74968-065.dmg'
Extracting iBSS.iphone5.RELEASE.dfu...
Personalizing IMG3 component iBSS...
reconstructed size: 158042
Sending iBSS (158042 bytes)...
[==================================================] 100.0%
Nonce: 4f e4 85 fd 0c 9a 99 6f 98 38 db 2f 0e 4d 27 d0 48 67 46 6f 
Extracting iBEC.iphone5.RELEASE.dfu...
Not personalizing component iBEC...
Sending iBEC (306124 bytes)...
[==================================================] 100.0%
INFO: device serial number is C7GN25K3DTWF
Getting ApNonce in recovery mode... 4f e4 85 fd 0c 9a 99 6f 98 38 db 2f 0e 4d 27 d0 48 67 46 6f 
Sending APTicket (2760 bytes)
Recovery Mode Environment:
iBoot build-version=iBoot-3406.60.10
iBoot build-style=RELEASE
ramdisk-size=0x10000000
Extracting 058-75249-065.dmg...
Not personalizing component RestoreRamDisk...
Sending RestoreRamDisk (24744076 bytes)...
Extracting DeviceTree.n42ap.img3...
Not personalizing component RestoreDeviceTree...
Sending RestoreDeviceTree (88332 bytes)...
Extracting kernelcache.release.iphone5...
Not personalizing component RestoreKernelCache...
Sending RestoreKernelCache (11658060 bytes)...
About to restore device... 
Waiting for device...
Device b56a29a3dfdf691da338c4df4a68e2e09c3a0585 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 14
Device b56a29a3dfdf691da338c4df4a68e2e09c3a0585 has successfully entered restore mode
Hardware Information:
BoardID: 2
ChipID: 35152
UniqueChipID: 2384983055755
ProductionMode: true
Previous restore exit status: 0x100
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Unmounting filesystems (29)
Unmounting filesystems (29)
Creating partition map (11)
Creating filesystem (12)
Creating filesystem (12)
About to send filesystem...
Connected to ASR
Validating the filesystem
Filesystem validated
Sending filesystem now...
[=========                                         ]  17.0%ERROR: Unable to send data to ASR. Sent 0 of 1450 bytes.
ERROR: Unable to send filesystem payload
ERROR: Unable to send payload to ASR
ERROR: Unable to send filesystem
ERROR: Unable to successfully restore device
ERROR: Unable to restore device
* For device activation, go to: Other Utilities -> Attempt Activation

* Save the terminal output now if needed.
* Legacy iOS Kit v24.05.12 (9a3f574)
* Platform: macos (14.5)

**Comment by LukeZGD** [comment]
USB issue again, refer to my previous comment

**Comment by FlutterW** [comment]
But I use the same cable which I used to downupgrade my iPad successfully.

**Comment by LukeZGD** [comment]
The error in the log indicates USB disconnection. This is not an issue with Legacy iOS Kit and is out of my control
