### ISSUE TITLE
problem in macOS

### ISSUE THREAD

**Issue by mohame782** [LukeZGD/Legacy-iOS-Kit#492]
the problem is that when install the file restore.sh it says jb is downloaded from safari and didn't give me an option just to delete the kb I think the jb is required so that ur tool to work.. I need a fix for this issue please
![Uploading Screen Shot 2024-05-27 at 6.20.31 PM.png…]()

**Comment by LukeZGD** [comment]
Your screenshot didnt get uploaded

What are you trying to do anyway
