### ISSUE TITLE
iPhone 2,1 stuck in DFU on non-latest firmware

### ISSUE THREAD

**Issue by trwy7** [LukeZGD/Legacy-iOS-Kit#495]
I attempted to downgrade my iPhone 3GS to ios 3.1.3 from 4.3.3, but it always gets stuck in DFU mode after restore
[may29.log](https://github.com/LukeZGD/Legacy-iOS-Kit/files/15490087/may29.log)

**Comment by LukeZGD** [comment]
other utilities -> install alloc8
