### ISSUE TITLE
Add possibility to keep data when downgrading iOS version

### ISSUE THREAD

**Issue by ro1605he** [LukeZGD/Legacy-iOS-Kit#498]
### Discussed in https://github.com/LukeZGD/Legacy-iOS-Kit/discussions/496

<div type='discussions-op-text'>

<sup>Originally posted by **ro1605he** June  1, 2024</sup>
@LukeZGD (or anyone who knows the answers to my questions!)  

I have an old iPhone 5 lying around that due to “storage full” no longer boots (Apple logo remains visible). I tried SSH Ramdisk, but have a feeling this won't work because of this either. Is it possible to use the script to downgrade from iOS (was running on 8.4.1 at the time of the crash) to iOS 7 without losing data? Or, when I choose option 1 (downgrade to 8.4.1) in the script, will it re-install this version without losing data? Or is it possible to add this feature?

Also, do you know if an iDevice gets low level formatted when doing a restore? Otherwise my last option could be to try a restore and recover deleted files afterwards?</div>

**Comment by LukeZGD** [comment]
Legacy iOS Kit will never support keeping data for restores, this will cause a lot of breakage especially for downgrading. This can be seen especially when users do the atrocious "plist method" for downgrading to iOS 8. After the downgrade, many features just break and stop working, requiring an "Erase All Content and Settings." At that point, just do a full clean restore, which is what Legacy iOS Kit does.

Keeping data on restore is called an "update restore" and this is something that cannot be done when the storage of the device that is near full or is full, it will just fail. One notable case of this was back in the iOS 15 release with 16GB devices being unable to update to it, requiring users to do a backup, restore to iOS 15 using iTunes/Finder, then restore their backup afterwards.

I'll try to ask around in the LegacyJailbreak Discord about the picture you posted in #497 if it is a hardware issue

**Comment by LukeZGD** [comment]
after some discussion, the picture really does seem like a board issue especially with a panic when booting sshrd as one of the symptoms.. do check for other symptoms like this:

- unable to enter recovery
- unable to boot ibec for blob dump
- device boots to apple logo and shuts off/fades

**Comment by ro1605he** [comment]
@LukeZGD thanks! I'm able to enter recovery and DFU, no problem. Also the device boots to the Apple logo, but does not shut off or fade.

I get some different errors on the black iPhone screen everytime I try to boot the SSH Ramdisk: "000054.939508 AppleBasebandN41::initialize: Could not find mux function" is another one of them. Any ideas here...?

**Comment by LukeZGD** [comment]
im pretty sure the data partition has some encryption, data recovery after restoring is not possible afaik, but it could be different with these old devices so im not entirely sure

if you havent tried this yet, try to do a "just boot" with a build 12H321 to see the verbose output of it booting

if all else fails, you might need to go to a data recovery service as a last resort

**Comment by ro1605he** [comment]
@LukeZGD  thanks for the tip. I didn't try that, but just did. See output below. Unfortunately I still get a black screen on the iPhone with some logging. Please see attached photo.

![Just Boot 12H321](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/169261485/550d4063-b8b5-4ac2-9173-237792bdaa84)

regarding encryption, is it at all possible to recover data via an SSH Ramdisk? On an old iPod (iOS 4), I managed to do this. But I haven't tried it before on a device running iOS 8 or 9.

From which device/iOS version did Apple start using encryption? I cannot find this clearly. This will then determine if the last option I have (restore and then recover data) might work. But hopefully there are other options to try first?

```
*** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.06.02 (acb9532)
* Platform: linux (Linux Mint 21.3) 

* Device: iPhone5,2 (n42ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 2270545636621

 > Main Menu > Other Utilities
[Input] Select an option:
1) Send Pwned iBSS		     8) Create Custom IPSW
2) Get iOS Version		     9) Enable disable-bbupdate flag
3) Clear NVRAM			    10) Enable activation-records flag
4) Dump Baseband		    11) Enable skip-ibss flag
5) Activation Records		    12) (Re-)Install Dependencies
6) Just Boot			    13) Go Back
7) SSH Ramdisk
#? 6
* You are about to do a tethered boot.
[Input] Enter build version (eg. 10B329): 12H321
[Log] Checking firmware keys in ../resources/firmware/iPhone5,2/12H321
[Log] Checking URL in ../resources/firmware/iPhone5,2/12H321/url
[Log] iBSS
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 997ef353c128ea273399bd25c12d2d61608c1226b5457bd39821ab38d41cecfbda216fcac181f1207fbf76823a125a10
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 997ef353c128ea273399bd25c12d2d61608c1226b5457bd39821ab38d41cecfbda216fcac181f1207fbf76823a125a10
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 997ef353c128ea273399bd25c12d2d61608c1226b5457bd39821ab38d41cecfbda216fcac181f1207fbf76823a125a10
[Log] iBEC
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ba72b6fb5c5d068d103455b25aebcb125d0ceefe85fb3483f97c0cf0b584774a249613176fe25c1884478d8d1b20d92f
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ba72b6fb5c5d068d103455b25aebcb125d0ceefe85fb3483f97c0cf0b584774a249613176fe25c1884478d8d1b20d92f
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: ba72b6fb5c5d068d103455b25aebcb125d0ceefe85fb3483f97c0cf0b584774a249613176fe25c1884478d8d1b20d92f
[Log] DeviceTree
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 4f542e8bd12274fd69b7da5e593f7f024d4cd1ca51a47b2fa2de7d8fd69ce72f78277ce422afb4215650c35ec27ea7c1
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 4f542e8bd12274fd69b7da5e593f7f024d4cd1ca51a47b2fa2de7d8fd69ce72f78277ce422afb4215650c35ec27ea7c1
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 4f542e8bd12274fd69b7da5e593f7f024d4cd1ca51a47b2fa2de7d8fd69ce72f78277ce422afb4215650c35ec27ea7c1
[Log] Kernelcache
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 12d19891a9fc39018fe76ac11ce218127df30bdea042adcf0b1f2add4f99791d3945f93e8585afe7286bffcf09fded83
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 12d19891a9fc39018fe76ac11ce218127df30bdea042adcf0b1f2add4f99791d3945f93e8585afe7286bffcf09fded83
/home/runner/work/daibutsuCFW/daibutsuCFW/src/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 12d19891a9fc39018fe76ac11ce218127df30bdea042adcf0b1f2add4f99791d3945f93e8585afe7286bffcf09fded83
[Log] Patch iBSS
main: Starting...
main: iBoot-2261 inputted.
patch_rsa_check: Entering...
find_bl_verify_shsh_generic: Entering...
find_bl_verify_shsh_generic: Found LDR instruction at 0x634c
find_bl_verify_shsh_generic: Found BL verify_shsh at 0x66f2
find_bl_verify_shsh_generic: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x66f2...
patch_rsa_check: Leaving...
main: Writing out patched file to iBSS.patched...
main: Quitting...
[Log] Patch iBEC
main: Starting...
main: iBoot-2261 inputted.
patch_boot_args: Entering...
patch_boot_args: Default boot-args string is at 0x3c88f
patch_boot_args: boot-args xref is at 0x1c4e8
patch_boot_args: Applying custom boot-args "-v pio-error=0"
patch_boot_args: Found LDR R1, =boot_args at 0x1c2ba
patch_boot_args: Found CMP R6, #0 at 0x1c2bc
patch_boot_args: Found IT EQ/IT NE at 0x1c2c0
patch_boot_args: Found MOV R4, R1 at 0x1c2c2
patch_boot_args: Found LDR R4, =null_str at 0x1c2be
patch_boot_args: Pointing LDR R4, =null_str to boot-args xref...
patch_boot_args: Leaving...
patch_rsa_check: Entering...
find_bl_verify_shsh_generic: Entering...
find_bl_verify_shsh_generic: Found LDR instruction at 0x1a234
find_bl_verify_shsh_generic: Found BL verify_shsh at 0x1a86e
find_bl_verify_shsh_generic: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x1a86e...
patch_rsa_check: Leaving...
main: Writing out patched file to iBEC.patched...
main: Quitting...
* Select Y if your device is in pwned iBSS/kDFU mode.
* Select N to place device to pwned DFU mode using ipwndfu/ipwnder.
* Failing to answer correctly will cause "Sending iBEC" to fail.
[Input] Is your device already in pwned iBSS/kDFU mode? (y/N): y
[Log] Pwned iBSS/kDFU mode specified by user.
[Log] Sending iBEC...
[==================================================] 100.0%
[Log] Finding device in Recovery mode...
[Log] Found device in Recovery mode.
[Log] Sending DeviceTree...
[==================================================] 100.0%
[Log] Running devicetree
[Log] Sending KernelCache...
[==================================================] 100.0%
[Log] Device should now boot.

* Save the terminal output now if needed.
* Legacy iOS Kit v24.06.02 (acb9532)
* Platform: linux (Linux Mint 21.3) 

```

**Comment by LukeZGD** [comment]
other than people in the jailbreak/legacyjailbreak community, i don't really know who to contact for this kind of data recovery stuff

**Comment by ro1605he** [comment]
@LukeZGD Will do. What would you recommend posting there, knowing what I've already tried?
