### ISSUE TITLE
3GS restore error?

### ISSUE THREAD

**Issue by horvath-matyas** [LukeZGD/Legacy-iOS-Kit#499]
Hi! I got this 3GS recently, it was in recovery mode, when I tried to restore it, it just freezes at this point, the phone shows the Apple logo and an empty status bar. Maybe its not your programs fault, but I thought it worths an asking.
[3GS error.log](https://github.com/user-attachments/files/15539560/3GS.error.log)

**Comment by LukeZGD** [comment]
Older devices do get stuck in "Waiting for NAND" for some time, just wait for a few minutes to get past it
