### ISSUE TITLE
Hey! I've got a question

### ISSUE THREAD

**Issue by 1G0REX** [LukeZGD/Legacy-iOS-Kit#500]
so I wanted to ask how to downgrade on iPhone 5c because I have tried everything and nothing.  Either a black screen or it simply won't start.

**Comment by LukeZGD** [comment]
If you don't have blobs, you can only do tethered downgrades (by selecting Restore/Downgrade -> Other (Tethered)) to your device, which requires a computer to boot every time (by going to Other Utilities -> Just Boot)

**Comment by 1G0REX** [comment]
only I've done that before and nothing.  It said that it failed to restore
