### ISSUE TITLE
Add CFW flashing option

### ISSUE THREAD

**Issue by AZGDO** [LukeZGD/Legacy-iOS-Kit#505]
ok, im now testing out ios 9.3.5 cfw which i create myself, but for some reason i cant flash them. I try to idevicerestore -ew {ipsw here} in pwndfu mode, but it cant even boot recovery mode. Maybe i did something wrong? ive only modified rootfs(decrypted, make some changes, encrypted, put back in ipsw). i also tried modifying ibss via iboot32patcher within bin folder, still no success. It will be good to have restoring cfw feature.

**Comment by LukeZGD** [comment]
i wont be adding this since legacy ios kit automatically handles the creation and restore of custom ipsws needed appropriate to what the user selects in the restore/downgrade option
