### ISSUE TITLE
Cydia jailbroken using Legacy iOS Kit starts bootlooping iPod

### ISSUE THREAD

**Issue by cozumii8364** [LukeZGD/Legacy-iOS-Kit#507]
I jailbroke an iPod Touch 4th generation on iOS 6.1.3 using the legacy iOS kit. Cydia installed and when I opened it it updated the filesystem (or whatever it usually says, I don’t remember) and after that, it resprung the device. After that, when I opened cydia, it put the device into a boot loop, in which the device shows the apple logo, a white screen, then tries to boot again. Is there something to fix it?

**Comment by cozumii8364** [comment]
I’ve jailbroken devices before, and if they respring out of nowhere, it says that Springboard has crashed and that this is the substrate safe mode saving the device from boot looping and whatnot. I think that’s what’s happening here, Springboard crashing.

**Comment by LukeZGD** [comment]
the normal flow goes like this: open cydia for the first time -> preparing filesystem -> respring -> open cydia again -> proceed as normal

do you mean that you can't open cydia after the respring here? i have never heard or seen such a case and would like to see a video about it

**Comment by cozumii8364** [comment]
Can’t even open the device. It’s just bootlooping. I can send you a video when I can.

**Comment by cozumii8364** [comment]
If you’re wondering what I jailbroke it with, it’s Linux Mint 21.3

**Comment by LukeZGD** [comment]
oh, then the blame goes to the p0sixspwn untether. that is normal for this untether in particular, try to wait it out for a few minutes and it should eventually boot (this is the case on my ipad 2 when i observed it)

**Comment by cozumii8364** [comment]
alright thanks!
