### ISSUE TITLE
Incorrect device model detection

### ISSUE THREAD

**Issue by notdevcody** [LukeZGD/Legacy-iOS-Kit#515]
I've got two iPhone 4 devices. On the backplates of both of them the model is A1332, which the ipsw device finder recognizes as iPhone 4 (GSM). The script however outputs the following:
```
* Device: iPhone3,2 (n90bap) in Normal mode
* iOS Version: 7.1.2 (11D257)
```
The iOS version is correct. Is there anything I'm missing here? Are there any other ways to check the model, just to be sure?

**Comment by LukeZGD** [comment]
8GB device?

**Comment by LukeZGD** [comment]
Then the info is correct, you have an iPhone3,2 which is not supported by powdersn0w downgrades
