### ISSUE TITLE
[QUESTION] How to un-clear NVRAM?

### ISSUE THREAD

**Issue by nmka55** [LukeZGD/Legacy-iOS-Kit#516]
Sorry, I didn't know where to ask. 
I was SSH ramdisking ipad Mini 1 (ipad 2,6) and wrote nvram -c just from curiousity. And when I reboot_bak the device is stuck at apple logo. 

Can i undo this? Help.

**Comment by LukeZGD** [comment]
nvram -c won't do anything to that since it's not downgraded with powdersn0w or anything. Is it jailbroken with EtasonJB by chance, or whatever other jailbreak it currently has? That might be the culprit

**Comment by nmka55** [comment]
yeah it is jailbroken. 

idk which one, I used the 2nd option from tool.

**Comment by nmka55** [comment]
Thank you for the reply. Maybe I will look into reverting jailbreak then. This is totally do-able from SSH ramdisk right...?

**Comment by LukeZGD** [comment]
reverting the jailbreak cannot be easily done on ios versions below 11.3. you might need to restore

**Comment by nmka55** [comment]
ok, got it,. Thanks
