### ISSUE TITLE
failed to download firmware keys

### ISSUE THREAD

**Issue by rav000** [LukeZGD/Legacy-iOS-Kit#524]
trying to restore to 15.8 with blobs and this happens
![image](https://github.com/LukeZGD/Legacy-iOS-Kit/assets/97004117/c6344014-07b7-4340-8176-ee718a90faee)

**Comment by LukeZGD** [comment]
Run my fork of wikiproxy in another terminal window before running the restore: https://github.com/LukeZGD/wikiproxy
