### ISSUE TITLE
Extremly slow after jailbreaking with Ramdisk method

### ISSUE THREAD

**Issue by averagenokiauser** [LukeZGD/Legacy-iOS-Kit#528]
Hello, i have jailbroken an iPhone 4 with iOS 7.1.2 successfully, but the phone is now really slow and keeps freezing. For some reason i also got a pop up that my storage is full but i have 12GB left. Rebooting did not help.

**Comment by LukeZGD** [comment]
The culprit is Pangu, see my comment here https://github.com/LukeZGD/Legacy-iOS-Kit/issues/512#issuecomment-2183899962

Solution is to restore with jailbreak option enabled
