### ISSUE TITLE
iPad 1 Charging Very Slowly After iOS 4 Untethered Downgrade And Saying "Not Charging"

### ISSUE THREAD

**Issue by BulbasaurGreen** [LukeZGD/Legacy-iOS-Kit#530]
So, I Downgraded My iPad 1 To iOS 4.3.2 (Untethered) Using Legacy iOS Kit, And Now The Device Will Always Say Not Charging, And Also Really Slow
Specific Device Specs: iPad1,1, Cellular, 32GB, If You Need Any Other Info Message Me, I'll Update If I Find Anything Else

**Comment by LukeZGD** [comment]
I don't think this issue has anything to do with the downgrade

Check your charging brick, make sure it has enough wattage to charge iPads, typically around 10 or 12W
