### ISSUE TITLE
Feature Request - Apple TV Support

### ISSUE THREAD

**Issue by CtrliPhones** [LukeZGD/Legacy-iOS-Kit#534]
I'd like to see basic functionality (Notably SSH Ramdisks and app installation) for Apple TV 2nd, 3rd, and 4th generation, at least in some kind of experimental form, as not much has been done lately with the older Apple TV models.
Obviously, not everything would be supported, however I'd love to see it!

**Comment by LukeZGD** [comment]
as much as i would like that to happen, it probably wont due to the difficulty of obtaining the devices for testing

maybe someday
