### ISSUE TITLE
[Bug] Script doesn't seem to check properly when the package installation fails

### ISSUE THREAD

**Issue by veast-network** [LukeZGD/Legacy-iOS-Kit#535]
I am on Arch Linux.
On first-run, it _attempted_ to install dependencies from my package manager but it seemed to fail due to a dependency mismatch (I had to update my system fully). But it seems as if, on pacman, it doesn't check if the installation properly succeeds and the script continues as if everything is normal. I had to remove the firstrun file to install the dependencies normally.

**Comment by LukeZGD** [comment]
ill just fix the pacman command by doing a full `-Syu` instead of a partial `-Sy`
