### ISSUE TITLE
Could not connect to lockdownd: SSL error (-5)

### ISSUE THREAD

**Issue by PierreSachot** [LukeZGD/Legacy-iOS-Kit#537]
I did use this tool since some time to restore my iPhones 2G and thanks a lot for this amazing tool!
I was under v24.07.16 and it asked me to update. I did so and now I get this error during the iPhone scan procedure: 
```bash
 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.07.23 (cb7a466)
* Enter your user password when prompted
[Log] Running on platform: linux (Ubuntu 22.04.4 LTS)
[Log] Checking Internet connection...
[Log] Checking for updates...
[Log] Finding device in Normal mode...
* If it gets stuck here, try to restart your PC
[Log] Getting device info...
ERROR: Could not connect to lockdownd: SSL error (-5)
[Error] Unrecognized device . Enter the device type properly.

* Legacy iOS Kit v24.07.23 (cb7a466)
* Platform: linux (Ubuntu 22.04.4 LTS) 
```

Can you please explain to me what is this error: `ERROR: Could not connect to lockdownd: SSL error (-5)` is about?

Regards,
Pierre

**Comment by LukeZGD** [comment]
What iOS version is your iPhone curently on? If it's iOS 1, that will be a problem, it must be on iOS 2 or newer to get detected properly

**Comment by PierreSachot** [comment]
Ok, to be honest this was the thing I wanted to know. I currently don’t know which version of iOS is running on this iPhone. 

Maybe my only possibility is to restart my old windows xp in order to detect it under iTunes 7.

**Comment by PierreSachot** [comment]
I thought about it and I believe that I am at least under iOS 2 as the activation screen is different between iOS 1 and 2.
Here is my activation screen:
![IMG_4793](https://github.com/user-attachments/assets/762463da-6b97-4979-b542-4071035c0b9d)

as you can see I have the usb port displayed and not the 32 pins connector as under iOS 1

**Comment by PierreSachot** [comment]
After starting restore on iTunes 7 under windows xp, it failed with an error code (1). I retried and I got an error code (5). After this iPhone was stucked in recovery mode (white screen)
After this I came back on my Linux and used your program which perfectly detected the iPhone and restoration under iOS 3.1.3 was perfect.
Thanks a lot!

**Comment by LukeZGD** [comment]
Good to know

For recovery and DFU, iOS version doesnt matter

For normal mode, looks like iOS 3 or newer is needed
