### ISSUE TITLE
Can't download firmware keys - 500 Internal Server Error

### ISSUE THREAD

**Issue by MishuPwns** [LukeZGD/Legacy-iOS-Kit#538]
iPad Pro 9.7 6,3 
16.7.8 --> 16.7.1 with shsh blobs

wikiproxy log:

INFO:     Started server process [2994]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO:     127.0.0.1:49777 - "GET /firmware/iPad6%2C3/20H30 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host theapplewiki.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

Legacy iOS Kit log:

usb_timeout: 5
usb_abort_timeout_min: 0
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[Log] Checking firmware keys in ../resources/firmware/iPad6,3/20H30
[Log] Getting firmware keys for iPad6,3-20H30
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  256k    0  256k    0     0   282k      0 --:--:-- --:--:-- --:--:--  282k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0     51      0 --:--:-- --:--:-- --:--:--    51
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0     22      0 --:--:-- --:--:-- --:--:--    22
[Error] Failed to download firmware keys.
* You may need to run wikiproxy to get firmware keys.
* For more details, go to the "Troubleshooting" wiki page in GitHub.
* Troubleshooting link: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting#running-wikiproxy
* Legacy iOS Kit v24.07.26 (26f26b0)
* Platform: macos (12.7.5)

**Comment by LukeZGD** [comment]
There are no firmware keys for that device/version in the apple wiki. You have these options:

- Set nonce generator manually and disable the pwned restore option
- Get the firmware keys manually (idk how) and upload them to the apple wiki
