### ISSUE TITLE
Cydia Crashes after Jailbreaking iPad 1 iOS 3.2.2

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#539]
[Input] Do you also want to jailbreak it now? (Y/n) Y
[Log] Sending greenpois0n/iPad1,1_7B500.tar
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
[Log] Extracting greenpois0n/iPad1,1_7B500.tar
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
tar: /mnt1/greenpois0n/iPad1,1_7B500.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rm: /mnt1/greenpois0n/iPad1,1_7B500.tar: No such file or directory
[Log] Mounting data partition
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
Waiting for disks...
/dev/disk0s1 already mounted on /mnt1
Mounting /dev/disk0s2s1 on /mnt1/private/var
[Log] fstab
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
[Log] Sending cydiasubstrate.tar
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
[Log] Extracting cydiasubstrate.tar
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
./
./private/
./private/var/
./private/var/root/
./private/var/root/Media/
./private/var/root/Media/Cydia/
./private/var/root/Media/Cydia/AutoInstall/
./private/var/root/Media/Cydia/AutoInstall/com.saurik.substrate.safemode_fix.deb
./private/var/root/Media/Cydia/AutoInstall/mobilesubstrate_fix.deb
[Log] Sending cydiahttpatch.tar
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
[Log] Extracting cydiahttpatch.tar
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
./
./private/
./private/etc/
./private/etc/apt/
./private/etc/apt/sources.list.d/
./private/etc/apt/sources.list.d/ipg.list
./private/var/
./private/var/root/
./private/var/root/Media/
./private/var/root/Media/Cydia/
./private/var/root/Media/Cydia/AutoInstall/
./private/var/root/Media/Cydia/AutoInstall/cydiahttpatch-1.0.deb
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
[Log] Done, your device should reboot now

* Save the terminal output now if needed.
* Legacy iOS Kit v24.07.27 (ca8d636)
* Platform: macos (11.7.10)

**Comment by Jefferyat** [comment]
Thank you so much for your awesome tool again!

**Comment by LukeZGD** [comment]
oops, ill fix this rq
