### ISSUE TITLE
9.3.5 -> 8.4.1 regression between  24.7.29 and  24.07.35?

### ISSUE THREAD

**Issue by nn-afly** [LukeZGD/Legacy-iOS-Kit#540]
MacOs catalina (10.15.7)
ipad 3/32 bit 

Downloaded  legacy-ios-kit 24.7.29 this morning and went 9.3.5 -> 8.4.1 (jb) no problem at all. Later used leg-ios-kit to go back to 9.3.5

Now using leg-ios-kit 24.07.35 (forced to upgrade) and trying to 9.3.5 -> 8.4.1 (jb) again. Problem I'm having is that ios-kit nails the current ios as 9.3.5 but then tries to run operation as if it was 8.4.1 (jb).  talks about cydia etc and then fails trying to find a device in dfu. Screeny attached

Done fresh install of 24.07.35 with same result. Screenshot is a second run through for brevity

![image](https://github.com/user-attachments/assets/c1568b7b-4c66-4a20-8b28-5f4ef3be837f)

**Comment by LukeZGD** [comment]
kdfu has always been required, that has not changed

read the wiki pages for more info
