### ISSUE TITLE
Custom bootlogo

### ISSUE THREAD

**Issue by KittenPro** [LukeZGD/Legacy-iOS-Kit#546]
i have iphone 3,1. i downgraded phone to ios 5.1.1 and selected custom bootlogo with resolution 320x480, everything is good, but my bootlogo is empty/black. how can i install custom bootlogo correctly? image is colorful, in png format.

**Comment by LukeZGD** [comment]
yeah i never really figured this one out, even with a 3gs i cant seem to get it working when the conversion seems successful. there might be something to be done with the png that i dont know about, idk
