### ISSUE TITLE
Help with powdersn0w

### ISSUE THREAD

**Issue by yoyo2306** [LukeZGD/Legacy-iOS-Kit#547]
Hello! Could you tell me what is the code of powdersn0w v3.x self-made firmware? Also, the code of powdersn0w_v2.0b3 self-made firmware before is: ./ipsw <input.ipsw> <output.ipsw> -memory -bbupdate -useDRA <base.ipsw> But now this code is also unusable.

I know these are easy to solve in your Legacy-iOS-Kit, I just want to figure out what is the code of powdersn0w v3.x self-made firmware, thank you very much!

**Comment by LukeZGD** [comment]
repo is linked in the readme
