### ISSUE TITLE
iPad 2,2 Not restoring when trying to restore with FourThree.

### ISSUE THREAD

**Issue by JakeGithub2015** [LukeZGD/Legacy-iOS-Kit#551]
So basically, the iPad 2,2 does not even restore on FourThree restore process and this is what it shows:
![Screenshot from 2024-08-01 22-01-23](https://github.com/user-attachments/assets/28c8566a-656f-4f4d-b90c-d10f7ef2d48d)

**Comment by LukeZGD** [comment]
Delete the existing custom IPSW, redo step 1, and get the entire terminal output/log

**Comment by JakeGithub2015** [comment]
Ok, thank you!

**Comment by JakeGithub2015** [comment]
I have done it, thank u LukeZGD!

**Comment by LukeZGD** [comment]
assuming the issue is solved, will be closing this now
