### ISSUE TITLE
iPad2,1 4.3.3 restore problem

### ISSUE THREAD

**Issue by sow1nd** [LukeZGD/Legacy-iOS-Kit#552]
Today I used kit to dump my iPad 2 4.3.3 on-board SHSH blob with 4.3.3 IPSW file (use checkm8-A5).
restore was successful and no error But iPad 2 was stuck recovery mode and can't exit .
Can you help me? thanks  My SHSH file is broken？

**Comment by LukeZGD** [comment]
Yes it could be bad SHSH blobs, you can upload the file here for checking

**Comment by sow1nd** [comment]
[SHSH.zip](https://github.com/user-attachments/files/16477803/SHSH.zip)
here thanks

**Comment by LukeZGD** [comment]
![Screenshot_20240803_104450](https://github.com/user-attachments/assets/fe25e28b-a071-4c73-b354-eff4c112d6ed)

Unfortunately yes your blob is broken, not sure if there is anything that can be done about it
