### ISSUE TITLE
Add Support for these 

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#553]
Jailbreaks for A5 iOS 8.0-iOS 8.2 via SSH Ramdisk

Create Untether for Kok3shi9 KokeshiX Socket and MeredianFix and TNS Sockport JB's or Even P0laris 

Add Jailbreak Support for iOS 2.1.1-2.2.1 on iPod Touch 2G

Add Jailbreak Support for iOS 2.0-3.1.2 and iOS 4.0.x on iPhone 2G/iPod Touch 1G/iPhone 3G/iPod Touch 2G

Add Tethered Downgrade Support for 64 bit Since Semaphorin is Discontinued

Add Powdersn0w Downgrade Support for iPad3,1 and iPad3,3 with iOS 7.1.x blobs with this ramdisk as well as iPod Touch 2G MC since you cant downgrade to iOS 4.0-4.0.2 or iOS 3.1.1 or 3.1.2 https://github.com/Ralph0045/iloader

Add Powdersn0w Support for iPad 3 with iOS 7.0.x blobs as well

**Comment by Jefferyat** [comment]
Add Jailbreak Support for 64 bit iOS 7.0-7.1.2

**Comment by LukeZGD** [comment]
cool list, but no, i wont be doing any of these, youre asking for way too much from me
