### ISSUE TITLE
Support for activation locked devices

### ISSUE THREAD

**Issue by Emiral46** [LukeZGD/Legacy-iOS-Kit#558]
Hi, 

I wonder is it possible for legacy ios kit to have support for bypassing icloud activation lock on A4 to A11 devices using ssh ramdisk method on devices lower than ios 12 and checkra1n/palera1n method on devices that are running ios 12 or higher? Is it also possible to retain GSM or MEID signal after bypassing activation lock? If yes, please also support GSM or MEID signal after bypassing icloud activation lock in this tool. I am looking for a more up to date alternative for the Sliver tool so that's why I am asking for it.

Sincerely,

**Comment by LukeZGD** [comment]
breaks jailbreak and legacyjailbreak rules, i will not be adding this

previously mentioned this in #544
