### ISSUE TITLE
SSH ramdisk help

### ISSUE THREAD

**Issue by UInt2048** [LukeZGD/Legacy-iOS-Kit#559]
I'm trying to use an SSH ramdisk on an `iPhone 6S Plus (iPhone8,2 - n66ap)` running iOS 11.3.1.

I've successfully used one in the past on this device at some point.

However, I can't get the mount filesystems command to work anymore — it just hangs indefinitely.

Here's the output on-device. 

The relevant error seems to be `nx_volume_group_update:6773: Volume Monarch13A452.N66OS role 0 Not a System or data volume`.

Any assistance would be appreciated. Thank you!

![IMG_3383](https://github.com/user-attachments/assets/019f24e6-794c-42e4-8709-a1b67c1b7c72)

**Comment by LukeZGD** [comment]
That's a weird issue, I don't think I can help with it.. It's also weird that it says `Monarch13A452` since that is 9.0.2, while 11.3.1 is the current iOS version haha. Maybe try asking Nathan or ask for assistance in rjb sub/discord server

**Comment by LukeZGD** [comment]
closing now since i cant really help with this one, sorry about that
