### ISSUE TITLE
Sideloading Issue

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#564]
*** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.09.01 (6cf7239)
* Platform: linux (Ubuntu 22.04.4 LTS) 

* Device: iPhone 6 (iPhone7,2 - n61ap) in Normal mode
* iOS Version: 9.2 (13C75)
* ECID: 2591902034249766

* Sideload IPA is for iOS 9 and newer only. Sideloading will require an Apple ID.
* Your Apple ID and password will only be sent to Apple servers.
* Make sure that the device is activated and connected to the Internet.
* There is also the option to use Dadoum Sideloader: https://github.com/Dadoum/Sideloader
* If you have AppSync installed, go to App Management -> Install IPA (AppSync) instead.

* Selected IPA: /home/linux/Downloads/kok3shi9_v5.0.2.ipa

 > Main Menu > Sideload IPA
[Input] Select an option:
1) Select IPA
2) Install IPA
3) Go Back
#? 2
[Log] Checking for latest anisette-server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18531  100 18531    0     0  71911      0 --:--:-- --:--:-- --:--:-- 72105
[Log] Latest version: 2.2.0-1, current version: 2.2.0-1
[Log] Running Anisette
[Log] Waiting for Anisette
                     app INFO  2024-09-04T13:27:17.377 anisette-server-provision v2.2.2
                     app INFO  2024-09-04T13:27:17.383 Ready! Serving data.
                     app INFO  2024-09-04T13:27:18.392 [<<] GET 
                     app INFO  2024-09-04T13:27:18.393 [>>] 200 OK {"X-Apple-I-Client-Time":"2024-09-04T13:27:18Z","X-Apple-I-MD":"AAAABQAAABDHlGjRNK28p3wVtFOG1a9oAAAABA==","X-Apple-I-MD-LU":"5DA5C5215678521455F066E37C33122D33029D4FE2877B4AEB01C1062780757D","X-Apple-I-MD-M":"m9OYzCdXcMiKhgED8v7IS23hsV1f8DXf6J1FwmAdo1\/jQ2o+GqlpHvNk85u362XpJpnJdfLKeh71AiBw","X-Apple-I-MD-RINFO":"17106176","X-Apple-I-SRL-NO":"0","X-Apple-I-TimeZone":"EDT","X-Apple-Locale":"en_US","X-MMe-Client-Info":"<MacBookPro13,2> <macOS;13.1;22C65> <com.apple.AuthKit\/1 (com.apple.dt.Xcode\/3594.4.19)>","X-Mme-Device-Id":"D27FCCF0-F0F0-4E46-B465-B9660AD41C0A"}
[Log] Attempting idevicepair
SUCCESS: Paired with device bf5035b6312bcb224b6aabfc1a15b13402f91ce0
SUCCESS: Paired with device bf5035b6312bcb224b6aabfc1a15b13402f91ce0
[Log] Enter Apple ID details to continue.
* Your Apple ID and password will only be sent to Apple servers.
[Input] Apple ID:
* Your password input will not be visible, but it is still being entered.
[Input] Password: 
[Log] Running AltServer-Linux with given Apple ID details...
Installing app...
                     app INFO  2024-09-04T13:27:29.060 [<<] GET 
                     app INFO  2024-09-04T13:27:29.060 [>>] 200 OK {"X-Apple-I-Client-Time":"2024-09-04T13:27:29Z","X-Apple-I-MD":"AAAABQAAABDHlGjRNK28p3wVtFOG1a9oAAAABA==","X-Apple-I-MD-LU":"5DA5C5215678521455F066E37C33122D33029D4FE2877B4AEB01C1062780757D","X-Apple-I-MD-M":"m9OYzCdXcMiKhgED8v7IS23hsV1f8DXf6J1FwmAdo1\/jQ2o+GqlpHvNk85u362XpJpnJdfLKeh71AiBw","X-Apple-I-MD-RINFO":"17106176","X-Apple-I-SRL-NO":"0","X-Apple-I-TimeZone":"EDT","X-Apple-Locale":"en_US","X-MMe-Client-Info":"<MacBookPro13,2> <macOS;13.1;22C65> <com.apple.AuthKit\/1 (com.apple.dt.Xcode\/3594.4.19)>","X-Mme-Device-Id":"D27FCCF0-F0F0-4E46-B465-B9660AD41C0A"}
Received response status code: 200
parse anisette data ret
Got anisetteData json: {"X-Apple-I-Client-Time":"2024-09-04T13:27:29Z","X-Apple-I-MD":"AAAABQAAABDHlGjRNK28p3wVtFOG1a9oAAAABA==","X-Apple-I-MD-LU":"5DA5C5215678521455F066E37C33122D33029D4FE2877B4AEB01C1062780757D","X-Apple-I-MD-M":"m9OYzCdXcMiKhgED8v7IS23hsV1f8DXf6J1FwmAdo1/jQ2o+GqlpHvNk85u362XpJpnJdfLKeh71AiBw","X-Apple-I-MD-RINFO":"17106176","X-Apple-I-SRL-NO":"0","X-Apple-I-TimeZone":"EDT","X-Apple-Locale":"en_US","X-MMe-Client-Info":"<MacBookPro13,2> <macOS;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>","X-Mme-Device-Id":"D27FCCF0-F0F0-4E46-B465-B9660AD41C0A"}
X-Apple-I-MD-M: m9OYzCdXcMiKhgED8v7IS23hsV1f8DXf6J1FwmAdo1/jQ2o+GqlpHvNk85u362XpJpnJdfLKeh71AiBw
X-Apple-I-MD: AAAABQAAABDHlGjRNK28p3wVtFOG1a9oAAAABA==
X-Apple-I-MD-LU: 5DA5C5215678521455F066E37C33122D33029D4FE2877B4AEB01C1062780757D
X-Apple-I-MD-RINFO: 17106176
X-Mme-Device-Id: D27FCCF0-F0F0-4E46-B465-B9660AD41C0A
X-Apple-I-SRL-NO: 0
X-MMe-Client-Info: <MacBookPro13,2> <macOS;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>
X-Apple-I-Client-Time: 2024-09-04T13:27:29Z
X-Apple-Locale: en_US
X-Apple-I-TimeZone: EDT
Building anisetteData obj...
MachineID : m9OYzCdXcMiKhgED8v7IS23hsV1f8DXf6J1FwmAdo1/jQ2o+GqlpHvNk85u362XpJpnJdfLKeh71AiBw
One-Time Password: AAAABQAAABDHlGjRNK28p3wVtFOG1a9oAAAABA==
Local User ID: 5DA5C5215678521455F066E37C33122D33029D4FE2877B4AEB01C1062780757D
Device UDID: D27FCCF0-F0F0-4E46-B465-B9660AD41C0A
Device Description: <MacBookPro13,2> <macOS;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>
Date: 2024-09-04T18:27:29Z
Received auth response status code: 200
Received auth response status code: 200
HMAC_OUT:
Byte:109
Byte:-54
Byte:77
Byte:61
Byte:-2
Byte:29
Byte:-49
Byte:112
Byte:20
Byte:-104
Byte:-4
Byte:-50
Byte:121
Byte:116
Byte:88
Byte:-85
Byte:85
Byte:92
Byte:123
Byte:-117
Byte:101
Byte:-11
Byte:60
Byte:95
Byte:-29
Byte:-84
Byte:61
Byte:10
Byte:57
Byte:59
Byte:28
Byte:103
NP:
Byte:-89
Byte:-101
Byte:-66
Byte:25
Byte:-64
Byte:81
Byte:-32
Byte:62
Byte:-21
Byte:58
Byte:37
Byte:-26
Byte:-71
Byte:-12
Byte:73
Byte:-69
Byte:-74
Byte:-45
Byte:12
Byte:-95
Byte:126
Byte:-126
Byte:116
Byte:97
Byte:37
Byte:37
Byte:99
Byte:-55
Byte:98
Byte:110
Byte:64
Byte:121
Data: <dict><key>isEligibleForBackgroundICloudSignIn</key><string>true</string><key>acname</key><string>jefferyat@gmail.com</string><key>ln</key><string>Atkinson</string><key>canBeBeneficiary</key><integer>1</integer><key>primaryEmailVetted</key><integer>1</integer><key>canHaveBeneficiary</key><integer>1</integer><key>fn</key><string>Jeff</string><key>adsid</key><string>000278-10-cdbf55f4-4b29-46bc-8d88-d9a1ff4bbb9d</string><key>duration</key><integer>3600</integer><key>canBeCustodian</key><integer>1</integer><key>passkeyEligible</key><integer>0</integer><key>userCountryWalrusEligible</key><integer>1</integer><key>canHaveCustodian</key><integer>1</integer><key>countryCode</key><string>US</string><key>custodianEnabled</key><integer>0</integer><key>isSenior</key><string>true</string><key>sk</key><data>1LAaP4NYgt1PdPnj83YUmpOMehhg0Je09Sxd0mfpU6E=</data><key>additionalInfo</key><dict><key>silentEscrowRecordRepairEnabled</key><integer>0</integer><key>obfuscatedPhoneNumbers</key><array><dict><key>recentlyUsed</key><integer>1</integer><key>maskedPhoneNumber</key><string>(***) ***-0071</string></dict></array><key>phoneNumbers</key><array><dict><key>phoneNumber</key><string>(704) 962-0071</string><key>recentlyUsed</key><integer>1</integer><key>type</key><string>2fa</string></dict></array></dict><key>ageOfMajority</key><integer>13</integer><key>serverExperimentalFeatures</key><integer>0</integer><key>webAccessEnabled</key><integer>1</integer><key>primaryEmail</key><string>jefferyat@gmail.com</string><key>ut</key><integer>4</integer><key>authmode</key><integer>1</integer><key>c</key><data>NjI3MTkwNWUtOTU0Yy00Y2Y2LThhMmEtMWM1Mjg4M2ZmMDA1dmRUeU5BOE9wZEpzWHFIQTZ4NnZ6LzNtUENTdURpdUxwN1gwb1lqbmh1cU5MTlpCOHNqRzlLWGU3TTNTUWswelBZK0kyV042VEgzeitIbHRQRmhGS1VXcUlZWW1yYW5Ia3F3QkxWRWdJUi9saCtCanBhSzRSRURhTkhFZnFZU1dXRnBI</data><key>beneficiaryListVersion</key><string>0</string><key>privateAttestationEnabled</key><integer>1</integer><key>GsIdmsToken</key><string>AAAABLwIAAAAAGbYmIERDGdzLmlkbXMuYXV0aL0Au5PnCSvErxxOF+vGFIJwwtb5eb/4EbDo2YSINbiv0baBQocNjbOu9KUpivD7mIwBqnIuUcu1I2pscMcy1sdXcJn0W5IAM17rYZ0DwOmisV3iwjt0k7rW9wJcbciqC0JbCjVVRIvMfe9chIrzdHWtmEyW9xpELigydbYwNVKS4d3c6LHml7Y6L0E8qwPS/hNagUvRiuGAkktd/NKO5LXmfo/3TnklN/Piytif75DMHqhWQb4m</string><key>status-code</key><integer>200</integer><key>t</key><dict><key>com.apple.gs.idms.pet</key><dict><key>duration</key><integer>300</integer><key>expiry</key><integer>1725471149846</integer><key>token</key><string>GSQ5ZYDB7qjyd9nk/WIQitQY8Fwf2slzvCjF8NGx3U595OrPJeBG+gI7ETcH3GJJ2X5QCQ8349pKLyksC5RfjXwpzpXn7VyRdKyVqH1UyaEIvThESpXkm4QctsQBM0NA0ghty55wfw3UTkvY6LEIaNR99lnXVmwXCL4GzoxMw62l1OiGKhrATdRG7aE+RgFrZGjtcFebEkJms9VIlBtaGJ5woJH08OKRd8EVebe1a1iZPbQb5OUBvIJK14Z4Khhld5DovGkJSBSqn9c+YArkfJ6VKwModi1dcep5he2wNDFKqgpjI1bePv/A5Jliz3CwcCg4YI9WW3BwZMwXSfAPFlA5gZk/Qanc1bcq7i/QD9oRfoWlUQGrNqS7r+vFVjD8gPxMuALy86N7R/bf/sFZ4q8SEex0V1Gjh807EvdQggDA8dxaQTZ8yX2kczsQcz75+dS3FLjd0eEYIbTqdh0HRgs+St59PET</string></dict><key>com.apple.gs.icloud.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>GSQ5ZYDB7qjyd9nk/WIQitQtU2MHoLYyGUeesHLBwQeWhRqof0h4GLBGoPFNrKNsZrd5baG4zdIka3q3s2AtJ1pFBpEXmEl7AWNe4uxI/nfgSdsSvymGQzWOtLAUx+VXDMQXErsKvHBf2pVrVbLQZcbvz9BSwbnnPBNnjZOZumYuI16FF1aXC+YU1+eV+pBdM43baHjoxgDTy24xWr1edM3IxQozZJAZTU5AJGDGASl5BjyrcuB/odcZeTu3hGMNh5iBVZ5J/DEWfLmoMneYDYX4ZrwpEPptTVoKCIQakXgRIzOhjuwbHiu6LeQkq0ac6QUdDMV7D3d6DmUcBdTFyPO5qlTafZxoW2x6W6i1jj7QpRn4GF3YY3XhVQi2fgpweJ472f7jquyQ6tDiu0QnEwnbA8xt08k7WwPTJ+oGY6hOndoJw2pf/dmzqSvd+DJsoWqYCqSIbrvi9vtBcnrcsNiKD0gB</string></dict><key>com.apple.gs.appleid.auth</key><dict><key>duration</key><integer>3600</integer><key>expiry</key><integer>1725474449846</integer><key>token</key><string>GSQ5ZYDB7qjyd9nk/WIQitR0WOrJDVsh8GhnTd9iZMtmoEReW2oez87vS3uuc/dJmEBv+fF95OszJkM3YeqbjZ1rUF3+Zq6oX14MJG5oqEpckShD8hHu3FawHyiKxTp0xQ+UBqpQB/pwhBPBFcydFRv7sWxC6ex3kDe04MpQEisa01pY9LwxeCLnZGiQnYS8HqZBcCmAuxBEJIfLKoECemOFpBvWzgUrJTpOQoEz82zp4Q8EhnuI74nvRD+3BNTxYPgMy4tAGMfmTOEyFQzjG8fqU1YRKfpJaaRjHYnntDBkBQldVisUf7Zf4bywU+qo5BUL/2VzLadBzueOTJoEeTqyEpgGYHalqhInc60Sv7G4/e+IyIh6iSD2zE7cq1aRUVu7uvl2weDjn/zzgQxPhM7ISEIi/y7/EtbEM4WgG5T+GtYqRKCIS4GzrUI2Mrv9CoVRnUDOSGemi5BH5t8Jvtsl3d7n</string></dict><key>com.apple.gs.idms.hb</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERCmdzLmlkbXMuaGK9ALuT5wkrxK8cThfrxhSCcMLW+Xm/+BGw6NmEiDW4r9G2gUKHDY2zrvSlKYrw+5iMAapyLlHLtSNqbHDHMtbHV3CZ9FuSADNe62GdA8DporFd4sI7dJO61vcCXG3IqgtCWwo1VUSLzH3vXISK83R1rZhMlvcaRC4oMnW2MDVSkuHd3Oix5pe2Oi9BPKsD0v4TWrTuPB6a6zAbVbfV/G+S2HyajuEl4uxn5cmYqlz/XyrHwDGk0A==</string></dict><key>com.apple.gs.pb.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERCmdzLnBiLmF1dGi9ALuT5wkrxK8cThfrxhSCcMLW+Xm/+BGw6NmEiDW4r9G2gUKHDY2zrvSlKYrw+5iMAapyLlHLtSNqbHDHMtbHV3CZ9FuSADNe62GdA8DporFd4sI7dJO61vcCXG3IqgtCWwo1VUSLzH3vXISK83R1rZhMlvcaRC4oMnW2MDVSkuHd3Oix5pe2Oi9BPKsD0v4TWvrLSqjo/a+XdPcBQm47ofaBjPwqfNp3u1dIfQLGoOVXpzf07g==</string></dict><key>com.apple.gs.gpk.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERC2dzLmdway5hdXRovQC7k+cJK8SvHE4X68YUgnDC1vl5v/gRsOjZhIg1uK/RtoFChw2Ns670pSmK8PuYjAGqci5Ry7UjamxwxzLWx1dwmfRbkgAzXuthnQPA6aKxXeLCO3STutb3AlxtyKoLQlsKNVVEi8x971yEivN0da2YTJb3GkQuKDJ1tjA1UpLh3dzoseaXtjovQTyrA9L+E1oFgj3tTGQo8myo5uTJFaXmMLlpP+SAwbgTNn+7Z/QHsd1PB1M=</string></dict><key>com.apple.gs.sharedchannels.auth</key><dict><key>duration</key><integer>172800</integer><key>expiry</key><integer>1725643649846</integer><key>token</key><string>eyJraWQiOiI2IiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiIwMDAyNzgtMTAtY2RiZjU1ZjQtNGIyOS00NmJjLThkODgtZDlhMWZmNGJiYjlkIiwiZXhwIjoxNzI1NjQzNjQ5LCJpYXQiOjE3MjU0NzA4NDksImlzcyI6ImNvbS5hcHBsZS5pZG1zIiwiaWQiOiJjb20uYXBwbGUuZ3Muc2hhcmVkY2hhbm5lbHMuYXV0aCIsInRva2VuIjoiQUFBQUJMd0lBQUFBQUdiWW1JRVJGbWR6TG5Ob1lYSmxaR05vWVc1dVpXeHpMbUYxZEdpOUFMdVQ1d2tyeEs4Y1RoZnJ4aFNDY01MVytYbS8rQkd3Nk5tRWlEVzRyOUcyZ1VLSERZMnpydlNsS1lydys1aU1BYXB5TGxITHRTTnFiSERITXRiSFYzQ1o5RnVTQUROZTYyR2RBOERwb3JGZDRzSTdkSk82MXZjQ1hHM0lxZ3RDV3dvMVZVU0x6SDN2WElTSzgzUjFyWmhNbHZjYVJDNG9NblcyTURWU2t1SGQzT2l4NXBlMk9pOUJQS3NEMHY0VFdwVkJEeENJNk04dWw4S1IyNi9TZ3lNQUh2OWtrd0psNTVDcFVBNll4Y0RNdE5Yb1pBPT0iLCJtaWQiOiJtOU9ZekNkWGNNaUtoZ0VEOHY3SVMyM2hzVjFmOERYZjZKMUZ3bUFkbzEvalEybytHcWxwSHZOazg1dTM2MlhwSnBuSmRmTEtlaDcxQWlCdyIsInNlcmlhbF9ubyI6IjAifQ.-d9nr9H48lUAF-e_lwxJBzGlnb8wzFo7U6PP8YQP1A_QYiDY20WA5R8X0XizZtEB9UFOjYu9wGn5rWtj-iXQsg</string></dict><key>com.apple.gs.idms.ln</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERCmdzLmlkbXMubG69ALuT5wkrxK8cThfrxhSCcMLW+Xm/+BGw6NmEiDW4r9G2gUKHDY2zrvSlKYrw+5iMAapyLlHLtSNqbHDHMtbHV3CZ9FuSADNe62GdA8DporFd4sI7dJO61vcCXG3IqgtCWwo1VUSLzH3vXISK83R1rZhMlvcaRC4oMnW2MDVSkuHd3Oix5pe2Oi9BPKsD0v4TWlGENUHCoYGCFNROKARzbl6XrbhFdGjp6n8r1P++9Ghmfo1W1Q==</string></dict><key>com.apple.gs.global.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERDmdzLmdsb2JhbC5hdXRovQC7k+cJK8SvHE4X68YUgnDC1vl5v/gRsOjZhIg1uK/RtoFChw2Ns670pSmK8PuYjAGqci5Ry7UjamxwxzLWx1dwmfRbkgAzXuthnQPA6aKxXeLCO3STutb3AlxtyKoLQlsKNVVEi8x971yEivN0da2YTJb3GkQuKDJ1tjA1UpLh3dzoseaXtjovQTyrA9L+E1pRpJHIeXo8uxn4o4O/3/2RjZp2L4y7BE16ZPWFTzxMor9uHXk=</string></dict><key>com.apple.gs.supportapp.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIEREmdzLnN1cHBvcnRhcHAuYXV0aL0Au5PnCSvErxxOF+vGFIJwwtb5eb/4EbDo2YSINbiv0baBQocNjbOu9KUpivD7mIwBqnIuUcu1I2pscMcy1sdXcJn0W5IAM17rYZ0DwOmisV3iwjt0k7rW9wJcbciqC0JbCjVVRIvMfe9chIrzdHWtmEyW9xpELigydbYwNVKS4d3c6LHml7Y6L0E8qwPS/hNaGa+aqtL8RbpvhlaB2wu6CR7V0wMAjAMyRhTGRlFdH6Z/Z2Gx</string></dict><key>com.apple.gs.beta.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERDGdzLmJldGEuYXV0aL0Au5PnCSvErxxOF+vGFIJwwtb5eb/4EbDo2YSINbiv0baBQocNjbOu9KUpivD7mIwBqnIuUcu1I2pscMcy1sdXcJn0W5IAM17rYZ0DwOmisV3iwjt0k7rW9wJcbciqC0JbCjVVRIvMfe9chIrzdHWtmEyW9xpELigydbYwNVKS4d3c6LHml7Y6L0E8qwPS/hNaXESN0BYQfndh7n8vtBDcy0eqMtlNLu7FSYrFgGb0ixa0BBK8</string></dict><key>com.apple.gs.tdm.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERC2dzLnRkbS5hdXRovQC7k+cJK8SvHE4X68YUgnDC1vl5v/gRsOjZhIg1uK/RtoFChw2Ns670pSmK8PuYjAGqci5Ry7UjamxwxzLWx1dwmfRbkgAzXuthnQPA6aKxXeLCO3STutb3AlxtyKoLQlsKNVVEi8x971yEivN0da2YTJb3GkQuKDJ1tjA1UpLh3dzoseaXtjovQTyrA9L+E1qsOv9PAkUFqT50ED352NI31VPAHPqhUoareHlu0gZcVVqFD/k=</string></dict><key>com.apple.gs.itunes.mu.invite</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERE2dzLml0dW5lcy5tdS5pbnZpdGW9ALuT5wkrxK8cThfrxhSCcMLW+Xm/+BGw6NmEiDW4r9G2gUKHDY2zrvSlKYrw+5iMAapyLlHLtSNqbHDHMtbHV3CZ9FuSADNe62GdA8DporFd4sI7dJO61vcCXG3IqgtCWwo1VUSLzH3vXISK83R1rZhMlvcaRC4oMnW2MDVSkuHd3Oix5pe2Oi9BPKsD0v4TWm79bN2rg4bm2M+niSOuH8ESv2kX9HDmR9XsUejTmX3O6SkRow==</string></dict><key>com.apple.gs.icloud.storage.buy</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERFWdzLmljbG91ZC5zdG9yYWdlLmJ1eb0Au5PnCSvErxxOF+vGFIJwwtb5eb/4EbDo2YSINbiv0baBQocNjbOu9KUpivD7mIwBqnIuUcu1I2pscMcy1sdXcJn0W5IAM17rYZ0DwOmisV3iwjt0k7rW9wJcbciqC0JbCjVVRIvMfe9chIrzdHWtmEyW9xpELigydbYwNVKS4d3c6LHml7Y6L0E8qwPS/hNaRGUmzKndN++JJz+brEGFuXccbrxMJTKgzy0jGLY8k5byEn/+</string></dict><key>com.apple.gs.news.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERDGdzLm5ld3MuYXV0aL0Au5PnCSvErxxOF+vGFIJwwtb5eb/4EbDo2YSINbiv0baBQocNjbOu9KUpivD7mIwBqnIuUcu1I2pscMcy1sdXcJn0W5IAM17rYZ0DwOmisV3iwjt0k7rW9wJcbciqC0JbCjVVRIvMfe9chIrzdHWtmEyW9xpELigydbYwNVKS4d3c6LHml7Y6L0E8qwPS/hNa1MPzvs+SWDOqO8kiOAO3uGsm7gvFyYtNgRHuwEkl3OgOlCbW</string></dict><key>com.apple.gs.authagent.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIEREWdzLmF1dGhhZ2VudC5hdXRovQC7k+cJK8SvHE4X68YUgnDC1vl5v/gRsOjZhIg1uK/RtoFChw2Ns670pSmK8PuYjAGqci5Ry7UjamxwxzLWx1dwmfRbkgAzXuthnQPA6aKxXeLCO3STutb3AlxtyKoLQlsKNVVEi8x971yEivN0da2YTJb3GkQuKDJ1tjA1UpLh3dzoseaXtjovQTyrA9L+E1rJB6nyup5eIs4GbpJghZch2cV+Ss9qpd9U73T5d73vqn9eWLM=</string></dict><key>com.apple.gs.dip.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERC2dzLmRpcC5hdXRovQC7k+cJK8SvHE4X68YUgnDC1vl5v/gRsOjZhIg1uK/RtoFChw2Ns670pSmK8PuYjAGqci5Ry7UjamxwxzLWx1dwmfRbkgAzXuthnQPA6aKxXeLCO3STutb3AlxtyKoLQlsKNVVEi8x971yEivN0da2YTJb3GkQuKDJ1tjA1UpLh3dzoseaXtjovQTyrA9L+E1ol/MrIsTLK1pGd+/3L7mQ8BhT+oKaDV8SwlNQ5cJ5dXUpsYjs=</string></dict><key>com.apple.gs.sharedexperiences.auth</key><dict><key>duration</key><integer>604800</integer><key>expiry</key><integer>1726075649846</integer><key>token</key><string>eyJraWQiOiI5IiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiIwMDAyNzgtMTAtY2RiZjU1ZjQtNGIyOS00NmJjLThkODgtZDlhMWZmNGJiYjlkIiwiZXhwIjoxNzI2MDc1NjQ5LCJpYXQiOjE3MjU0NzA4NDksImlzcyI6ImNvbS5hcHBsZS5pZG1zIiwiaWQiOiJjb20uYXBwbGUuZ3Muc2hhcmVkZXhwZXJpZW5jZXMuYXV0aCIsInRva2VuIjoiQUFBQUJMd0lBQUFBQUdiWW1JRVJHV2R6TG5Ob1lYSmxaR1Y0Y0dWeWFXVnVZMlZ6TG1GMWRHaTlBTHVUNXdrcnhLOGNUaGZyeGhTQ2NNTFcrWG0vK0JHdzZObUVpRFc0cjlHMmdVS0hEWTJ6cnZTbEtZcncrNWlNQWFweUxsSEx0U05xYkhESE10YkhWM0NaOUZ1U0FETmU2MkdkQThEcG9yRmQ0c0k3ZEpPNjF2Y0NYRzNJcWd0Q1d3bzFWVVNMekgzdlhJU0s4M1IxclpoTWx2Y2FSQzRvTW5XMk1EVlNrdUhkM09peDVwZTJPaTlCUEtzRDB2NFRXdm9yMEFLRE1uNTFoUWNRNEZBMnZtQkp2NXNNNXlIbkxLRkRRcEd0aEE0TWFRV2RLUT09IiwibWlkIjoibTlPWXpDZFhjTWlLaGdFRDh2N0lTMjNoc1YxZjhEWGY2SjFGd21BZG8xL2pRMm8rR3FscEh2Tms4NXUzNjJYcEpwbkpkZkxLZWg3MUFpQnciLCJzZXJpYWxfbm8iOiIwIn0.5xNavQdPZFbPRVMLxFYK0L50Rr2Dy2aGoe_lkEcyDP78A8RFjRVYPsa2tddbXFc4RI8pcsz7AK-Sfg-_TUtcdA</string></dict><key>com.apple.gs.icloud.family.auth</key><dict><key>duration</key><integer>31536000</integer><key>expiry</key><integer>1757006849846</integer><key>token</key><string>AAAABLwIAAAAAGbYmIERFWdzLmljbG91ZC5mYW1pbHkuYXV0aL0Au5PnCSvErxxOF+vGFIJwwtb5eb/4EbDo2YSINbiv0baBQocNjbOu9KUpivD7mIwBqnIuUcu1I2pscMcy1sdXcJn0W5IAM17rYZ0DwOmisV3iwjt0k7rW9wJcbciqC0JbCjVVRIvMfe9chIrzdHWtmEyW9xpELigydbYwNVKS4d3c6LHml7Y6L0E8qwPS/hNaSpMDb0sT4Jo/wkMsCr2XEipyPsEQVfv9CdRWy9KbA1a47IjH</string></dict></dict><key>underAge</key><integer>0</integer><key>passkeyPresent</key><integer>0</integer><key>isProximityAuthEligible</key><integer>0</integer><key>DsPrsId</key><integer>563132952</integer></dict>
Received auth response status code: 200
Got token for com.apple.gs.xcode.auth!
Value : AAAABLwIAAAAAGbYmIIRDWdzLnhjb2RlLmF1dGi9AMtte+1UqgW0kNS38JSw82L7Jkt+gZufzG+fRTs0gaUjG1aS/6c+ObF6Zc3cdO27WdX/sQ6++iAw8dCNVsVMtvurM52FGfNBCNE9ZLVKVkLIz4Yop/KUVmQ/3XUY9GBCry22YLEjI0J2BQXfPegaxurt+yCs
Received response status code: 200
Fetching team...
Received response status code: 200
Registering device...
Received response status code: 200
Fetching certificate...
Received response status code: 200
Preparing device...
Received response status code: 200
Failed to install DeveloperDiskImage.dmg to Name: unknown UDID: bf5035b6312bcb224b6aabfc1a15b13402f91ce0. The URL to download the Developer disk image could not be determined.
Importing app...
Downloaded app!
Notify: Installing kokeshi9_new to unknown...
    This may take a few seconds.
Received response status code: 200
Received response status code: 200
Alert: Could not install kok3shi9_v5.0.2.ipa to unknown.
    The name for this app is invalid.
Press any key to continue...

Error: com.rileytestut.ALTAppleAPI (9).
Finished!

* Save the terminal output now if needed.
* Legacy iOS Kit v24.09.01 (6cf7239)
* Platform: linux (Ubuntu 22.04.4 LTS)

**Comment by LukeZGD** [comment]
seems to be some kind of issue with the kok3shi9 5.0 ipa that makes it fail with altserver-linux (4.0.3 works fine)

use dadoum sideloader instead, it seems to work fine from there
