### ISSUE TITLE
iPhone 4s downgrade 

### ISSUE THREAD

**Issue by maximus215** [LukeZGD/Legacy-iOS-Kit#565]
getting same issue on OTA downgrader to either do ios 8.4.1 or ios 6.1.3

 line 2262: ../bin/macos/tsschecker: No such file or directory
ls: 3423006412173_iPhone4,1_n94ap_8.4.1-12H321_*.shsh*: No such file or directory
[Error] Saving 8.4.1 blobs failed. Please run the script again

**Comment by maximus215** [comment]
or I get issue "“tsschecker” is damaged and can’t be opened. You should move it to the Trash"

**Comment by LukeZGD** [comment]
delete firstrun in the resources folder then try again, let me know how it goes

**Comment by maximus215** [comment]
still getting the tss checker issue :( should I try a fresh download?

**Comment by LukeZGD** [comment]
yes

**Comment by LukeZGD** [comment]
<img width="827" alt="Screenshot 2024-09-08 at 11 17 38 PM" src="https://github.com/user-attachments/assets/caa32a83-d846-4d05-bd22-0d2a020599af">

works fine for me

try to `git clone` the repo and try again from there

**Comment by LukeZGD** [comment]
see other troubleshooting steps here https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting#macos
