### ISSUE TITLE
Downgrade question

### ISSUE THREAD

**Issue by AlertFire399611** [LukeZGD/Legacy-iOS-Kit#566]
Hello! I have an icloud locked ipad 2,1
I Want downgrade it to ios 6 but i can't jailbreak it
I already make tethered bypass, then tried phoenix jailbreak, but they did'nt work, i tried jailbreaks.app/legacy.html, 3utools, this did'nt work
Can i downgrade it without arduino and Other things?
iOS ver 9.3.5

**Comment by LukeZGD** [comment]
you need an arduino/pi pico for checkm8-a5
