### ISSUE TITLE
iPhone 5 failed to tethered downgrade to iOS 10.0 beta 1 

### ISSUE THREAD

**Issue by harry33333333** [LukeZGD/Legacy-iOS-Kit#569]
Hello! I have an iPhone 5. When I tried to downgrade to iOS 10.0 beta1 (version 14A5261v) through tethering, the script displayed an error "Issue with firmware keys: Failed getting RootFS." when making the tethered firmware. However, I checked the Apple Wiki website and found that there was no Root Filesystem key. However, I found someone on Reddit saying that Rootfs before iOS 10 was encrypted and required a firmware key to decrypt, which means that iOS 10.0 beta1 may not require Rootfs decryption. So do you want to modify the script so that it can operate normally on this firmware, or can you give some explanation?
Phone model: iPhone 5,2
Firmware name: iPhone_4.0_32bit_10.0_14A5261v_Restore.ipsw

**Comment by harry33333333** [comment]
Here is a screenshot of the terminal:
![12E62F762F2C35982EEF091156478B15](https://github.com/user-attachments/assets/ba736299-4a2b-4118-8937-9ee9a35cf232)

**Comment by LukeZGD** [comment]
tethered restores to ios 10 is a weird edge case i havent tested, ill try to do something about it

**Comment by LukeZGD** [comment]
so i have fixed the firmware key stuff now as of v24.09.05, but now the ipsw utility wont proceed and will error out here. so ios 10 targets will not be supported after all unfortunately
<img width="831" alt="Screenshot 2024-09-10 at 10 55 06 AM" src="https://github.com/user-attachments/assets/15df0623-a60f-424a-b3bd-46143cbcb898">
