### ISSUE TITLE
Can AppSync be included during the jailbreak process?

### ISSUE THREAD

**Issue by yoyo2306** [LukeZGD/Legacy-iOS-Kit#571]
Can I choose to include AppSync directly when jailbreaking or flashing the device? If that's possible, that would be great! After jailbreaking or flashing, you can install jailbreak IPAs right away without manually installing AppSync again.

**Comment by LukeZGD** [comment]
technically yes, by injecting the needed debs to the autoinstall folder to the ipsw. i can add this at some point, but it is currently not planned. for now, openssh is the only tweak that is getting pre-installed. so the alternative way of doing this is to enable jailbreak option for the restore, then after the restore, place cydia substrate, substrate safe mode, and appsync debs to the autoinstall folder via ssh.
