### ISSUE TITLE
iPhone 4S Not working after disabling baseband update

### ISSUE THREAD

**Issue by corped12** [LukeZGD/Legacy-iOS-Kit#572]
I downgraded my iPhone 4s to 8.4.1 with disabled baseband (it had an error with baseband on) and my iphone won't activate anymore

**Comment by LukeZGD** [comment]
if you have enabled dead-bb flag, you will need to bypass activation. this is something that is not supported in legacy ios kit, but you can use ssh ramdisk to do it manually
