### ISSUE TITLE
iPhone 4 restore to the latest ipsw failed

### ISSUE THREAD

**Issue by zz0ya** [LukeZGD/Legacy-iOS-Kit#574]
Hello!

I tried to restore my iphone to the latest iOS.
The idevicerestore program prints error message and stuck with 100% CPU load, I killed it after 30 minutes or so.
The phone is now loads into the recovery mode.

Here is a log:

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.09.07 (742c9c3)
* Platform: linux (Ubuntu 24.04.1 LTS - x86_64)

* Device: iPhone 4 (GSM) (iPhone3,1 - n90ap) in Recovery mode
* iOS Version: ::       BUILD_TAG: iBoot-1940.10.58
* ECID: 1125484233512

* Only select unmodified IPSW for the selection. Do not select custom IPSWs

* Selected IPSW: /home/refute/Downloads/iPhone3,1_7.1.2_11D257_Restore.ipsw

* This restore will use 7.1.2 baseband if the jailbreak option is disabled

 > Main Menu > Restore/Downgrade > Latest iOS (7.1.2)
[Input] Select an option:
1) Select Target IPSW
2) Download Target IPSW
3) Start Restore
4) Go Back
#? 3
[Input] Jailbreak Option
* When this option is enabled, your device will be jailbroken on restore.
* I recommend to enable this option to have the jailbreak and Cydia pre-installed.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): n
[Log] Jailbreak option disabled by user.

[Log] Running idevicerestore with command: sudo ../bin/linux/x86_64/idevicerestore -e "/home/refute/Downloads/iPhone3,1_7.1.2_11D257_Restore.ipsw"
Found device in Recovery mode
INFO: device serial number is DX4JJ1NNDP0N
Found ECID 1125484233512
Identified device as n90ap, iPhone3,1
Extracting BuildManifest from IPSW
Product Version: 7.1.2
Product Build: 11D257 Major: 11
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Getting ApNonce in recovery mode... 95 55 11 f8 93 60 fc 23 ac db 09 b7 0f a2 a1 24 47 32 89 3d
Trying to fetch new SHSH blob
Getting SepNonce in recovery mode...
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
Using cached filesystem from '/home/refute/Downloads/iPhone3,1_7.1.2_11D257_Restore/058-4520-010.dmg'
Sending APTicket (2741 bytes)
Extracting iBEC.n90ap.RELEASE.dfu...
Personalizing IMG3 component iBEC...
reconstructed size: 285145
Sending iBEC (285145 bytes)...
Getting ApNonce in recovery mode... 95 55 11 f8 93 60 fc 23 ac db 09 b7 0f a2 a1 24 47 32 89 3d
Sending APTicket (2741 bytes)
Recovery Mode Environment:
iBoot build-version=iBoot-1940.10.58
iBoot build-style=RELEASE
ramdisk-size=0x4000000
Extracting 058-4107-013.dmg...
Not personalizing component RestoreRamDisk...
Sending RestoreRamDisk (8892684 bytes)...
Extracting DeviceTree.n90ap.img3...
Not personalizing component RestoreDeviceTree...
Sending RestoreDeviceTree (74764 bytes)...
Extracting kernelcache.release.n90...
Not personalizing component RestoreKernelCache...
Sending RestoreKernelCache (8115660 bytes)...
About to restore device...
Waiting for device...
Device 6d69596648118d1cf3dc8a5c18eabea55f4c683b is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 13
Device 6d69596648118d1cf3dc8a5c18eabea55f4c683b has successfully entered restore mode
Hardware Information:
BoardID: 0
ChipID: 35120
UniqueChipID: 1125484233512
ProductionMode: true
Panic log is available:
panic(cpu 0 caller 0x841d88d5): "Failed _ReplaceBadBlock CE 1 PBN 1225"
Debugger message: panic
OS version: 11D257
Kernel version: Darwin Kernel Version 14.0.0: Thu May 15 23:18:01 PDT 2014; root:xnu-2423.10.71~1/RELEASE_ARM_S5L8930X
Kernel slide:     0x0000000003800000
Kernel text base: 0x83801000
  Boot    : 0x66e6bffd 0x00000000
  Sleep   : 0x00000000 0x00000000
  Wake    : 0x00000000 0x00000000
  Calendar: 0x66e6c003 0x000ca927

Panicked task 0xc4419c00: 6393 pages, 101 threads: pid 0: kernel_task
panicked thread: 0xc450c220, backtrace: 0x819b3bd8
                0x83918a15
                0x839195bb
                0x83804b2d
                0x841d88d5
                0x841d3c77
                0x841dc6fb
                0x841e5be7
                0x841e4bfd
                0x841e4a37
                0x841df7d3
                0x841d2c6f
                0x841ecdbb
                0x83883a31
                0x838838f3
                0x8388408d
                0x83ab04cb
                0x8381f05c

Task 0xc4419c00: 6393 pages, 101 threads: pid 0: kernel_task
Task 0xc4419950: 377 pages, 3 threads: pid 1: launchd
Task 0xc44196a0: 549 pages, 1 threads: pid 2: launchctl
Task 0xc44193f0: 671 pages, 1 threads: pid 3: restored_externa
Task 0xc4419140: 2930 pages, 5 threads: pid 4: restored_externa

^C
* Save the terminal output now if needed.
* Legacy iOS Kit v24.09.07 (742c9c3)
* Platform: linux (Ubuntu 24.04.1 LTS - x86_64)

**Comment by LukeZGD** [comment]
looks like your iphone 4 has hardware failure with the nand, based on that `Failed _ReplaceBadBlock` error

try restoring with itunes/finder on windows/mac. if you get error 9, your nand is most likely dead
