### ISSUE TITLE
failed to sideload any apps to device using install ipa (appsync): iPad 3 (GSM) (iPad3,3 IOS 9.3.6

### ISSUE THREAD

**Issue by thatdudejr** [LukeZGD/Legacy-iOS-Kit#575]
i have install App sync iOS 5+ on my iPad 2 running iOS 9.3.6 but it fails to side load apps: 

[Log] Installing selected IPA(s) to device using ideviceinstaller...
[Log] Installing: /Users/notsoanonymous/Downloads/drive-download-20240912T193011Z-002/MCSM-1.4.0.ipa
WARNING: could not locate Payload/GameApp.app/SC_Info/GameApp.sinf in archive!
Copying '/Users/notsoanonymous/Downloads/drive-download-20240912T193011G-002/MCSM-1.4.0.ipa' to device... DONE.
Installing 'com.telltalegames.MC100'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: TakingInstallLock (20%)
Install: PreflightingApplication (30%)
Install: VerifyingApplication (40%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008001: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.v1E4y7/extracted/Payload/GameApp.app : 0xe8008001 (An unknown error has occurred.)

**Comment by LukeZGD** [comment]
It could be a problem with the IPA, try using other IPA files and/or try installing using Filza/IPA Installer

**Comment by thatdudejr** [comment]
> It could be a problem with the IPA, try using other IPA files and/or try installing using Filza/IPA Installer

I've tried all those options including filza and I've tried different app as well all get the same error message

**Comment by LukeZGD** [comment]
then yea the problem is the ipa

**Comment by LukeZGD** [comment]
then yea the problem might be the ipa. 

also just to check, where did you install appsync unified from? make sure it is from archive.org (https://web.archive.org/web/20230515000000*/https://cydia.akemi.ai/debs/ai.akemi.appsyncunified.deb) or from this repo (https://bigfloppa234.github.io/repo/)

**Comment by thatdudejr** [comment]
> then yea the problem might be the ipa.
> 
> also just to check, where did you install appsync unified from? make sure it is from archive.org (https://web.archive.org/web/20230516162851/https://cydia.akemi.ai/debs/nodelete-ai.akemi.appsyncunified.deb) or from this repo (https://bigfloppa234.github.io/repo/)

that might be the isssue i got it from here: https://pwnage.dev/ I'll try those too and see how i go thanks
