### ISSUE TITLE
[4S + Linux] Issues with kok3shi9

### ISSUE THREAD

**Issue by Pineconium** [LukeZGD/Legacy-iOS-Kit#578]
I'm trying to downgrade my iPhone 4S to iOS 6.1.3 and it's not going too well. I got everything done but I'm stuck on this bit:
```
[Log] Please read the message below:
* Follow these instructions to enter kDFU mode.
1. Install "OpenSSH" and "Core Utilities" in Cydia or Zebra.
  - After installing these requirements, lock your device.
2. You will be prompted to enter the root password of your iOS device.
  - The default root password is: alpine
  - Your password input will not be visible, but it is still being entered.
3. On entering kDFU mode, the device will disconnect.
  - Proceed to unplug and replug the device when prompted.
  - Alternatively, press the TOP or HOME button.
[Input] Press Enter/Return to continue (or press Ctrl+C to cancel)
```
I got the kok3shi9 jailbreak (since it runs iOS 9.3.5) but it doesn't work. Every time I try to start the jailbreak the iPhone restarts unexpectedly and Cydia isn't on the screen, meaning I can't progress ANY further. Is there another way I can downgrade on Linux or do I have to use a Mac ;-;

**Comment by LukeZGD** [comment]
make sure to use version 4.0.3 of kok3shi9: https://kok3shidoll.web.app/kok3shi9_32.html

also if cydia still doesnt appear after jailbreaking, try opening it using safari: `cydia://`
