### ISSUE TITLE
4s always Waiting for NAND (28) 

### ISSUE THREAD

**Issue by RiberWang** [LukeZGD/Legacy-iOS-Kit#580]
4s always Waiting for NAND (28) 
2015 old years producted

**Comment by LukeZGD** [comment]
please provide more info. for now i assume that youre trying tp downgrade to 6.1.3. known issue when restoring to 6.1.3 or lower on unsupported/too new devices (typically made in 2014 or newer)

there is no fix other than getting another device capable of running 6.1.3
