### ISSUE TITLE
Pwning using iphone se

### ISSUE THREAD

**Issue by AlertFire399611** [LukeZGD/Legacy-iOS-Kit#581]
Can i put my ipad 2 to pwndfu using iphone se on ios 15.7?

**Comment by LukeZGD** [comment]
ipad 2? no. for checkm8-a5 you need an arduino uno+usb shield, or a raspberry pi pico.

**Comment by LukeZGD** [comment]
stop creating issues for questions that i have already answered for you, both in the issues you previously opened, and in the troubleshooting wiki.
