### ISSUE TITLE
Sequel to "Not really an issue but rather a question. "

### ISSUE THREAD

**Issue by GreenwaveStudios** [LukeZGD/Legacy-iOS-Kit#591]
Can you put it in dfu mode before you do the jailbreak?

**Comment by LukeZGD** [comment]
yes, thats what youre supposed to do

also no need to open an issue for every question

**Comment by GreenwaveStudios** [comment]
ok

**Comment by GreenwaveStudios** [comment]
> yes, thats what youre supposed to do
> 
> also no need to open an issue for every question

i thought you had to do it in the middle of the process as shown in the image here
![image](https://github.com/user-attachments/assets/4512154f-e923-45b5-903a-335a0df5410d)

**Comment by GreenwaveStudios** [comment]
it would be less stressful to do it before the jb rather than do it during
