### ISSUE TITLE
Unable to sign in to my apple id?

### ISSUE THREAD

**Issue by kapivr** [LukeZGD/Legacy-iOS-Kit#592]
Hello. When ever I need to sign in to something (Like game center or iTunes,) it says the username or password is incorrect. I verified that I am not inputting wrong information (Other devices will ask me to verify and I have copy and pasted.) Is this a known issue relating to legacy iOS kit? Could it possibly be something to do with certificates (Such as the iOS being to old?) Im currently having issues on iOS 8.4.1. Thanks!

**Comment by LukeZGD** [comment]
https://www.reddit.com/r/LegacyJailbreak/comments/15x206a/tutorial_how_to_sign_in_icloud_ios_8/?rdt=56677
