### ISSUE TITLE
iPad4,1 - iOS version 12.2 [IMG4TOOL] failed to verify IM4M signature with error:

### ISSUE THREAD

**Issue by zygame110119** [LukeZGD/Legacy-iOS-Kit#593]
> Main Menu > Restore/Downgrade > Other (Use SHSH Blobs)
[Input] Select an option:
1) Select Target IPSW  3) Start Restore
2) Select Target SHSH  4) Go Back
#? 3
[Log] Device is in DFU mode, Pwned Restore Option enabled.
* If you want to disable Pwned Restore Option, place the device in Normal/Recovery mode
[Log] Device seems to be already in pwned DFU mode
* Pwned: checkm8
[Log] gaster reset
usb_timeout: 5
usb_abort_timeout_min: 0
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[Log] Checking firmware keys in ../resources/firmware/iPad4,1/16E227
[Log] Starting local server for firmware keys: /usr/bin/python -m SimpleHTTPServer 8888
[Log] Waiting for local server
Serving HTTP on 0.0.0.0 port 8888 ...
127.0.0.1 - - [07/Oct/2024 00:51:27] "GET / HTTP/1.1" 200 -
[Log] Manifest: ../saved/iPad4,1/16H81.plist
[Log] SEP: ../saved/iPad4,1/sep-firmware.j71.RELEASE-16H81.im4p
[Log] futurerestore nightly will be used for this restore: https://github.com/futurerestore/futurerestore
[Log] Checking for futurerestore updates...
[Log] Running futurerestore with command: ../saved/futurerestore_macos --latest-sep --no-baseband --no-rsep --use-pwndfu -t /Users/zygame/Desktop/shsh blobs/iPad4,1_12.2(16E227)_000005B4F07F7430(6274687136816).plist /Users/zygame/Desktop/shsh blobs/iPad_64bit_12.2_16E227_Restore.ipsw
Version: v2.0.0(1a5317ce543e6f6c583b31e379775e36b0ac0916-328)
img4tool version: 0.202-e1c37d6ce8c629ca9669efc9cb5b5f7d6810ed30-RELEASE
libipatcher version: 0.102-281f529530fdee361fe5ec5d72c14e2dc454d02f-RELEASE
PWNDFU(libpatchfinder) for 32-bit support: yes
PWNDFU(libpatchfinder) for 64-bit support: yes
Checking for updates...
ERROR: failed to check for futurerestore updates! continuing...
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket /Users/zygame/Desktop/shsh blobs/iPad4,1_12.2(16E227)_000005B4F07F7430(6274687136816).plist is done
User specified to use latest signed SEP
Downloading SEP
100 [===================================================================================================>]
Checking if SEP is being signed...
Sending TSS request attempt 1... response successfully received
SEP is being signed!

WARNING: user specified is not to flash a baseband. This can make the restore fail if the device needs a baseband!

If you added this flag by mistake, you can press CTRL-C now to cancel
Continuing restore in 10 9 8 7 6 5 4 3 2 1 Downloading the latest firmware components...
Finished downloading the latest firmware components!
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as j71ap, iPad4,1
Extracting BuildManifest from iPSW
Product version: 12.2
Product build: 16E227 Major: 16
Device supports Image4: true
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          OK (found "rdsk" with matching hash)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "RestoreTrustCache"       OK (found "rtsc" with matching hash)
[IMG4TOOL] checking hash for "SEP"                     OK (found "sepi" with matching hash)
[IMG4TOOL] checking hash for "StaticTrustCache"        OK (found "trst" with matching hash)
[IMG4TOOL] checking hash for "iBEC"                    OK (found "ibec" with matching hash)
[IMG4TOOL] checking hash for "iBSS"                    OK (found "ibss" with matching hash)
[IMG4TOOL] checking hash for "iBoot"                   OK (found "ibot" with matching hash)
[IMG4TOOL] failed to verify IM4M signature with error:
[exception]:
what=assure failed
code=18743314
line=286
file=ASN1DERElement.cpp
commit count=202
commit sha  =e1c37d6ce8c629ca9669efc9cb5b5f7d6810ed30
IM4M signature is not valid!
Cleaning up...
[exception]:
what=APTicket can't be used for this restore

code=81461316
line=1243
file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp
commit count=328
commit sha  =1a5317ce543e6f6c583b31e379775e36b0ac0916
Done: restoring failed!
[Log] Restoring done! Read the message below if any error has occurred:
* Please read the "Troubleshooting" wiki page in GitHub before opening any issue!
* Your problem may have already been addressed within the wiki page.
* If opening an issue in GitHub, please provide a FULL log/output. Otherwise, your issue may be dismissed.

* Save the terminal output now if needed. (macOS: Cmd+S, Linux: Ctrl+Shift+S)
* Legacy iOS Kit v24.10.01 (d45b8d7)
* Platform: macos (11.7.9 - x86_64)

**Comment by LukeZGD** [comment]
There seems to be an issue with your blob

Try to dump blobs again if what you have is an onboard dump and you're still on that version

Otherwise you can also try to enable the `--skip-blob` flag and see if it restores with that

**Comment by zygame110119** [comment]
[OUTPUT OF TERMINAL.TXT](https://github.com/user-attachments/files/17281919/OUTPUT.OF.TERMINAL.TXT)
Unfortunately, after turning it on, it didn't work.
