### ISSUE TITLE
iPhone 8 Issue with FutureRestore

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#595]
*** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.10.02 (efcdfb2)
* Platform: macos (13.7 - x86_64) 

* Device: iPhone 8 (GSM) (iPhone10,4 - d201ap) in DFU mode
* iOS Version: Unknown
* ECID: 1768701900812206
* Pwned: checkm8

 > Main Menu
[Input] Select an option:
1) Restore/Downgrade  3) Other Utilities
2) Save SHSH Blobs    4) Exit
#? 1

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.10.02 (efcdfb2)
* Platform: macos (13.7 - x86_64) 

* Device: iPhone 8 (GSM) (iPhone10,4 - d201ap) in DFU mode
* iOS Version: Unknown
* ECID: 1768701900812206
* Pwned: checkm8

 > Main Menu > Restore/Downgrade
* Note: Restoring to latest iOS for 64-bit devices is not supported on macOS, use iTunes/Finder instead for that

[Input] Select an option:
1) Other (Use SHSH Blobs)  3) Go Back
2) IPSW Downloader
#? 1

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.10.02 (efcdfb2)
* Platform: macos (13.7 - x86_64) 

* Device: iPhone 8 (GSM) (iPhone10,4 - d201ap) in DFU mode
* iOS Version: Unknown
* ECID: 1768701900812206
* Pwned: checkm8

* Only select unmodified IPSW for the selection. Do not select custom IPSWs

* Select Target IPSW to continue
* Check the SEP/BB compatibility chart: https://docs.google.com/spreadsheets/d/1Mb1UNm6g3yvdQD67M413GYSaJ4uoNhLgpkc7YKi3LBs

* Select Target SHSH to continue

 > Main Menu > Restore/Downgrade > Other (Use SHSH Blobs)
[Input] Select an option:
1) Select Target IPSW
2) Go Back
#? 1
[Input] Select your target IPSW file in the file selection window.

[Log] Selected IPSW file: /Users/apple/Desktop/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
[Log] Getting version from IPSW
Archive:  /Users/apple/Desktop/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
  inflating: ./Restore.plist         
[WARNING] Please read: You will need to follow a guide regarding activation files before and after the restore.
* You will encounter issues activating if you do not follow this.
* Link to guide: https://gist.github.com/pixdoet/2b58cce317a3bc7158dfe10c53e3dd32
[Input] Press Enter/Return to continue (or press Ctrl+C to cancel)
[Log] Getting SHA1 hash for /Users/apple/Desktop/iPhone_4.7_P3_14.8_18H17_Restore.ipsw...
[Log] Getting SHA1 hash from The Apple Wiki...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  351k    0  351k    0     0   297k      0 --:--:--  0:00:01 --:--:--  298k
[Log] Using saved SHA1 hash for this IPSW: c9f684a45241ce37ba74196b5740d60d08586b26
[Log] IPSW SHA1sum matches

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.10.02 (efcdfb2)
* Platform: macos (13.7 - x86_64) 

* Device: iPhone 8 (GSM) (iPhone10,4 - d201ap) in DFU mode
* iOS Version: Unknown
* ECID: 1768701900812206
* Pwned: checkm8

* Only select unmodified IPSW for the selection. Do not select custom IPSWs

* Selected Target IPSW: /Users/apple/Desktop/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
* Target Version: 14.8-18H17
* Check the SEP/BB compatibility chart: https://docs.google.com/spreadsheets/d/1Mb1UNm6g3yvdQD67M413GYSaJ4uoNhLgpkc7YKi3LBs

* Select Target SHSH to continue

 > Main Menu > Restore/Downgrade > Other (Use SHSH Blobs)
[Input] Select an option:
1) Select Target IPSW
2) Select Target SHSH
3) Go Back
#? 2
[Input] Select your target SHSH file in the file selection window.

[Log] Selected SHSH file: /Users/apple/Desktop/1768701900812206_iPhone10,4_d201ap_14.8-18H17_27325c8258be46e69d9ee57fa9a8fbc28b873df434e5e702a8b27999551138ae.shsh2
[Log] Validating...
Archive:  /Users/apple/Desktop/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
  inflating: BuildManifest.plist     
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 1:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 2:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (untrusted)
[IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"OK (found "msys" with matching hash)
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "AudioCodecFirmware"      OK (untrusted)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "ISP"                     OK (found "ispf" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "Liquid"                  OK (found "liqd" with matching hash)
[IMG4TOOL] checking hash for "Multitouch"              OK (untrusted)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          OK (found "rdsk" with matching hash)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "RestoreTrustCache"       OK (found "rtsc" with matching hash)
[IMG4TOOL] checking hash for "SE,UpdatePayload"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SEP"                     OK (found "sepi" with matching hash)
[IMG4TOOL] checking hash for "StaticTrustCache"        OK (found "trst" with matching hash)
[IMG4TOOL] checking hash for "SystemVolume"            OK (found "isys" with matching hash)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    OK (found "ibec" with matching hash)
[IMG4TOOL] checking hash for "iBSS"                    OK (found "ibss" with matching hash)
[IMG4TOOL] checking hash for "iBoot"                   OK (found "ibot" with matching hash)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)
[WARNING] COMPILED WITHOUT OPENSSL: can not im4m signature!
[IMG4TOOL] IM4M is valid for the given BuildManifest for the following restore:
BuildNumber : 18H17
BuildTrain : AzulSecuritySky
DeviceClass : d201ap
FDRSupport : YES
MobileDeviceMinVersion : 1253.100.1
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)

[IMG4TOOL] APTicket is GOOD!
[IMG4TOOL] SHSH2 contains generator 0x1111111111111111 which is GOOD for nonce in IM4M!

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.10.02 (efcdfb2)
* Platform: macos (13.7 - x86_64) 

* Device: iPhone 8 (GSM) (iPhone10,4 - d201ap) in DFU mode
* iOS Version: Unknown
* ECID: 1768701900812206
* Pwned: checkm8

* Only select unmodified IPSW for the selection. Do not select custom IPSWs

* Selected Target IPSW: /Users/apple/Desktop/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
* Target Version: 14.8-18H17
* Check the SEP/BB compatibility chart: https://docs.google.com/spreadsheets/d/1Mb1UNm6g3yvdQD67M413GYSaJ4uoNhLgpkc7YKi3LBs

* Selected Target SHSH: /Users/apple/Desktop/1768701900812206_iPhone10,4_d201ap_14.8-18H17_27325c8258be46e69d9ee57fa9a8fbc28b873df434e5e702a8b27999551138ae.shsh2
* Generator: 0x1111111111111111
* Selected SHSH file is validated
* Note: For OTA/onboard/factory blobs, try enabling the skip-blob flag

 > Main Menu > Restore/Downgrade > Other (Use SHSH Blobs)
[Input] Select an option:
1) Select Target IPSW  3) Start Restore
2) Select Target SHSH  4) Go Back
#? 1) Select Target IPSW  3) Start Restore
2) Select Target SHSH  4) Go Back
#? 3
[Log] Device is in DFU mode, Pwned Restore Option enabled.
* If you want to disable Pwned Restore Option, place the device in Normal/Recovery mode
[Log] Device seems to be already in pwned DFU mode
* Pwned: checkm8
[Log] gaster reset
usb_timeout: 5
usb_abort_timeout_min: 0
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[Log] Checking firmware keys in ../resources/firmware/iPhone10,4/18H17
[Log] Getting firmware keys for iPhone10,4-18H17
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  262k    0  262k    0     0   101k      0 --:--:--  0:00:02 --:--:--  101k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 8888 after 0 ms: Couldn't connect to server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15    0    15    0     0      0      0 --:--:--  0:00:39 --:--:--     3
[Error] Failed to download firmware keys.
* You may need to run wikiproxy to get firmware keys.
* For more details, go to the "Troubleshooting" wiki page in GitHub.
* Troubleshooting link: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting#running-wikiproxy

**Comment by LukeZGD** [comment]
the m1sta api for firmware keys was down a few hours ago, but its now back up and working now, just try again.

you can also use wikiproxy running it background: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting#running-wikiproxy
