### ISSUE TITLE
add this to legacy ios kit 

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#597]
https://gist.github.com/Orangera1n/fa3ca03d6aa9f5be963fd3b72c3f4225

**Comment by LukeZGD** [comment]
sorry, i wont be doing it since this is a niche functionality to add tbh, and something that i cant test. for a more updated guide, ig check this out https://gist.github.com/pixdoet/2b58cce317a3bc7158dfe10c53e3dd32
