### ISSUE TITLE
iPad5,3 - Unable to downgrade from iOS 15.6 to iOS 14.1 with SHSH blobs

### ISSUE THREAD

**Issue by dippergaming** [LukeZGD/Legacy-iOS-Kit#598]
Unfortunately, I was unable to downgrade my iPad Air 2 with SHSH blobs by using the —skip-blob flag because it had the 0x1111111111111111 generator set. This is the error it gave me:

ReverseProxy[Ctrl]: (status=2)  Terminated
ERROR:  Could not read data (-256).  Aborting.
Cleaning up…
[exception]:
what=ERROR: Unable to restore device

I tried every USB port possible with a USB-A type Lightning port and it still did not work.

**Comment by LukeZGD** [comment]
might be a futurerestore issue that i dont know about, better ask for help in futurerestore repo/server instead, make sure to provide the whole log/terminal output

**Comment by dippergaming** [comment]
Fixed it. It was a storage issue on my iPad.
