### ISSUE TITLE
Please add support to fedora atomic desktops (Silverblue/Kinoite/...)

### ISSUE THREAD

**Issue by ExodowRRGB** [LukeZGD/Legacy-iOS-Kit#600]
The tool will try to install using dnf instead of rpm-ostree

**Comment by LukeZGD** [comment]
Will try to do this by the weekend

**Comment by LukeZGD** [comment]
Now supported as of v24.10.08, note that I have only tested basic functionality so far

Also, users will need to do toolbox/build environment setup manually if pyenv/python2 is needed (like for ipwndfu): https://github.com/pyenv/pyenv/wiki#suggested-build-environment
