### ISSUE TITLE
Unable to create ‘/DS_Store.dpkg-new’ (while processing ‘./.DS_Store’): Read-only file system

### ISSUE THREAD

**Issue by Ruri040** [LukeZGD/Legacy-iOS-Kit#605]
I was trying to downgrade my iPad Mini 2 to iOS 10.3.3 using linux and got stuck in the dfu part so I decided to use the iPwnder Lite in the repo, but when I try to install the package I get this error:

dpkg: error processing archive /var/tmp//apt-dpkg-install-b75XjJ/6-ipwnderlite_1.0.63_iphoneos-arm64.deb (--unpack):
unable to create '/ DS_Store.dpkg-new' (while processing
'./.DS_Store'): Read-only file system
Errors were encountered while processing:
/var/tmp//apt-dpkg-install-b75XjJ/6-ipwnderlite_1.0.63_iphoneos-arm64.deb
E: Sub-process /var/jb/us/bin/dpkg returned an error code (1)

What’s the issue here: I’m running an iPhone 13 with Dopamine.

**Comment by LukeZGD** [comment]
Oh, this is my fault for not testing before updating the package haha. I'll fix this rq

**Comment by Ruri040** [comment]
Don’t worry haha, thanks for the fast response.

**Comment by LukeZGD** [comment]
I have fixed the ipwnderlite package now, you may now try installing it again
