### ISSUE TITLE
4s with 9.3.6 not active

### ISSUE THREAD

**Issue by RiberWang** [LukeZGD/Legacy-iOS-Kit#607]
when I connected 4s by ssh, use mount.sh happen this error
-sh-4.0# mount.sh
Waiting for disks...
/dev/disk0s1s1 already mounted on /mnt1
Mounting /dev/disk0s1s2 on /mnt2
mount_hfs: Operation not permitted
what should I do?

**Comment by LukeZGD** [comment]
what build number did you use for the ramdisk?

**Comment by LukeZGD** [comment]
solution is to use ios 9 for build number (like 13A452)

ios 9+ can tend to be unreliable when it comes to mounting tho, so it may or may not work

**Comment by RiberWang** [comment]
update can work
