### ISSUE TITLE
Can we get an Alpine and Void Linux port of this project?

### ISSUE THREAD

**Issue by VenomousSteam81** [LukeZGD/Legacy-iOS-Kit#610]
I have a machine with Void linux and I also use Alpine a lot, was thinking it would be nice to have this support Void and Alpine. Best part is that I can help if needed!

**Comment by LukeZGD** [comment]
ill try to do this by the weekend

**Comment by LukeZGD** [comment]
i have added untested void "support", note that legacy ios kit's binaries are compiled for glibc, so those on musl will need something like gcompat, idk how well this works.

i wont bother with alpine for now, but i think most of the stuff should work as well from there. if you want to make a pr or something like that, feel free to do so if you are willing. the main libraries needed here is openssl 3, curl, and mostly compression libraries like zlib, libzip, lzma, zstd, etc. the script also checks for the following: unzip, zip, scp and ssh (openssh), patch, zenity, curl, xxd (vim), git. lastly, also include the stuff needed for pyenv https://github.com/pyenv/pyenv/wiki#suggested-build-environment
