### ISSUE TITLE
Cannot enter kDFU, failed to get kernel_baseel base

### ISSUE THREAD

**Issue by Mastereq20** [LukeZGD/Legacy-iOS-Kit#612]
![image](https://github.com/user-attachments/assets/48e3153c-c884-444b-90a0-fe690f790205)
I assume it cant enter kdfu because of the kerner_baseel error

**Comment by LukeZGD** [comment]
What is your device/iOS version? If you are jailbroken with Pangu, have you updated the untether by installing the latest deb?

**Comment by Mastereq20** [comment]
![image](https://github.com/user-attachments/assets/96663d23-aac0-4ddb-8c4f-00091f51c4f9)

**Comment by Mastereq20** [comment]
Wow really quick reply btw

**Comment by LukeZGD** [comment]
Wait... are you jailbroken with h3lix? Don't use that garbage, jailbreak with socket

**Comment by Mastereq20** [comment]
sorry i uploaded the same sscreenshot again 
![image](https://github.com/user-attachments/assets/580e42fe-1db0-47d3-b5bd-86aa1757928c)

**Comment by Mastereq20** [comment]
i will try on socket, im using Kok3Shix

**Comment by Mastereq20** [comment]
Well didn't think the jailbreak was the problem, guess i could have followed the guide more precisely. Thanks so much for the quick help!
