### ISSUE TITLE
6.1.3 not showing for iPad 2,5 ipad mini 1st gen

### ISSUE THREAD

**Issue by jkfoong** [LukeZGD/Legacy-iOS-Kit#613]
I can only see 8.4.1 but not 6.1.3 in the downgrade option for ipad mini 1st gen iPad 2,5
Is it not possible to downgrade?
Thanks

**Comment by LukeZGD** [comment]
yes it is not possible

(unless you have blobs, or do a dualboot, or do a tethered downgrade)
