### ISSUE TITLE
Waiting for disks...

### ISSUE THREAD

**Issue by RiberWang** [LukeZGD/Legacy-iOS-Kit#614]
4s with ssh ramdisk
-sh-4.0# mount.sh                                                                                                                             
Waiting for disks...

**Comment by LukeZGD** [comment]
whats supposed to be the issue here? waiting for disks is normal, it will continue mounting after a few seconds, should take less than a minute. if it does get stuck there forever though, maybe theres something wrong with the device

**Comment by RiberWang** [comment]
Until waiting for disks always
next step not work mnt1 and mnt2 is empty
