### ISSUE TITLE
Waiting for disks...

### ISSUE THREAD

**Issue by RiberWang** [LukeZGD/Legacy-iOS-Kit#615]
4s with ssh ramdisk
连接主机...
连接主机成功
Use mount.sh script to mount the partitions
Use reboot_bak to reboot
Use 'device_infos' to dump EMF keys (when imaging user volume)
-sh-4.0# mount.sh
Waiting for disks...

I'm stuck right now Waiting for disks...

**Comment by LukeZGD** [comment]
as i already told you in the last issue #614, this is not a legacy ios kit issue.

**Comment by RiberWang** [comment]
downgrade 6.1.3 show
Waiting for NAND (28)
stuck right now Waiting for NAND (28)

**Comment by LukeZGD** [comment]
your nand is probably dead, which means your device is dead

**Comment by RiberWang** [comment]
ssh conneted
input mount.sh will show
Waiting for disks...

**Comment by RiberWang** [comment]
nand is hard disk?
