### ISSUE TITLE
iPhone 4 iOS 6.1.3 downgrade [Error] Failed to find custom IPSW. Please run the script again

### ISSUE THREAD

**Issue by notimadam123** [LukeZGD/Legacy-iOS-Kit#616]
Tried with and without the memory option, also tried with ios 4.0 and 4.3.5
[legacyioskit.log](https://github.com/user-attachments/files/17689223/legacyioskit.log)

**Comment by LukeZGD** [comment]
cannot reproduce. ig check your system, try in a different distro or live usb or something
