### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MaciejJezierski** [LukeZGD/Legacy-iOS-Kit#620]
Trying to restore iOS 16.6.1 from 16.7 on iPhone 8 with blobs. After selecting target ipsw I have to select SHSH blobs but after selecting them I am getting `[Input] Enter path to target IPSW file (or press Ctrl+C to cancel): `message. I believe its an error because after copypasting the info from previus step (ipsw selection) I am getting `Selected Target SHSH: /Users/maciejjezierski/Downloads/FIREFOX/Legacy-iOS-Kit_macos_v24.11.04/iPhone_4.7_P3_16.6.1_20G81_Restore.ipsw` what is wrong as its path to ipsw not SHSH files. Then after proceeding I am getting segfault just after futurerestore command `../saved/futurerestore_macos --latest-sep --latest-baseband --no-rsep --use-pwndfu -t /Users/maciejjezierski/Downloads/FIREFOX/Legacy-iOS-Kit_macos_v24.11.04/iPhone_4.7_P3_16.6.1_20G81_Restore.ipsw /Users/maciejjezierski/Downloads/FIREFOX/Legacy-iOS-Kit_macos_v24.11.04/iPhone_4.7_P3_16.6.1_20G81_Restore.ipsw` which seems to be wrong as its having ipsw two times in arguments. Attached terminal dump. 

Note: I tried to paste path to shsh2 file instead of ipsw but its not letting me proceed then. 

[Dane wyjściowe Terminala.txt](https://github.com/user-attachments/files/17734150/Dane.wyjsciowe.Terminala.txt)

**Comment by LukeZGD** [comment]
Well yeah of course it won't work when you select the ipsw as the shsh file. Anyway, I can't reproduce whatever issue you're having when selecting an shsh blob as i can do that just fine and successfully restored. If you have any log/screenshot/recording of whatever is happening that might help, please do share. 

As for saying path to IPSW when an SHSH is supposed to be selected, I will be fixing that in the next update.

For now, you can try to do the futurerestore command manually, use the futurerestore binary in the saved folder, just copy paste the futurerestore command given in the log. Just replace the path next to `-t` to point to the correct blob, not ipsw, something like that
