### ISSUE TITLE
Tethered boot failing on iOS 7 Beta 1

### ISSUE THREAD

**Issue by victorlobe** [LukeZGD/Legacy-iOS-Kit#623]
Hello, 
first of all, thanks for your amazing tool. I use it nearly daily to downgrade various Legacy Decices. 
Today I wanted to downgrade an iPhone 5 (Global) to iOS 7 Beta 1 which worked flawlessly but when I wanna boot tethered the following error appears: 

`[Error] Failed to find device in Recovery mode (Timed out). Please run the script again. `

I tried it with and without the Jailbreak option but got no luck. Is there anything I'm missing or is this just a little bug? I think that beta versions are supported because there is a specific dialog in the tool that mentions that it is a beta. I also looked on Reddit but only found successes with the Beta. 

Thanks in advance and have a good one.

**Comment by LukeZGD** [comment]
Please provide a full log/terminal output

I dont think betas are supported in just boot right now

**Comment by LukeZGD** [comment]
v24.11.10 addresses this issue by adding an option to select IPSW to just boot menu
