### ISSUE TITLE
kDFU downgrade freezes at "Sending filesystem now"

### ISSUE THREAD

**Issue by korek644** [LukeZGD/Legacy-iOS-Kit#625]
Thing freezes at random % like: 21, 31, 61,56 ,45...
iPhone 4S iOS 9.3.6, kok3shi9 jailbreak, OpenSSH and kDFU installed succesfully.
kDFUapp gives me bundle iPhone 4,1 iOS6.1.3 and went into kDFU.
At LiK it asks me do i want to jailbreak, i say yes. Is your device already in iBBS, kDFU?  I say yes.
Goes nice then freezes after "sending fs now" and doesnt stop even after unplugging the device. (I sat there for an hour.)
Used the iOS 8.4.1 ipsw made by LiK.
Linux Mint 22

OUTPUT:

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.11.12 (d7bfcac)
* Platform: linux (Linux Mint 22 - x86_64) 

* Device: iPhone 4S (iPhone4,1 - n94ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 701859519816

* Only select unmodified IPSW for the selection. Do not select custom IPSWs

* Selected Target IPSW: ../iPhone4,1_8.4.1_12H321_Restore.ipsw
* Selected Target IPSW is validated

* This restore will use 9.3.6 baseband

 > Main Menu > Restore/Downgrade > iOS 8.4.1
[Input] Select an option:
1) Select Target IPSW
2) Download Target IPSW
3) Start Restore
4) Go Back
#? 3
[Input] Jailbreak Option
* When this option is enabled, your device will be jailbroken on restore.
* I recommend to enable this option to have the jailbreak and Cydia pre-installed.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): y
[Log] Jailbreak option enabled.

[Input] Memory Option for creating custom IPSW
* When this option is enabled, system RAM will be used for the IPSW creation process.
* I recommend to enable this option to speed up creating the custom IPSW.
* However, if your PC/Mac has less than 8 GB of RAM, disable this option.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): y
[Log] Memory option enabled.

[Log] Found existing Custom IPSW. Skipping IPSW creation.
[Log] Found existing saved 8.4.1 blobs: ../saved/shsh/701859519816_iPhone4,1_n94ap_8.4.1-12H321_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2
* Select Y if your device is in pwned iBSS/kDFU mode.
* Select N if this is not the case. (pwned using checkm8-a5)
* Failing to answer correctly will cause "Sending iBEC" to fail.
[Input] Is your device already in pwned iBSS/kDFU mode? (y/N): y
[Log] Pwned iBSS/kDFU mode specified by user.
[Log] Extracting IPSW: ../iPhone4,1_8.4.1_12H321_CustomJ.ipsw
Archive:  ../iPhone4,1_8.4.1_12H321_CustomJ.ipsw
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/058-24033-023.dmg  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/058-24104-023.dmg  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/058-24341-023.dmg  
 extracting: ../iPhone4,1_8.4.1_12H321_CustomJ/BuildManifest.plist  
   creating: ../iPhone4,1_8.4.1_12H321_CustomJ/Downgrade/
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Downgrade/RestoreDeviceTree  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Downgrade/RestoreKernelCache  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Downgrade/RestoreLogo  
   creating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/Trek-5.5.00.Release.bbfw  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/Trek-5.5.00.Release.plist  
   creating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/
   creating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/DeviceTree.n94ap.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/LLB.n94.RELEASE.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/applelogo@2x~iphone.s5l8940x.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batterycharging0@2x~iphone.s5l8940x.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batterycharging1@2x~iphone.s5l8940x.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batteryfull@2x~iphone.s5l8940x.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batterylow0@2x~iphone.s5l8940x.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/batterylow1@2x~iphone.s5l8940x.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/glyphplugin@2x~iphone-30pin.s5l8940x.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/iBoot.n94.RELEASE.img3  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/manifest  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/all_flash/all_flash.n94ap.production/recoverymode@2x~iphone-30pin.s5l8940x.img3  
   creating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/dfu/
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/dfu/iBEC.n94.RELEASE.dfu  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/dfu/iBSS.n94.RELEASE.dfu  
   creating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/usr/
   creating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/usr/local/
   creating: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/usr/local/standalone/
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/Restore.plist  
  inflating: ../iPhone4,1_8.4.1_12H321_CustomJ/kernelcache.release.n94  
 extracting: ../iPhone4,1_8.4.1_12H321_CustomJ/Firmware/Trek-6.7.00.Release.bbfw  
[Log] Running idevicerestore with command: sudo ../bin/linux/x86_64/idevicerestore -ew "../iPhone4,1_8.4.1_12H321_CustomJ.ipsw"
Found device in DFU mode
Found ECID 701859519816
Identified device as n94ap, iPhone4,1
Extracting BuildManifest from IPSW
Product Version: 8.4.1
Product Build: 12H321 Major: 12
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Getting ApNonce in dfu mode... 51 81 a6 05 d1 a6 b1 de 53 9b 53 68 26 0d 66 b8 88 f4 49 77 
checking for local shsh
Using cached SHSH
Using cached filesystem from '../iPhone4,1_8.4.1_12H321_CustomJ/058-24033-023.dmg'
Extracting iBSS.n94.RELEASE.dfu...
Personalizing IMG3 component iBSS...
reconstructed size: 80234
Sending iBSS (80234 bytes)...
[==================================================] 100.0%
Nonce: 51 81 a6 05 d1 a6 b1 de 53 9b 53 68 26 0d 66 b8 88 f4 49 77 
Extracting iBEC.n94.RELEASE.dfu...
Not personalizing component iBEC...
Sending iBEC (282844 bytes)...
[==================================================] 100.0%
INFO: device serial number is DX5LLG4WFML6
Getting ApNonce in recovery mode... 51 81 a6 05 d1 a6 b1 de 53 9b 53 68 26 0d 66 b8 88 f4 49 77 
Sending APTicket (2738 bytes)
Recovery Mode Environment:
iBoot build-version=iBoot-2261.30.37
iBoot build-style=RELEASE
ramdisk-size=0x4000000
Extracting 058-24341-023.dmg...
Not personalizing component RestoreRamDisk...
Sending RestoreRamDisk (20267100 bytes)...
Extracting RestoreDeviceTree...
Not personalizing component RestoreDeviceTree...
Sending RestoreDeviceTree (82480 bytes)...
Extracting RestoreKernelCache...
Not personalizing component RestoreKernelCache...
Sending RestoreKernelCache (9255676 bytes)...
About to restore device... 
Waiting for device...
Device 0fd4b06e441e9425a0443640bcc1535507211a14 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 13
Device 0fd4b06e441e9425a0443640bcc1535507211a14 has successfully entered restore mode
Hardware Information:
BoardID: 8
ChipID: 35136
UniqueChipID: 701859519816
ProductionMode: true
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Unmounting filesystems (29)
Unmounting filesystems (29)
Creating partition map (11)
Creating filesystem (12)
Creating filesystem (12)
Mounting filesystems (16)
Mounting filesystems (16)
Unmounting filesystems (29)
Unmounting filesystems (29)
About to send filesystem...
Connected to ASR
Validating the filesystem
Filesystem validated
Sending filesystem now... 
[==================================                ]  66.0%  (freezes here)

**Comment by LukeZGD** [comment]
You might want to check your USB cable/port/s since I can't reproduce this issue on my end

**Comment by LukeZGD** [comment]
figured out the issue, it's usbmuxd2. running `sudo killall usbmuxd usbmuxd2` or rebooting will fix this, and the script has been updated to do this in clean_usbmuxd.
