### ISSUE TITLE
Fix these issues

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#627]
UNTETHERED iPad 2 iOS 4.3.x Jailbreak via Legacy iOS Kit

iOS 3.x Downgrade Activation fix for iPod Touch 3G 

iOS 4.2.x iPhone3,3 Boot Errors Fix

**Comment by LukeZGD** [comment]
im pretty sure there have been multiple issues on here before about this, its not happening, all 3 of those

**Comment by gamelover-sergei** [comment]
> UNTETHERED iPad 2 iOS 4.3.x Jailbreak via Legacy iOS Kit
> 
> iOS 3.x Downgrade Activation fix for iPod Touch 3G
> 
> iOS 4.2.x iPhone3,3 Boot Errors Fix

ipad 2 4.3.x have untrethered jb
ipod touch 3g (3.0-last update for ipod touch 3g) no have activation
