### ISSUE TITLE
Cannot tether boot iOS 6 on macOS

### ISSUE THREAD

**Issue by Votreaux** [LukeZGD/Legacy-iOS-Kit#628]
24/11/2024

When I attempt to tether boot my iPad 4th generation (iOS 6.1.3), i go through the steps but I cannot get past "Just boot" (right before it starts the tether booting process), it just reprints the menu and I cannot go any further, so I am unable to boot my iPad (it was tether downgraded with Legacy iOS Kit in the past)

Log:

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.11.17 (8f309aa)
[Log] Running on platform: macos (13.7.1 - x86_64)
[Log] Checking Internet connection...
[Log] Checking for updates...
[Log] Finding device in Normal mode...
ERROR: No device found!
ERROR: No device found!
[Log] Finding device in Recovery/DFU mode...
[Log] Getting device info...
* Device: iPad 4 (Wi-Fi) (iPad3,4 - p101ap) in DFU mode
* iOS Version: Unknown
* ECID: **Removed**

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.11.17 (8f309aa)
* Platform: macos (13.7.1 - x86_64) 

* Device: iPad 4 (Wi-Fi) (iPad3,4 - p101ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: **Removed**

 > Main Menu
[Input] Select an option:
1) Restore/Downgrade  3) Just Boot	    5) Other Utilities
2) Jailbreak Device   4) Save SHSH Blobs    6) Exit
#? 3

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.11.17 (8f309aa)
* Platform: macos (13.7.1 - x86_64) 

* Device: iPad 4 (Wi-Fi) (iPad3,4 - p101ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: **Removed**

 > Main Menu > Other Utilities > Just Boot
* You are about to do a tethered boot.
* To know more about build version, go here: https://theapplewiki.com/wiki/Firmware

* Enter build version or select IPSW to continue

* You may enter custom bootargs (optional, experimental option)
* Default Bootargs: -v pio-error=0

[Input] Select an option:
1) Enter Build Version	3) Custom Bootargs
2) Select IPSW		4) Go Back
#? 1
* Enter the build version of your device's current iOS version to boot.
[Input] Enter build version (eg. 10B329): 10B329

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.11.17 (8f309aa)
* Platform: macos (13.7.1 - x86_64) 

* Device: iPad 4 (Wi-Fi) (iPad3,4 - p101ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: **Removed**

 > Main Menu > Other Utilities > Just Boot
* You are about to do a tethered boot.
* To know more about build version, go here: https://theapplewiki.com/wiki/Firmware

* Build Version entered: 10B329

* You may enter custom bootargs (optional, experimental option)
* Default Bootargs: -v pio-error=0

[Input] Select an option:
1) Enter Build Version	3) Custom Bootargs	5) Go Back
2) Select IPSW		4) Just Boot
#? 4

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.11.17 (8f309aa)
* Platform: macos (13.7.1 - x86_64) 

* Device: iPad 4 (Wi-Fi) (iPad3,4 - p101ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: **Removed**

 > Main Menu > Other Utilities > Just Boot
* You are about to do a tethered boot.
* To know more about build version, go here: https://theapplewiki.com/wiki/Firmware

* Build Version entered: 10B329

* You may enter custom bootargs (optional, experimental option)
* Default Bootargs: -v pio-error=0

[Input] Select an option:
1) Enter Build Version	3) Custom Bootargs	5) Go Back
2) Select IPSW		4) Just Boot
#?

**Comment by LukeZGD** [comment]
found the issues now, will be fixing it in a bit
