### ISSUE TITLE
Add Support for iOS 10.x Restores with powdersn0w

### ISSUE THREAD

**Issue by Jefferyat** [LukeZGD/Legacy-iOS-Kit#629]
Also Add P0insettia-plus support for iPhone 5 iOS 7.0.x and iPhone 5C iOS 7.0.x and iOS 7.1.x

**Comment by LukeZGD** [comment]
hmm I would like to keep p0insettia plus as a separate tool, so I won't be integrating it into LiK

as for adding more support, I don't think I will be doing it anytime soon, but I might look into it sometime by updating the patchers to be more dynamic like iBoot32Patcher, no promises tho
