### ISSUE TITLE
Request to add a parameter for just boot

### ISSUE THREAD

**Issue by fullpwn** [LukeZGD/Legacy-iOS-Kit#631]
Heya!

Would it be possible to add a parameter for Just Boot with options to specify the build number?
I think it would be extremely beneficial to jump straight into the booting process instead of going through the CLI. If you don't geet what I mean by this, I will give you a rough example. 

`./restore.sh --just-boot --model=5,2 --version=10B350`
Entering that should skip the CLI and start the pwning and ramdisk process.
Why it would be beneficial, is because some devices (mine included) can kernel panic and restart at random times. Having this command easily accessible would make things a lot more simpler.

Thanks! <3

**Comment by LukeZGD** [comment]
yea im considering revamping legacy ios kit's argument parser sometime, ig i may start with this just boot option for now

**Comment by LukeZGD** [comment]
Added. Just Boot usage: `./restore.sh --just-boot --device=<device> --build-id=<id>"`

Optional: `--bootargs="<bootargs>"

Example: `./restore.sh --just-boot --device=iPhone5,2 --build-id=12H321`
