### ISSUE TITLE
Get stuck in recovery mode(white apple screen) in processing jailbreak

### ISSUE THREAD

**Issue by zhengling** [LukeZGD/Legacy-iOS-Kit#635]
Dear LukeZGD project team:
I use my ipad2 with ios9.3.6v and has been downgraded successfully to recommended 8.4.1 in Jailbreak option enabled. And for some small problem I reset(Not in erase mode) my ipad.This wipe off cydia icon in the screen. So I select Jailbreak Device in the menu to jailbreak again(attached below), and no error reported. However it being stucked after rebooted system. How to avoid this happen
[TerminalOutput_Jailbreak.txt](https://github.com/user-attachments/files/18145152/TerminalOutput_Jailbreak.txt)
Thank for your concern

**Comment by LukeZGD** [comment]
Reset? If you used the "Erase All Content and Settings" in the settings app, that is a mistake. You should restore to 9.3.6 and downgrade to 8.4.1 again

**Comment by zhengling** [comment]
If the Cydia icon is losted in accident which is the easiest and most convenient way to recover it. Restore,jailbreak and downgrade is terrible for me to do it.

**Comment by LukeZGD** [comment]
There is not much you can do at that point, sorry

Unless you have an Arduino/Pi Pico, but that's a hassle
