### ISSUE TITLE
After downgrading an iPad to version 8.4.1, can I perform an iTunes data recovery operation on it?

### ISSUE THREAD

**Issue by zhengling** [LukeZGD/Legacy-iOS-Kit#640]
Dear LukeZGD project team:
My ipad2 was downgraded to version 8.4.1 successfully, Can I use the existing backup data on iTunes, which was made before downgrading, to perform a restore operation on my downgraded iPad 2? Is this feasible?
Thank you for your concern

**Comment by LukeZGD** [comment]
yes you can spoof the info plist to restore an itunes backup on an older ios version, but since this is between major versions, things might break, do it at your own risk
