### ISSUE TITLE
Failed to downgrade iPhone4s to ios8.0beta

### ISSUE THREAD

**Issue by P1Ter56** [LukeZGD/Legacy-iOS-Kit#642]
I have 8.0b shsh and ipsw.When I tried to downgrade it, an error occurred.

curl: (7) Failed to connect to 127.0.0.1 port 8888: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15    0    15    0     0      0      0 --:--:--  0:00:36 --:--:--     3
[Error] Failed to download firmware keys.

I don't know what's wrong with it.Hope that someone can help me.Thanks!

**Comment by LukeZGD** [comment]
see the wikiproxy section in troubleshooting: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting#running-wikiproxy
