### ISSUE TITLE
Needs to add clear NVRAM option for SHSH restores on powdersn0wed devices

### ISSUE THREAD

**Issue by MDX-Tom** [LukeZGD/Legacy-iOS-Kit#643]
The issue #633 (iPad 1 downgrade to 4.3.1 with SHSH recovery loop) has been solved with clearing NVRAM before restoring. 

It turned out that my iPad had been powdersn0wed before, and restoring with SHSH blobs may not work if I do not clear the NVRAM.
So clearing the NVRAM is required before restoring with SHSH if the device has been powdersn0wed.

**Comment by LukeZGD** [comment]
> clearing the NVRAM is required before restoring with SHSH

clearing NVRAM after the restore will work too

anyway it's not really feasible to detect powdersn0w'ed devices, so i'll just add a note about clearing nvram when they attempt to exit recovery mode for powdersn0w'able devices

**Comment by MDX-Tom** [comment]
Okay, or maybe you could add a manual option along with the Jailbreak and Memory options asking for something like  "Clear NVRAM if powdersn0wed? (y/N)"

**Comment by LukeZGD** [comment]
i have added the note now with exit recovery option

the clear nvram option has always been mentioned in the wiki page too, users that seek to troubleshoot should check the wiki pages: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/powdersn0w
