### ISSUE TITLE
Unable to do a tethered downgrade of a iphone 4 Rev A to iOS 6.0

### ISSUE THREAD

**Issue by Polep222** [LukeZGD/Legacy-iOS-Kit#645]
So I'm trying to downgrade an iphone 4 rev a (3.2) and it only have a tethered downgrade so when I select restore/downgrade I put the .ipsw download from the website it give me a error 
![Uploading 17354981788575161434017010927559.jpg…]()
The jailbreak option is on and the memory option is off I'm using a live CD is it because I don't have space or ? Thank you if u can help me

**Comment by LukeZGD** [comment]
i cant see the image, but i think i know your issue.

your live usb should have persistent storage. create your live usb using rufus: https://www.linuxuprising.com/2019/08/rufus-creating-persistent-storage-live.html
