### ISSUE TITLE
Can you add a function to allow iPhone3,1 to restore custom ipsw?

### ISSUE THREAD

**Issue by Pingzi610** [LukeZGD/Legacy-iOS-Kit#646]
I want to restore an iPhone3,1 with 4.2.1 shsh blob, but it won't boot properly if I just use Legacy iOS Kit to restore. I use iFaith to create custom ipsw and use iTunes 10.5 to restore it several month ago, but now iTunes won't recognize my iPhone in pwnDFU mode. I've noticed that the script does support iPod touch 4 to restore a custom ipsw. Now I use this function to restore my iPod touch 4 to iOS 4.2.1 with iFaith's custom ipsw, and it works fine. I wonder if you can allow iPhone3,1 to restore a custom firmware such as iFaith's custom firmware, so that I can restore iOS 4.2.1 with shsh blob properly? Thank you.
![QQ图片20241231224755](https://github.com/user-attachments/assets/4b3d515f-b334-4175-8f90-a39e8194babd)
(I modified restore.sh to allow the iPhone3,1 in the picture to restore iFaith's custom firmware. )
![QQ图片20241231225044](https://github.com/user-attachments/assets/7f257637-6158-4dca-bf3d-d76c985fb6c3)

**Comment by LukeZGD** [comment]
i dont really want usage of the custom ipsw option on iphone 4 devices but ig ill just enable it for all a4 and older devices since i dont really care much for them anymore at this point tbh (its not that i know how to fix that issue with 4.2.x anyway)

**Comment by LukeZGD** [comment]
done
